apiVersion: v2
name: apexmail
description: ApexMail — enterprise email infrastructure for private cloud deployment
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - email
  - smtp
  - mta
  - tracking
  - hipaa
  - enterprise
home: https://apexmail.ee
sources:
  - https://github.com/apexmail
maintainers:
  - name: ApexMail Engineering
    email: engineering@apexmail.ee
dependencies:
  - name: postgresql
    version: "15.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "19.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: clickhouse
    version: "6.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: clickhouse.enabled
