apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: worker
  namespace: apexmail
  labels:
    app.kubernetes.io/name: worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: worker