apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  namespace: apexmail
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/component: worker
automountServiceAccountToken: false