apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: apexmail
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/component: worker
spec:
  selector:
    app.kubernetes.io/name: worker
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
  type: ClusterIP