[package]
name = "apexmail-db"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
urlencoding = { workspace = true }
once_cell = { workspace = true }
prometheus = "0.14"
apexmail-lib = { path = "../apexmail-lib" }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "macros"] }
