BEGIN;

DROP VIEW IF EXISTS subscriptions;
DROP VIEW IF EXISTS usage_events;

DROP TABLE IF EXISTS billing_audit_log CASCADE;
DROP TABLE IF EXISTS cost_alerts CASCADE;
DROP TABLE IF EXISTS tenant_costs CASCADE;
DROP TABLE IF EXISTS viral_conversions CASCADE;
DROP TABLE IF EXISTS viral_clicks CASCADE;
DROP TABLE IF EXISTS viral_impressions CASCADE;
DROP TABLE IF EXISTS purchase_orders CASCADE;
DROP TABLE IF EXISTS contract_amendments CASCADE;
DROP TABLE IF EXISTS enterprise_contracts CASCADE;
DROP TABLE IF EXISTS wallet_reservations CASCADE;
DROP TABLE IF EXISTS wallet_transactions CASCADE;
DROP TABLE IF EXISTS wallets CASCADE;
DROP TABLE IF EXISTS sla_credits CASCADE;
DROP TABLE IF EXISTS sla_metrics CASCADE;
DROP TABLE IF EXISTS dunning_history CASCADE;
DROP TABLE IF EXISTS dunning_states CASCADE;
DROP TABLE IF EXISTS usage_alerts_sent CASCADE;
DROP TABLE IF EXISTS usage_alert_configs CASCADE;
DROP TABLE IF EXISTS metering_aggregates CASCADE;
DROP TABLE IF EXISTS metering_events_default CASCADE;
DROP TABLE IF EXISTS metering_events CASCADE;
DROP TABLE IF EXISTS invoices CASCADE;
DROP TABLE IF EXISTS stripe_webhook_events CASCADE;
DROP TABLE IF EXISTS stripe_subscriptions CASCADE;
DROP TABLE IF EXISTS stripe_customers CASCADE;
DROP TABLE IF EXISTS plan_overrides CASCADE;
DROP TABLE IF EXISTS plans CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;

DROP SEQUENCE IF EXISTS invoice_number_seq;
DROP SEQUENCE IF EXISTS contract_number_seq;

COMMIT;
