<?php

declare(strict_types=1);

namespace KiwiCaptcha\Tests\Fixtures;

/**
 * Authoritative cross-language test vectors.
 *
 * Generated by the Rust crate (packages/kiwicaptcha) — the values here are
 * what the Rust implementation produces; the PHP implementation MUST
 * reproduce them byte-for-byte. Regenerate with
 *   cargo run --release --manifest-path /tmp/vecgen/Cargo.toml
 */
final class Vectors
{
    public const SECRET = '0123456789abcdef0123456789abcdef';

    public const CLIENT_IP = '203.0.113.7';

    public const ISSUED_AT = 1_800_000_000;

    public const NOW = 1_800_000_100;

    /** Rust: ip_hash = sha256_hex(secret || ip) */
    public const IP_HASH = '9c50b8d493de847656a168d0408bd4455994df2fc0b1e94bab5a85d64850034b';

    /** SHA-256 vector (Rust outcome=Valid, counter=158, target_bits=8). */
    public const SHA = [
        'nonce' => '2l0IVh1xuKNjzcCDyV+X0lrceMHlHvmqCs5MdDw8tw0=',
        'challenge' => 'MmwwSVZoMXh1S05qemNDRHlWK1gwbHJjZU1IbEh2bXFDczVNZER3OHR3MD18bG9naW58OWM1MGI4ZDQ5M2RlODQ3NjU2YTE2OGQwNDA4YmQ0NDU1OTk0ZGYyZmMwYjFlOTRiYWI1YTg1ZDY0ODUwMDM0YnwxODAwMDAwMDAw.dee1893de8e9f57e974af43ec5b6e7523f7d09cee038a8edd5df59ad2f9248ba',
        'salt' => 'phUfA189G9A5KMv3r+wzLA==',
        'prefix' => 'MmwwSVZoMXh1S05qemNDRHlWK1gwbHJjZU1IbEh2bXFDczVNZER3OHR3MD18bG9naW58OWM1MGI4ZDQ5M2RlODQ3NjU2YTE2OGQwNDA4YmQ0NDU1OTk0ZGYyZmMwYjFlOTRiYWI1YTg1ZDY0ODUwMDM0YnwxODAwMDAwMDAw.dee1893de8e9f57e974af43ec5b6e7523f7d09cee038a8edd5df59ad2f9248ba|phUfA189G9A5KMv3r+wzLA==|',
        'algorithm' => 'sha256',
        'm_kib' => 0,
        't' => 1,
        'p' => 1,
        'target_bits' => 8,
        'counter' => 158,
        'outcome' => 'Valid',
    ];

    /** Argon2id vector (Rust outcome=Valid, counter=21, target_bits=4, t=3). */
    public const ARGON2 = [
        'nonce' => 'Sn89Ua2qPftlfNO2K9jZSWB52OpcuYwRD1kf2GDhAX4=',
        'challenge' => 'U244OVVhMnFQZnRsZk5PMks5alpTV0I1Mk9wY3VZd1JEMWtmMkdEaEFYND18bG9naW58OWM1MGI4ZDQ5M2RlODQ3NjU2YTE2OGQwNDA4YmQ0NDU1OTk0ZGYyZmMwYjFlOTRiYWI1YTg1ZDY0ODUwMDM0YnwxODAwMDAwMDAw.2757c7cdabe01a52d31cb91900d64eaaae881dd25353dd79267ce35298b3c239',
        'salt' => '6HL5BOgvD4ryefTBPNhS8A==',
        'prefix' => 'U244OVVhMnFQZnRsZk5PMks5alpTV0I1Mk9wY3VZd1JEMWtmMkdEaEFYND18bG9naW58OWM1MGI4ZDQ5M2RlODQ3NjU2YTE2OGQwNDA4YmQ0NDU1OTk0ZGYyZmMwYjFlOTRiYWI1YTg1ZDY0ODUwMDM0YnwxODAwMDAwMDAw.2757c7cdabe01a52d31cb91900d64eaaae881dd25353dd79267ce35298b3c239|6HL5BOgvD4ryefTBPNhS8A==|',
        'algorithm' => 'argon2id',
        'm_kib' => 64,
        't' => 3,
        'p' => 1,
        'target_bits' => 4,
        'counter' => 21,
        'outcome' => 'Valid',
    ];
}
