apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: ClickHouse
    uid: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: https://clickhouse:8443
    jsonData:
      defaultDatabase: apexmail
      username: apexmail
      protocol: https
      port: 8443
      server: clickhouse
      tlsSkipVerify: false
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
    editable: false
  - name: PostgreSQL
    uid: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: apexmail
    user: apexmail
    jsonData:
      sslmode: require
      postgresVersion: 1600
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    editable: false
  - name: Tempo
    uid: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
