"""Customer profiles for ApexMail AI agent test contexts.

50 simulated customer profiles spanning all 7 plans (Free, Starter, Pro,
Growth, Scale, Enterprise, Pay-As-You-Go), 15+ industries, and every major
issue type (DKIM, SPF, bounce, complaint, webhook, IP blocklist, warming,
dunning, SSO, rate-limit, rendering, etc.).

Each profile is a dict whose keys match the placeholders in
CUSTOMER_CONTEXT_TEMPLATE from prompts_v2.py.
"""

PROFILES: dict[str, dict[str, str]] = {

    # ======================================================================
    # Free Plan Profiles
    # ======================================================================

    # ── free_brand_new ──────────────────────────────────────────────
    "free_brand_new": {
        "account_id": 'acct_qw3r7t',
        "plan_name": 'Free',
        "plan_price": '0',
        "emails_sent": '0',
        "email_limit": '3,000',
        "api_calls": '23',
        "api_call_limit": '50,000',
        "team_count": '1',
        "team_limit": '1',
        "created_at": '2026-02-17',
        "billing_cycle_date": 'Free plan (no billing cycle)',
        "domain_count": '0',
        "domain_details": '- No domains configured yet',
        "team_members": '- maria@mariastudio.com (Admin, owner)',
        "api_keys": "- 'Default Key' (am_live_qw3r...) — scopes: send, read — last used: 30 minutes ago",
        "webhooks_summary": '- No webhooks (not available on Free plan)',
        "template_count": '0',
        "templates_summary": '- No templates created',
        "contact_count": '0',
        "recent_events": '- No sending activity',
        "open_issues": '- No domains added — cannot send until a domain is verified',
    },

    # ── free_hitting_limits ─────────────────────────────────────────
    "free_hitting_limits": {
        "account_id": 'acct_2n5v8q',
        "plan_name": 'Free',
        "plan_price": '0',
        "emails_sent": '980',
        "email_limit": '3,000',
        "api_calls": '8,900',
        "api_call_limit": '50,000',
        "team_count": '1',
        "team_limit": '1',
        "created_at": '2026-01-28',
        "billing_cycle_date": 'Free plan (no billing cycle)',
        "domain_count": '1',
        "domain_details": '- myshop.com: Verified (SPF: pass, DKIM: pass, DMARC: none — no DMARC record)',
        "team_members": '- owner@myshop.com (Admin, owner)',
        "api_keys": "- 'My Key' (am_live_2n5v...) — scopes: send — last used: today",
        "webhooks_summary": '- No webhooks (not available on Free plan)',
        "template_count": '1',
        "templates_summary": "- 'Order Receipt' (tmpl_rcpt01)",
        "contact_count": '312',
        "recent_events": '- 980 sent, 960 delivered (98.0%), 8 bounced (0.8%), 0 complaints',
        "open_issues": '- Email usage: 980/3,000 (32.7% used)',
    },

    # ── free_hobby_blogger ──────────────────────────────────────────
    "free_hobby_blogger": {
        "account_id": 'acct_hb4m2k',
        "plan_name": 'Free',
        "plan_price": '0',
        "emails_sent": '340',
        "email_limit": '3,000',
        "api_calls": '1,200',
        "api_call_limit": '50,000',
        "team_count": '1',
        "team_limit": '1',
        "created_at": '2025-10-05',
        "billing_cycle_date": 'Free plan (no billing cycle)',
        "domain_count": '1',
        "domain_details": '- craftyblog.net: Verified (SPF: pass, DKIM: pass, DMARC: none)',
        "team_members": '- jenny@craftyblog.net (Admin, owner)',
        "api_keys": "- 'Blog Notifications' (am_live_hb4m...) — scopes: send — last used: 2 days ago",
        "webhooks_summary": '- No webhooks (not available on Free plan)',
        "template_count": '1',
        "templates_summary": "- 'New Post Alert' (tmpl_npa01)",
        "contact_count": '178',
        "recent_events": '- 340 sent, 335 delivered (98.5%), 3 bounced (0.9%), 0 complaints',
        "open_issues": 'None',
    },

    # ── free_spf_broken ─────────────────────────────────────────────
    "free_spf_broken": {
        "account_id": 'acct_sp2f8z',
        "plan_name": 'Free',
        "plan_price": '0',
        "emails_sent": '450',
        "email_limit": '3,000',
        "api_calls": '3,200',
        "api_call_limit": '50,000',
        "team_count": '1',
        "team_limit": '1',
        "created_at": '2025-12-01',
        "billing_cycle_date": 'Free plan (no billing cycle)',
        "domain_count": '1',
        "domain_details": '- petgrooming.co: Verified (SPF: fail — multiple SPF records, DKIM: pass, DMARC: none)',
        "team_members": '- sam@petgrooming.co (Admin, owner)',
        "api_keys": "- 'Appointment Reminders' (am_live_sp2f...) — scopes: send — last used: today",
        "webhooks_summary": '- No webhooks (not available on Free plan)',
        "template_count": '1',
        "templates_summary": "- 'Appointment Reminder' (tmpl_apt01)",
        "contact_count": '490',
        "recent_events": '- 450 sent, 380 delivered (84.4%), 25 bounced (5.6%), 0 complaints\n- Deliverability dropped after adding Mailchimp SPF record 5 days ago',
        "open_issues": '- SPF failure: 2 SPF TXT records found (ApexMail + Mailchimp). Only 1 SPF record per domain allowed.',
    },

    # ======================================================================
    # Starter Plan Profiles
    # ======================================================================

    # ── starter_bounce_spike ────────────────────────────────────────
    "starter_bounce_spike": {
        "account_id": 'acct_bs3k7m',
        "plan_name": 'Starter',
        "plan_price": '25',
        "emails_sent": '20,100',
        "email_limit": '50,000',
        "api_calls": '95,000',
        "api_call_limit": '500,000',
        "team_count": '2',
        "team_limit": '5',
        "created_at": '2025-07-01',
        "billing_cycle_date": 'Renews on the 1st of each month',
        "domain_count": '1',
        "domain_details": '- newsletters.brightshop.com: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)',
        "team_members": '- sarah@brightshop.com (Admin, owner)\n- mark@brightshop.com (Editor)',
        "api_keys": "- 'Main Key' (am_live_bs3k...) — scopes: send, read — last used: 30 min ago",
        "webhooks_summary": '- wh_bs01: https://brightshop.com/hooks/email — Events: bounced, delivered — Status: active',
        "template_count": '4',
        "templates_summary": "- 'Welcome' (tmpl_w01)\n- 'Promo Blast' (tmpl_pb01)\n- 'Order Update' (tmpl_ou01)\n- 'Re-engagement' (tmpl_re01)",
        "contact_count": '18,500',
        "recent_events": '- 20,100 sent, 17,800 delivered (88.6%), 2,200 hard bounced (11.0%), 14 complaints (0.07%)\n- Hard bounce spike started 2 days ago after importing a purchased contact list\n- Suppression list has 420 entries',
        "open_issues": '- Bounce rate 11.0% (threshold: 2%)\n- 2,200 hard bounces in last 7 days — mostly invalid addresses from recent list import\n- Account at risk of suspension if bounce rate not reduced',
    },

    # ── starter_dunning_soft ────────────────────────────────────────
    "starter_dunning_soft": {
        "account_id": 'acct_ds5r2m',
        "plan_name": 'Starter',
        "plan_price": '25',
        "emails_sent": '14,200',
        "email_limit": '50,000',
        "api_calls": '105,000',
        "api_call_limit": '500,000',
        "team_count": '2',
        "team_limit": '5',
        "created_at": '2025-09-10',
        "billing_cycle_date": 'Renews on the 10th of each month',
        "domain_count": '1',
        "domain_details": '- campfire.club: Verified (SPF: pass, DKIM: pass, DMARC: pass)',
        "team_members": '- owner@campfire.club (Admin, owner)\n- helper@campfire.club (Editor)',
        "api_keys": "- 'Main' (am_live_ds5r...) — scopes: send, read — last used: 1 hour ago",
        "webhooks_summary": '- wh_cc01: https://campfire.club/api/email — Events: delivered, bounced — Status: active',
        "template_count": '2',
        "templates_summary": "- 'Event Invite' (tmpl_ei01)\n- 'Membership Renewal' (tmpl_mr01)",
        "contact_count": '5,600',
        "recent_events": '- 14,200 sent, 13,900 delivered (97.9%), 42 bounced (0.3%), 2 complaints (0.01%)',
        "open_issues": '- ⚠️ Payment failed — Invoice #INV-2026-0892 ($25) past due since Feb 10\n- Account in soft-suspended state — sending still works during 7-day grace period\n- Grace period ends Feb 17 (tomorrow)',
    },

    # ── starter_gdpr_deletion ───────────────────────────────────────
    "starter_gdpr_deletion": {
        "account_id": 'acct_gd2r8m',
        "plan_name": 'Starter',
        "plan_price": '25',
        "emails_sent": '9,800',
        "email_limit": '50,000',
        "api_calls": '62,000',
        "api_call_limit": '500,000',
        "team_count": '2',
        "team_limit": '5',
        "created_at": '2025-05-01',
        "billing_cycle_date": 'Renews on the 1st of each month',
        "domain_count": '1',
        "domain_details": '- euroservice.eu: Verified (SPF: pass, DKIM: pass, DMARC: pass)',
        "team_members": '- owner@euroservice.eu (Admin, owner)\n- staff@euroservice.eu (Editor)',
        "api_keys": "- 'Main' (am_live_gd2r...) — scopes: send, read, contacts — last used: today",
        "webhooks_summary": '- wh_es01: https://euroservice.eu/webhooks — Events: delivered, bounced, unsubscribed — Status: active',
        "template_count": '3',
        "templates_summary": "- 'Service Update' (tmpl_su01)\n- 'Invoice' (tmpl_inv01)\n- 'Welcome' (tmpl_wel01)",
        "contact_count": '2,800',
        "recent_events": '- 9,800 sent, 9,650 delivered (98.5%), 20 bounced (0.2%), 1 complaint (0.01%)',
        "open_issues": '- GDPR data deletion request received from subscriber jan.muller@example.de\n- Must process within 30 days (72-hour processing after confirmation)\n- Need to delete: contact record, all email events, analytics data, any templates with personal data',
    },

    # ── starter_healthy ─────────────────────────────────────────────
    "starter_healthy": {
        "account_id": 'acct_8f3k2j',
        "plan_name": 'Starter',
        "plan_price": '25',
        "emails_sent": '18,240',
        "email_limit": '50,000',
        "api_calls": '142,000',
        "api_call_limit": '500,000',
        "team_count": '2',
        "team_limit": '5',
        "created_at": '2025-06-15',
        "billing_cycle_date": 'Renews on the 15th of each month',
        "domain_count": '1',
        "domain_details": '- acmecorp.com: Verified (SPF: pass, DKIM: pass, DMARC: pass)',
        "team_members": '- alice@acmecorp.com (Admin, owner)\n- bob@acmecorp.com (Editor)',
        "api_keys": "- 'Production Key' (am_live_8f3k...) — scopes: send, read — last used: 2h ago\n- 'Test Key' (am_test_2j1m...) — scopes: all — last used: 5 days ago",
        "webhooks_summary": '- wh_3k2j1m: https://acmecorp.com/webhook — Events: delivered, bounced — Status: failing (12 consecutive failures, HTTP 404)',
        "template_count": '3',
        "templates_summary": "- 'Welcome Email' (tmpl_welc01)\n- 'Order Confirmation' (tmpl_ordr01)\n- 'old-newsletter-v1' (tmpl_news01)",
        "contact_count": '4,230',
        "recent_events": '- 18,240 sent, 17,890 delivered (98.1%), 52 bounced (0.3%), 3 complaints (0.02%)',
        "open_issues": 'None',
    },

    # ── starter_nonprofit ───────────────────────────────────────────
    "starter_nonprofit": {
        "account_id": 'acct_np8g1d',
        "plan_name": 'Starter',
        "plan_price": '25',
        "emails_sent": '15,600',
        "email_limit": '50,000',
        "api_calls": '72,000',
        "api_call_limit": '500,000',
        "team_count": '3',
        "team_limit": '5',
        "created_at": '2025-03-20',
        "billing_cycle_date": 'Renews on the 20th of each month',
        "domain_count": '1',
        "domain_details": '- cleanocean.org: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)',
        "team_members": '- director@cleanocean.org (Admin, owner)\n- volunteer1@cleanocean.org (Editor)\n- volunteer2@cleanocean.org (Editor)',
        "api_keys": "- 'Newsletter Key' (am_live_np8g...) — scopes: send, contacts — last used: yesterday",
        "webhooks_summary": '- wh_co01: https://crm.cleanocean.org/hooks — Events: bounced, unsubscribed, complained — Status: active',
        "template_count": '5',
        "templates_summary": "- 'Donation Thank You' (tmpl_dt01)\n- 'Monthly Newsletter' (tmpl_mn01)\n- 'Event Invitation' (tmpl_ei01)\n- 'Volunteer Welcome' (tmpl_vw01)\n- 'Annual Report' (tmpl_ar01)",
        "contact_count": '12,500',
        "recent_events": '- 15,600 sent, 14,800 delivered (94.9%), 340 bounced (2.2%), 45 complaints (0.29%)\n- Bounce rate crossed 2% threshold 4 days ago after annual donor list blast',
        "open_issues": '- Bounce rate 2.2% (threshold: 2%) — stale donor email list\n- Complaint rate 0.29% (threshold: 0.3%) — approaching danger zone',
    },

    # ── starter_over_limit ──────────────────────────────────────────
    "starter_over_limit": {
        "account_id": 'acct_ol5n2p',
        "plan_name": 'Starter',
        "plan_price": '25',
        "emails_sent": '27,800',
        "email_limit": '50,000',
        "api_calls": '198,000',
        "api_call_limit": '500,000',
        "team_count": '3',
        "team_limit": '5',
        "created_at": '2025-04-01',
        "billing_cycle_date": 'Renews on the 1st of each month',
        "domain_count": '2',
        "domain_details": '- fitnesshub.io: Verified (SPF: pass, DKIM: pass, DMARC: pass)\n- mail.fitnesshub.io: Verified (SPF: pass, DKIM: pass, DMARC: pass)',
        "team_members": '- coach@fitnesshub.io (Admin, owner)\n- sarah@fitnesshub.io (Editor)\n- mike@fitnesshub.io (Viewer)',
        "api_keys": "- 'App Backend' (am_live_ol5n...) — scopes: send, read, contacts — last used: today",
        "webhooks_summary": '- wh_fh01: https://api.fitnesshub.io/hooks — Events: delivered, bounced — Status: active',
        "template_count": '6',
        "templates_summary": "- 'Workout Reminder' (tmpl_wr01)\n- 'Class Booking' (tmpl_cb01)\n- 'Progress Report' (tmpl_pr01)\n- (3 more)",
        "contact_count": '8,900',
        "recent_events": '- 27,800 sent, 27,200 delivered (97.8%), 112 bounced (0.4%), 8 complaints (0.03%)',
        "open_issues": '- Within email limit: 27,800/50,000 (55.6% used)',
    },

    # ── starter_restaurant ──────────────────────────────────────────
    "starter_restaurant": {
        "account_id": 'acct_rs2m4n',
        "plan_name": 'Starter',
        "plan_price": '25',
        "emails_sent": '8,400',
        "email_limit": '50,000',
        "api_calls": '42,000',
        "api_call_limit": '500,000',
        "team_count": '2',
        "team_limit": '5',
        "created_at": '2025-08-15',
        "billing_cycle_date": 'Renews on the 15th of each month',
        "domain_count": '1',
        "domain_details": '- sushimaster.jp: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)',
        "team_members": '- chef@sushimaster.jp (Admin, owner)\n- manager@sushimaster.jp (Editor)',
        "api_keys": "- 'Reservation System' (am_live_rs2m...) — scopes: send — last used: 1 hour ago",
        "webhooks_summary": '- wh_sm01: https://sushimaster.jp/hooks/email — Events: delivered, bounced — Status: active',
        "template_count": '3',
        "templates_summary": "- 'Reservation Confirmation' (tmpl_rc01)\n- 'Weekly Specials' (tmpl_ws01)\n- 'Loyalty Points' (tmpl_lp01)",
        "contact_count": '4,200',
        "recent_events": '- 8,400 sent, 8,200 delivered (97.6%), 42 bounced (0.5%), 2 complaints (0.02%)',
        "open_issues": 'None',
    },

    # ── starter_webhook_dead ────────────────────────────────────────
    "starter_webhook_dead": {
        "account_id": 'acct_wh7d3k',
        "plan_name": 'Starter',
        "plan_price": '25',
        "emails_sent": '12,400',
        "email_limit": '50,000',
        "api_calls": '89,000',
        "api_call_limit": '500,000',
        "team_count": '2',
        "team_limit": '5',
        "created_at": '2025-08-22',
        "billing_cycle_date": 'Renews on the 22nd of each month',
        "domain_count": '2',
        "domain_details": '- bakerydelight.com: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)\n- orders.bakerydelight.com: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)',
        "team_members": '- claire@bakerydelight.com (Admin, owner)\n- paul@bakerydelight.com (Viewer)',
        "api_keys": "- 'Order System' (am_live_wh7d...) — scopes: send, read — last used: 1 hour ago",
        "webhooks_summary": '- wh_bd01: https://api.bakerydelight.com/email-events — Events: delivered, bounced, opened — Status: auto-disabled (8 consecutive failures, last error: HTTP 500)',
        "template_count": '4',
        "templates_summary": "- 'Order Placed' (tmpl_op01)\n- 'Order Ready' (tmpl_or01)\n- 'Loyalty Reward' (tmpl_lr01)\n- 'Weekly Specials' (tmpl_ws01)",
        "contact_count": '2,100',
        "recent_events": '- 12,400 sent, 12,150 delivered (98.0%), 38 bounced (0.3%), 1 complaint (0.01%)',
        "open_issues": '- Webhook wh_bd01 auto-disabled after 8 consecutive failures (HTTP 500) over 24 hours',
    },

    # ======================================================================
    # Pro Plan Profiles
    # ======================================================================

    # ── pro_agency_multi_domain ─────────────────────────────────────
    "pro_agency_multi_domain": {
        "account_id": 'acct_ag5d8k',
        "plan_name": 'Pro',
        "plan_price": '65',
        "emails_sent": '38,000',
        "email_limit": '150,000',
        "api_calls": '290,000',
        "api_call_limit": '2,000,000',
        "team_count": '4',
        "team_limit": '10',
        "created_at": '2025-04-20',
        "billing_cycle_date": 'Renews on the 20th of each month',
        "domain_count": '4',
        "domain_details": '- mail.clientA.com: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)\n- mail.clientB.io: Verified (SPF: pass, DKIM: pass, DMARC: pass)\n- news.clientC.co: DKIM FAILING (SPF: pass, DKIM: fail — CNAME not configured, DMARC: fail)\n- agencyname.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)',
        "team_members": '- owner@agencyname.com (Admin, owner)\n- dev@agencyname.com (Editor)\n- clientA@agencyname.com (Editor)\n- clientC@agencyname.com (Viewer)',
        "api_keys": "- 'Production' (am_live_ag5d...) — scopes: all — last used: 5 min ago\n- 'Client C Integration' (am_live_c3in...) — scopes: send — last used: 1 day ago",
        "webhooks_summary": '- wh_ag01: https://agencyname.com/webhooks — Events: all — Status: active',
        "template_count": '12',
        "templates_summary": "- 'Client A Newsletter' (tmpl_ca01)\n- 'Client B Digest' (tmpl_cb01)\n- 'Client C News' (tmpl_cc01)\n- (9 more templates)",
        "contact_count": '31,000',
        "recent_events": '- 38,000 sent, 36,400 delivered (95.8%), 1,200 bounced (3.2%), 18 complaints (0.05%)\n- news.clientC.co: 3,000 sent, 2,100 delivered (70%), 600 bounced (20%)\n- DKIM failure on news.clientC.co since Jan 15 — CNAME record not configured in DNS',
        "open_issues": '- DKIM failing on news.clientC.co — CNAME record missing in DNS\n- High bounce rate on clientC.co domain (20%)',
    },

    # ── pro_dmarc_none ──────────────────────────────────────────────
    "pro_dmarc_none": {
        "account_id": 'acct_dn7p3q',
        "plan_name": 'Pro',
        "plan_price": '65',
        "emails_sent": '31,000',
        "email_limit": '150,000',
        "api_calls": '210,000',
        "api_call_limit": '2,000,000',
        "team_count": '3',
        "team_limit": '10',
        "created_at": '2025-06-10',
        "billing_cycle_date": 'Renews on the 10th of each month',
        "domain_count": '2',
        "domain_details": '- newsletter.consultpro.com: Verified (SPF: pass, DKIM: pass, DMARC: p=none)\n- consultpro.com: Verified (SPF: pass, DKIM: pass, DMARC: p=none)',
        "team_members": '- admin@consultpro.com (Admin, owner)\n- marketing@consultpro.com (Editor)\n- assistant@consultpro.com (Viewer)',
        "api_keys": "- 'Main API' (am_live_dn7p...) — scopes: send, read — last used: 20 min ago",
        "webhooks_summary": '- wh_cp01: https://consultpro.com/webhooks — Events: delivered, bounced — Status: active',
        "template_count": '5',
        "templates_summary": "- 'Monthly Insights' (tmpl_mi01)\n- 'Client Report' (tmpl_cr01)\n- (3 more templates)",
        "contact_count": '12,800',
        "recent_events": '- 31,000 sent, 29,800 delivered (96.1%), 310 bounced (1.0%), 22 complaints (0.07%)\n- Some phishing attempts detected mimicking consultpro.com',
        "open_issues": '- DMARC policy set to p=none — no enforcement against spoofing\n- Recommend upgrading to p=quarantine or p=reject',
    },

    # ── pro_edtech ──────────────────────────────────────────────────
    "pro_edtech": {
        "account_id": 'acct_ed8k5n',
        "plan_name": 'Pro',
        "plan_price": '65',
        "emails_sent": '28,900',
        "email_limit": '150,000',
        "api_calls": '195,000',
        "api_call_limit": '2,000,000',
        "team_count": '4',
        "team_limit": '10',
        "created_at": '2025-05-15',
        "billing_cycle_date": 'Renews on the 15th of each month',
        "domain_count": '2',
        "domain_details": '- learnfast.edu: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- notifications.learnfast.edu: Verified (SPF: pass, DKIM: pass, DMARC: reject)',
        "team_members": '- admin@learnfast.edu (Admin, owner)\n- curriculum@learnfast.edu (Editor)\n- support@learnfast.edu (Viewer)\n- it@learnfast.edu (Admin)',
        "api_keys": "- 'LMS Integration' (am_live_ed8k...) — scopes: send, contacts — last used: 3 min ago\n- 'Analytics' (am_live_an2m...) — scopes: read — last used: 1 hour ago",
        "webhooks_summary": '- wh_lf01: https://api.learnfast.edu/notifications — Events: delivered, bounced — Status: active',
        "template_count": '7',
        "templates_summary": "- 'Course Enrollment' (tmpl_ce01)\n- 'Assignment Due' (tmpl_ad01)\n- 'Grade Posted' (tmpl_gp01)\n- (4 more templates)",
        "contact_count": '15,600',
        "recent_events": '- 28,900 sent, 28,400 delivered (98.3%), 145 bounced (0.5%), 4 complaints (0.01%)',
        "open_issues": 'None',
    },

    # ── pro_new_user ────────────────────────────────────────────────
    "pro_new_user": {
        "account_id": 'acct_6j2t9m',
        "plan_name": 'Pro',
        "plan_price": '65',
        "emails_sent": '320',
        "email_limit": '150,000',
        "api_calls": '1,200',
        "api_call_limit": '2,000,000',
        "team_count": '3',
        "team_limit": '10',
        "created_at": '2026-02-10',
        "billing_cycle_date": 'Renews on the 10th of each month',
        "domain_count": '2',
        "domain_details": '- newsletter.startupxyz.com: Pending verification (SPF: not checked, DKIM: not checked, DMARC: not checked)\n- startupxyz.com: Verified (SPF: pass, DKIM: pass, DMARC: none)',
        "team_members": '- founder@startupxyz.com (Admin, owner)\n- dev@startupxyz.com (Editor)\n- designer@startupxyz.com (Viewer)',
        "api_keys": "- 'Main Key' (am_live_6j2t...) — scopes: send, read — last used: yesterday",
        "webhooks_summary": '- No webhooks configured',
        "template_count": '0',
        "templates_summary": '- No templates created yet',
        "contact_count": '85',
        "recent_events": '- 320 sent (all from startupxyz.com), 315 delivered (98.4%), 2 bounced (0.6%), 0 complaints',
        "open_issues": '- newsletter.startupxyz.com pending domain verification',
    },

    # ── pro_outlook_rendering ───────────────────────────────────────
    "pro_outlook_rendering": {
        "account_id": 'acct_or6m3w',
        "plan_name": 'Pro',
        "plan_price": '65',
        "emails_sent": '22,000',
        "email_limit": '150,000',
        "api_calls": '180,000',
        "api_call_limit": '2,000,000',
        "team_count": '3',
        "team_limit": '10',
        "created_at": '2025-08-01',
        "billing_cycle_date": 'Renews on the 1st of each month',
        "domain_count": '2',
        "domain_details": '- mail.modernoffice.co: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)\n- modernoffice.co: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)',
        "team_members": '- design@modernoffice.co (Admin, owner)\n- dev@modernoffice.co (Editor)\n- marketing@modernoffice.co (Editor)',
        "api_keys": "- 'Backend' (am_live_or6m...) — scopes: send, templates — last used: today",
        "webhooks_summary": '- wh_mo01: https://api.modernoffice.co/hooks — Events: delivered, opened, clicked — Status: active',
        "template_count": '6',
        "templates_summary": "- 'Product Launch' (tmpl_pl01) — ⚠️ Outlook rendering issues\n- 'Monthly Newsletter' (tmpl_mn01)\n- 'Feature Update' (tmpl_fu01)\n- (3 more)",
        "contact_count": '12,000',
        "recent_events": '- 22,000 sent, 21,600 delivered (98.2%), 66 bounced (0.3%), 4 complaints (0.02%)\n- Support tickets from Outlook users: emails look broken (CSS grid not rendering)',
        "open_issues": "- Template 'Product Launch' renders incorrectly in Outlook 2019/2021 — CSS grid and flexbox not supported\n- 30% of recipients use Outlook (B2B audience)",
    },

    # ── pro_realtor ─────────────────────────────────────────────────
    "pro_realtor": {
        "account_id": 'acct_re3h7m',
        "plan_name": 'Pro',
        "plan_price": '65',
        "emails_sent": '18,500',
        "email_limit": '150,000',
        "api_calls": '120,000',
        "api_call_limit": '2,000,000',
        "team_count": '2',
        "team_limit": '10',
        "created_at": '2025-09-01',
        "billing_cycle_date": 'Renews on the 1st of each month',
        "domain_count": '2',
        "domain_details": '- premiumhomes.com: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)\n- track.premiumhomes.com: Verified (custom tracking domain, SSL active)',
        "team_members": '- agent@premiumhomes.com (Admin, owner)\n- assistant@premiumhomes.com (Editor)',
        "api_keys": "- 'CRM Sync' (am_live_re3h...) — scopes: send, contacts, read — last used: 15 min ago",
        "webhooks_summary": '- wh_ph01: https://premiumhomes.com/hooks — Events: delivered, opened, clicked — Status: active',
        "template_count": '5',
        "templates_summary": "- 'New Listing Alert' (tmpl_nl01)\n- 'Open House Invite' (tmpl_oh01)\n- 'Market Report' (tmpl_mr01)\n- (2 more templates)",
        "contact_count": '8,900',
        "recent_events": '- 18,500 sent, 18,100 delivered (97.8%), 92 bounced (0.5%), 6 complaints (0.03%)\n- Click tracking active via track.premiumhomes.com',
        "open_issues": 'None',
    },

    # ── pro_template_issue ──────────────────────────────────────────
    "pro_template_issue": {
        "account_id": 'acct_ti4w2k',
        "plan_name": 'Pro',
        "plan_price": '65',
        "emails_sent": '44,500',
        "email_limit": '150,000',
        "api_calls": '340,000',
        "api_call_limit": '2,000,000',
        "team_count": '3',
        "team_limit": '10',
        "created_at": '2025-03-01',
        "billing_cycle_date": 'Renews on the 1st of each month',
        "domain_count": '1',
        "domain_details": '- winerymail.com: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)',
        "team_members": '- owner@winerymail.com (Admin, owner)\n- marketing@winerymail.com (Editor)\n- design@winerymail.com (Viewer)',
        "api_keys": "- 'Sending Key' (am_live_ti4w...) — scopes: send, campaigns — last used: 6 hours ago",
        "webhooks_summary": '- wh_wm01: https://winerymail.com/hooks — Events: bounced, complained — Status: active',
        "template_count": '6',
        "templates_summary": "- 'Summer Wine Sale' (tmpl_sws01) — last sent 2 days ago, 8,000 recipients\n- 'Monthly Tasting' (tmpl_mt01)\n- 'New Arrivals' (tmpl_na01)\n- (3 more templates)",
        "contact_count": '22,000',
        "recent_events": "- 44,500 sent, 42,800 delivered (96.2%), 890 bounced (2.0%), 240 complaints (0.54%)\n- 'Summer Wine Sale' campaign: 8,000 sent, 7,600 delivered, 180 complaints (2.4%)\n- Complaint spike from 'Summer Wine Sale' — many recipients didn't sign up",
        "open_issues": "- Overall complaint rate 0.54% (threshold: 0.3%)\n- 'Summer Wine Sale' complaint rate 2.4% — suggests recipients were not opted in\n- Account under review for complaint rate violation",
    },

    # ======================================================================
    # Growth Plan Profiles
    # ======================================================================

    # ── growth_cloudflare_dkim ──────────────────────────────────────
    "growth_cloudflare_dkim": {
        "account_id": 'acct_cf4d2m',
        "plan_name": 'Growth',
        "plan_price": '150',
        "emails_sent": '38,000',
        "email_limit": '500,000',
        "api_calls": '290,000',
        "api_call_limit": '5,000,000',
        "team_count": '4',
        "team_limit": '25',
        "created_at": '2025-06-15',
        "billing_cycle_date": 'Renews on the 15th of each month',
        "domain_count": '2',
        "domain_details": '- webbuilder.tools: Verified (SPF: pass, DKIM: fail — CNAME flattened by Cloudflare proxy, DMARC: fail)\n- app.webbuilder.tools: Verified (SPF: pass, DKIM: pass, DMARC: pass)',
        "team_members": '- admin@webbuilder.tools (Admin, owner)\n- dev@webbuilder.tools (Editor)\n- designer@webbuilder.tools (Editor)\n- support@webbuilder.tools (Viewer)',
        "api_keys": "- 'Backend' (am_live_cf4d...) — scopes: send, read — last used: 10 min ago",
        "webhooks_summary": '- wh_wb01: https://api.webbuilder.tools/email — Events: all — Status: active',
        "template_count": '5',
        "templates_summary": "- 'Site Published' (tmpl_sp01)\n- 'Trial Ending' (tmpl_te01)\n- (3 more)",
        "contact_count": '15,000',
        "recent_events": '- 38,000 sent, 34,200 delivered (90.0%), 1,900 bounced (5.0%), 19 complaints (0.05%)\n- webbuilder.tools DKIM failing since Cloudflare proxy was enabled 5 days ago',
        "open_issues": '- DKIM failure on webbuilder.tools — Cloudflare proxy (orange cloud) is flattening the CNAME record\n- Must set DKIM CNAME to DNS-only (grey cloud) in Cloudflare',
    },

    # ── growth_complaint_suspended ──────────────────────────────────
    "growth_complaint_suspended": {
        "account_id": 'acct_cs3r7b',
        "plan_name": 'Growth',
        "plan_price": '150',
        "emails_sent": '45,000',
        "email_limit": '500,000',
        "api_calls": '350,000',
        "api_call_limit": '5,000,000',
        "team_count": '4',
        "team_limit": '25',
        "created_at": '2025-01-10',
        "billing_cycle_date": 'Renews on the 10th of each month',
        "domain_count": '2',
        "domain_details": '- dailydeals.shop: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)\n- promo.dailydeals.shop: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)',
        "team_members": '- boss@dailydeals.shop (Admin, owner)\n- marketing@dailydeals.shop (Editor)\n- dev@dailydeals.shop (Editor)\n- cs@dailydeals.shop (Viewer)',
        "api_keys": "- 'Main Key' (am_live_cs3r...) — scopes: send, read — last used: 2 days ago (before suspension)",
        "webhooks_summary": '- wh_dd01: https://api.dailydeals.shop/hooks — Events: all — Status: active',
        "template_count": '5',
        "templates_summary": "- 'Flash Deal' (tmpl_fd01)\n- 'Coupon Code' (tmpl_cc01)\n- 'Clearance Alert' (tmpl_cla01)\n- (2 more)",
        "contact_count": '65,000',
        "recent_events": '- 45,000 sent, 41,800 delivered (92.9%), 900 bounced (2.0%), 450 complaints (1.0%)\n- Account sending SUSPENDED at 2026-02-16 03:22 UTC — complaint rate exceeded 0.3%\n- All subsequent API send calls returning 403 Forbidden',
        "open_issues": '- ⚠️ SENDING SUSPENDED — Complaint rate 1.0% (threshold: 0.3%)\n- 450 complaints from last 3 campaigns sent to unsubscribed users\n- Must contact support to appeal suspension',
    },

    # ── growth_crypto ───────────────────────────────────────────────
    "growth_crypto": {
        "account_id": 'acct_cr8n5d',
        "plan_name": 'Growth',
        "plan_price": '150',
        "emails_sent": '58,000',
        "email_limit": '500,000',
        "api_calls": '420,000',
        "api_call_limit": '5,000,000',
        "team_count": '5',
        "team_limit": '25',
        "created_at": '2025-02-01',
        "billing_cycle_date": 'Renews on the 1st of each month',
        "domain_count": '2',
        "domain_details": '- alerts.chainledger.io: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- chainledger.io: Verified (SPF: pass, DKIM: pass, DMARC: reject)',
        "team_members": '- cto@chainledger.io (Admin, owner)\n- security@chainledger.io (Admin)\n- dev@chainledger.io (Editor)\n- ops@chainledger.io (Editor)\n- marketing@chainledger.io (Viewer)',
        "api_keys": "- 'Transaction Alerts' (am_live_cr8n...) — scopes: send — last used: 10 sec ago — IP-restricted: 10.0.0.0/24\n- 'Marketing' (am_live_mk4p...) — scopes: send, campaigns — last used: 4 hours ago — IP-restricted: 10.0.0.0/24",
        "webhooks_summary": '- wh_cl01: https://api.chainledger.io/hooks — Events: delivered, bounced — Status: active (HMAC-signed)',
        "template_count": '6',
        "templates_summary": "- 'Transaction Confirmation' (tmpl_tc01)\n- 'Security Alert' (tmpl_sa01)\n- 'Portfolio Update' (tmpl_pu01)\n- (3 more templates)",
        "contact_count": '42,000',
        "recent_events": '- 58,000 sent, 57,200 delivered (98.6%), 290 bounced (0.5%), 8 complaints (0.01%)',
        "open_issues": 'None',
    },

    # ── growth_dkim_fail ────────────────────────────────────────────
    "growth_dkim_fail": {
        "account_id": 'acct_9x7m4p',
        "plan_name": 'Growth',
        "plan_price": '150',
        "emails_sent": '67,500',
        "email_limit": '500,000',
        "api_calls": '523,000',
        "api_call_limit": '5,000,000',
        "team_count": '6',
        "team_limit": '25',
        "created_at": '2024-11-20',
        "billing_cycle_date": 'Renews on the 20th of each month',
        "domain_count": '3',
        "domain_details": '- notifications.techflow.io: Verified (SPF: pass, DKIM: pass, DMARC: pass)\n- marketing.techflow.io: DKIM FAILING (SPF: pass, DKIM: fail — record not found, DMARC: fail)\n- techflow.io: Verified (SPF: pass, DKIM: pass, DMARC: pass)',
        "team_members": '- cto@techflow.io (Admin, owner)\n- dev1@techflow.io (Editor)\n- dev2@techflow.io (Editor)\n- marketing@techflow.io (Editor)\n- support@techflow.io (Viewer)\n- intern@techflow.io (Viewer)',
        "api_keys": "- 'Backend API' (am_live_9x7m...) — scopes: send, read, contacts — last used: 1 min ago\n- 'Marketing Tool' (am_live_4p2q...) — scopes: send, campaigns — last used: 3 days ago",
        "webhooks_summary": '- wh_tf01: https://api.techflow.io/hooks/email — Events: all — Status: active\n- wh_tf02: https://marketing.techflow.io/events — Events: opened, clicked — Status: active',
        "template_count": '8',
        "templates_summary": "- 'Welcome Series - Day 1' (tmpl_ws01)\n- 'Welcome Series - Day 3' (tmpl_ws03)\n- 'Product Update' (tmpl_pu01)\n- 'February Newsletter' (tmpl_fn02)\n- (4 more templates)",
        "contact_count": '23,450',
        "recent_events": '- 67,500 sent, 62,100 delivered (92.0%), 3,200 bounced (4.7%), 89 complaints (0.13%)\n- marketing.techflow.io: 4,200 sent, 2,800 delivered (66.7%), 1,100 bounced (26.2%)\n- Bounce spike started 3 days ago after DNS change',
        "open_issues": '- High bounce rate on marketing.techflow.io (26.2%) — threshold: 2%',
    },

    # ── growth_gaming ───────────────────────────────────────────────
    "growth_gaming": {
        "account_id": 'acct_gm7k2p',
        "plan_name": 'Growth',
        "plan_price": '150',
        "emails_sent": '92,300',
        "email_limit": '500,000',
        "api_calls": '780,000',
        "api_call_limit": '5,000,000',
        "team_count": '6',
        "team_limit": '25',
        "created_at": '2025-03-10',
        "billing_cycle_date": 'Renews on the 10th of each month',
        "domain_count": '2',
        "domain_details": '- mail.pixelquest.gg: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)\n- pixelquest.gg: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)',
        "team_members": '- ceo@pixelquest.gg (Admin, owner)\n- dev@pixelquest.gg (Admin)\n- community@pixelquest.gg (Editor)\n- marketing@pixelquest.gg (Editor)\n- support@pixelquest.gg (Viewer)\n- art@pixelquest.gg (Viewer)',
        "api_keys": "- 'Game Server' (am_live_gm7k...) — scopes: send — last used: 30 sec ago\n- 'Marketing Platform' (am_live_mp4r...) — scopes: all — last used: 2 hours ago",
        "webhooks_summary": '- wh_pq01: https://api.pixelquest.gg/email-events — Events: all — Status: active',
        "template_count": '8',
        "templates_summary": "- 'Account Verification' (tmpl_av01)\n- 'Season Pass Purchased' (tmpl_sp01)\n- 'Tournament Invite' (tmpl_ti01)\n- (5 more templates)",
        "contact_count": '65,000',
        "recent_events": '- 92,300 sent, 90,400 delivered (97.9%), 920 bounced (1.0%), 28 complaints (0.03%)\n- Email usage: 18.5% of monthly limit (92,300/500,000)',
        "open_issues": '- Email usage at 18.5% of monthly limit (92,300/500,000) with 8 days left',
    },

    # ── growth_gmail_promo_tab ──────────────────────────────────────
    "growth_gmail_promo_tab": {
        "account_id": 'acct_gp5t8k',
        "plan_name": 'Growth',
        "plan_price": '150',
        "emails_sent": '62,000',
        "email_limit": '500,000',
        "api_calls": '540,000',
        "api_call_limit": '5,000,000',
        "team_count": '5',
        "team_limit": '25',
        "created_at": '2025-04-01',
        "billing_cycle_date": 'Renews on the 1st of each month',
        "domain_count": '3',
        "domain_details": '- mail.fashionbrand.style: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- promos.fashionbrand.style: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- track.fashionbrand.style: Custom tracking domain — Verified (SSL active)',
        "team_members": '- marketing@fashionbrand.style (Admin, owner)\n- (4 more)',
        "api_keys": "- 'Platform' (am_live_gp5t...) — scopes: all — last used: 2 hours ago",
        "webhooks_summary": '- wh_fb01: https://api.fashionbrand.style/email — Events: all — Status: active',
        "template_count": '14',
        "templates_summary": "- 'New Arrivals' (tmpl_na01)\n- 'Sale Alert' (tmpl_sa01)\n- 'Lookbook' (tmpl_lb01)\n- (11 more)",
        "contact_count": '65,000',
        "recent_events": '- 62,000 sent, 61,400 delivered (99.0%), 124 bounced (0.2%), 31 complaints (0.05%)\n- Open rate dropped from 35% to 12% over past 2 weeks\n- 85% of Gmail recipients seeing emails in Promotions tab (was Primary)',
        "open_issues": '- Gmail Promotions tab placement: open rate dropped 35% → 12%\n- Marketing campaigns being classified as promotional despite transactional content mix',
    },

    # ── growth_ip_warmup ────────────────────────────────────────────
    "growth_ip_warmup": {
        "account_id": 'acct_iw6p4q',
        "plan_name": 'Growth',
        "plan_price": '150',
        "emails_sent": '12,000',
        "email_limit": '500,000',
        "api_calls": '180,000',
        "api_call_limit": '5,000,000',
        "team_count": '5',
        "team_limit": '25',
        "created_at": '2026-01-15',
        "billing_cycle_date": 'Renews on the 15th of each month',
        "domain_count": '2',
        "domain_details": '- shoptrend.com: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)\n- promo.shoptrend.com: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)',
        "team_members": '- ops@shoptrend.com (Admin, owner)\n- dev@shoptrend.com (Editor)\n- mktg@shoptrend.com (Editor)\n- cs@shoptrend.com (Viewer)\n- intern@shoptrend.com (Viewer)',
        "api_keys": "- 'Ecommerce Backend' (am_live_iw6p...) — scopes: send, read, contacts — last used: 5 min ago",
        "webhooks_summary": '- wh_st01: https://api.shoptrend.com/email — Events: all — Status: active',
        "template_count": '7',
        "templates_summary": "- 'Order Confirmation' (tmpl_oc01)\n- 'Shipping Update' (tmpl_su01)\n- 'Cart Abandoned' (tmpl_ca01)\n- 'Flash Sale' (tmpl_fs01)\n- (3 more)",
        "contact_count": '35,000',
        "recent_events": '- 12,000 sent, 10,800 delivered (90.0%), 480 bounced (4.0%), 24 complaints (0.2%)\n- Dedicated IP 203.0.113.50 — warming phase, reputation score: 45/100\n- Gmail deliverability: 72% (emails landing in spam during warmup)',
        "open_issues": '- Dedicated IP warming: only 35% through warmup schedule\n- Gmail spam placement during reputation building\n- Bounce rate 4.0% — expected during warmup but needs monitoring',
    },

    # ── growth_logistics ────────────────────────────────────────────
    "growth_logistics": {
        "account_id": 'acct_lg4r8m',
        "plan_name": 'Growth',
        "plan_price": '150',
        "emails_sent": '72,000',
        "email_limit": '500,000',
        "api_calls": '650,000',
        "api_call_limit": '5,000,000',
        "team_count": '5',
        "team_limit": '25',
        "created_at": '2025-01-15',
        "billing_cycle_date": 'Renews on the 15th of each month',
        "domain_count": '2',
        "domain_details": '- tracking.swiftship.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- swiftship.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)',
        "team_members": '- ops@swiftship.com (Admin, owner)\n- tech@swiftship.com (Admin)\n- dispatch@swiftship.com (Editor)\n- cs@swiftship.com (Viewer)\n- warehouse@swiftship.com (Viewer)',
        "api_keys": "- 'Tracking System' (am_live_lg4r...) — scopes: send — last used: 5 sec ago\n- 'Notifications' (am_live_nt2k...) — scopes: send, read — last used: 1 min ago",
        "webhooks_summary": '- wh_ss01: https://api.swiftship.com/email-hooks — Events: delivered, bounced — Status: active',
        "template_count": '5',
        "templates_summary": "- 'Shipment Dispatched' (tmpl_sd01)\n- 'Delivery Confirmed' (tmpl_dc01)\n- 'Delay Notification' (tmpl_dn01)\n- (2 more templates)",
        "contact_count": '89,000',
        "recent_events": '- 72,000 sent, 71,500 delivered (99.3%), 216 bounced (0.3%), 4 complaints (0.006%)',
        "open_issues": 'None',
    },

    # ── growth_rate_limited ─────────────────────────────────────────
    "growth_rate_limited": {
        "account_id": 'acct_rl4k7n',
        "plan_name": 'Growth',
        "plan_price": '150',
        "emails_sent": '48,000',
        "email_limit": '500,000',
        "api_calls": '980,000',
        "api_call_limit": '5,000,000',
        "team_count": '7',
        "team_limit": '25',
        "created_at": '2025-02-20',
        "billing_cycle_date": 'Renews on the 20th of each month',
        "domain_count": '3',
        "domain_details": '- mail.devtools.run: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- alerts.devtools.run: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- devtools.run: Verified (SPF: pass, DKIM: pass, DMARC: reject)',
        "team_members": '- cto@devtools.run (Admin, owner)\n- (6 more)',
        "api_keys": "- 'Main Backend' (am_live_rl4k...) — scopes: all — last used: just now\n- 'Worker Service' (am_live_wk8m...) — scopes: send — last used: just now",
        "webhooks_summary": '- wh_dt01: https://api.devtools.run/email — Events: all — Status: active',
        "template_count": '10',
        "templates_summary": "- 'Build Notification' (tmpl_bn01)\n- 'Alert' (tmpl_al01)\n- (8 more)",
        "contact_count": '28,000',
        "recent_events": '- 48,000 sent, 47,500 delivered (99.0%), 96 bounced (0.2%), 5 complaints (0.01%)\n- ⚠️ 429 Rate Limit errors: 342 occurrences in last 24 hours\n- Rate limit: 1,000 req/min — burst traffic during product launch exceeded this',
        "open_issues": '- 342 rate-limit (429) errors in past 24 hours — exceeding 1,000 req/min limit\n- API call usage: 980K/5M (19.6%)',
    },

    # ── growth_travel ───────────────────────────────────────────────
    "growth_travel": {
        "account_id": 'acct_tr6m4k',
        "plan_name": 'Growth',
        "plan_price": '150',
        "emails_sent": '55,400',
        "email_limit": '500,000',
        "api_calls": '410,000',
        "api_call_limit": '5,000,000',
        "team_count": '5',
        "team_limit": '25',
        "created_at": '2025-04-20',
        "billing_cycle_date": 'Renews on the 20th of each month',
        "domain_count": '2',
        "domain_details": '- booking.wanderluxe.travel: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)\n- wanderluxe.travel: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)',
        "team_members": '- ceo@wanderluxe.travel (Admin, owner)\n- marketing@wanderluxe.travel (Editor)\n- support@wanderluxe.travel (Viewer)\n- ops@wanderluxe.travel (Editor)\n- content@wanderluxe.travel (Viewer)',
        "api_keys": "- 'Booking System' (am_live_tr6m...) — scopes: send — last used: 20 min ago\n- 'Marketing' (am_live_mk8p...) — scopes: all — last used: 3 hours ago",
        "webhooks_summary": '- wh_wl01: https://api.wanderluxe.travel/webhooks — Events: all — Status: active',
        "template_count": '8',
        "templates_summary": "- 'Booking Confirmation' (tmpl_bc01)\n- 'Itinerary Update' (tmpl_iu01)\n- 'Travel Deals' (tmpl_td01)\n- (5 more templates)",
        "contact_count": '45,000',
        "recent_events": '- 55,400 sent, 54,300 delivered (98.0%), 550 bounced (1.0%), 16 complaints (0.03%)',
        "open_issues": 'None',
    },

    # ======================================================================
    # Scale Plan Profiles
    # ======================================================================

    # ── scale_deliverability ────────────────────────────────────────
    "scale_deliverability": {
        "account_id": 'acct_4k8r1w',
        "plan_name": 'Scale',
        "plan_price": '350',
        "emails_sent": '425,000',
        "email_limit": '2,000,000',
        "api_calls": '3,200,000',
        "api_call_limit": '20,000,000',
        "team_count": '18',
        "team_limit": '50',
        "created_at": '2024-03-10',
        "billing_cycle_date": 'Renews on the 10th of each month',
        "domain_count": '8',
        "domain_details": '- mail.bigretail.com: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)\n- promo.bigretail.com: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)\n- alerts.bigretail.com: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)\n- (5 more domains, all verified)',
        "team_members": '- ceo@bigretail.com (Admin, owner)\n- cto@bigretail.com (Admin)\n- (16 more team members: 8 Editors, 8 Viewers)',
        "api_keys": "- 'Production Sending' (am_live_4k8r...) — scopes: all — last used: 1 min ago\n- 'Analytics Read' (am_live_7m2n...) — scopes: read — last used: 10 min ago\n- 'Staging' (am_test_9p3q...) — scopes: all — last used: 2 days ago",
        "webhooks_summary": '- wh_br01: https://api.bigretail.com/webhooks/email — Events: all — Status: active\n- wh_br02: https://analytics.bigretail.com/ingest — Events: delivered, bounced, opened, clicked — Status: active',
        "template_count": '24',
        "templates_summary": "- 'Order Confirmation' (tmpl_oc01)\n- 'Shipping Notification' (tmpl_ship01)\n- 'Black Friday 2025' (tmpl_bf25)\n- 'Weekly Promo' (tmpl_wp01)\n- (20 more templates)",
        "contact_count": '189,000',
        "recent_events": '- 425,000 sent, 391,000 delivered (92.0%), 12,750 bounced (3.0%), 850 complaints (0.2%)\n- Gmail deliverability dropped from 96% to 78% over past 2 weeks\n- IP 198.51.100.12 listed on Spamhaus SBL since Feb 14',
        "open_issues": '- Bounce rate 3.0% (threshold: 2%)\n- Complaint rate 0.2% (threshold: 0.1%)\n- IP 198.51.100.12 blocklisted on Spamhaus',
    },

    # ── scale_greylist ──────────────────────────────────────────────
    "scale_greylist": {
        "account_id": 'acct_gl8k5n',
        "plan_name": 'Scale',
        "plan_price": '350',
        "emails_sent": '350,000',
        "email_limit": '2,000,000',
        "api_calls": '3,100,000',
        "api_call_limit": '20,000,000',
        "team_count": '16',
        "team_limit": '50',
        "created_at": '2024-07-01',
        "billing_cycle_date": 'Renews on the 1st of each month',
        "domain_count": '5',
        "domain_details": '- mail.govcontract.us: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- bids.govcontract.us: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- (3 more verified domains)',
        "team_members": '- admin@govcontract.us (Admin, owner)\n- (15 more)',
        "api_keys": "- 'Bid Notifications' (am_live_gl8k...) — scopes: send, read — last used: just now\n- 'Reports' (am_live_rp2m...) — scopes: send, read — last used: 1 hour ago",
        "webhooks_summary": '- wh_gc01: https://api.govcontract.us/email — Events: all — Status: active',
        "template_count": '8',
        "templates_summary": "- 'Bid Alert' (tmpl_ba01)\n- 'Award Notification' (tmpl_an01)\n- 'Document Submission' (tmpl_ds01)\n- (5 more)",
        "contact_count": '78,000',
        "recent_events": "- 350,000 sent, 340,000 delivered (97.1%), 3,500 bounced (1.0%), 35 complaints (0.01%)\n- 12,000 emails in 'deferred' state — target domains (*.gov, *.mil) applying greylisting\n- Many government recipients experiencing 15-30 min delivery delays",
        "open_issues": '- 12,000 deferred emails to government domains (.gov, .mil) — greylisting delays\n- Some .gov recipients reporting non-receipt (emails in deferred queue)',
    },

    # ── scale_healthcare ────────────────────────────────────────────
    "scale_healthcare": {
        "account_id": 'acct_hc2m7k',
        "plan_name": 'Scale',
        "plan_price": '350',
        "emails_sent": '310,000',
        "email_limit": '2,000,000',
        "api_calls": '2,900,000',
        "api_call_limit": '20,000,000',
        "team_count": '15',
        "team_limit": '50',
        "created_at": '2024-06-01',
        "billing_cycle_date": 'Renews on the 1st of each month',
        "domain_count": '4',
        "domain_details": '- appointments.medconnect.health: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- results.medconnect.health: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- billing.medconnect.health: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- medconnect.health: Verified (SPF: pass, DKIM: pass, DMARC: reject)',
        "team_members": '- cto@medconnect.health (Admin, owner)\n- compliance@medconnect.health (Admin)\n- (13 more)',
        "api_keys": "- 'Appointment System' (am_live_hc2m...) — scopes: send, read — last used: just now\n- 'Patient Portal' (am_live_pp4k...) — scopes: send — last used: 5 min ago",
        "webhooks_summary": '- wh_mc01: https://api.medconnect.health/email — Events: delivered, bounced — Status: active',
        "template_count": '12',
        "templates_summary": "- 'Appointment Reminder' (tmpl_ar01)\n- 'Lab Results Ready' (tmpl_lrr01)\n- 'Prescription Update' (tmpl_pu01)\n- (9 more)",
        "contact_count": '250,000',
        "recent_events": '- 310,000 sent, 307,900 delivered (99.3%), 620 bounced (0.2%), 6 complaints (0.002%)',
        "open_issues": '- Requesting HIPAA BAA — need Enterprise plan for HIPAA compliance\n- Cannot use HIPAA features on Scale plan',
    },

    # ── scale_insurance ─────────────────────────────────────────────
    "scale_insurance": {
        "account_id": 'acct_in6k2r',
        "plan_name": 'Scale',
        "plan_price": '350',
        "emails_sent": '285,000',
        "email_limit": '2,000,000',
        "api_calls": '2,400,000',
        "api_call_limit": '20,000,000',
        "team_count": '12',
        "team_limit": '50',
        "created_at": '2024-03-15',
        "billing_cycle_date": 'Renews on the 15th of each month',
        "domain_count": '3',
        "domain_details": '- mail.shieldinsure.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- claims.shieldinsure.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- compliance.shieldinsure.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)',
        "team_members": '- ciso@shieldinsure.com (Admin, owner)\n- compliance@shieldinsure.com (Admin)\n- (10 more members)',
        "api_keys": "- 'Claims Processing' (am_live_in6k...) — scopes: send, contacts — last used: 2 min ago\n- 'Compliance Audit' (am_live_ca3r...) — scopes: read — last used: 30 min ago",
        "webhooks_summary": '- wh_si01: https://api.shieldinsure.com/email-hooks — Events: all — Status: active\n- wh_si02: https://compliance.shieldinsure.com/audit — Events: bounced, complained — Status: active',
        "template_count": '10',
        "templates_summary": "- 'Policy Renewal' (tmpl_pr01)\n- 'Claim Status Update' (tmpl_cs01)\n- 'Regulatory Notice' (tmpl_rn01)\n- (7 more templates)",
        "contact_count": '180,000',
        "recent_events": '- 285,000 sent, 280,200 delivered (98.3%), 2,850 bounced (1.0%), 142 complained (0.05%)\n- Compliance webhook to compliance.shieldinsure.com active and logging all events',
        "open_issues": '- Annual compliance audit due in 15 days — need complete email delivery report\n- 2,850 bounced + 142 complained emails need review for compliance reporting',
    },

    # ── scale_key_rotation ──────────────────────────────────────────
    "scale_key_rotation": {
        "account_id": 'acct_kr5n8t',
        "plan_name": 'Scale',
        "plan_price": '350',
        "emails_sent": '345,000',
        "email_limit": '2,000,000',
        "api_calls": '3,800,000',
        "api_call_limit": '20,000,000',
        "team_count": '20',
        "team_limit": '50',
        "created_at": '2024-08-01',
        "billing_cycle_date": 'Renews on the 1st of each month',
        "domain_count": '7',
        "domain_details": '- mail.cybershield.tech: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- alerts.cybershield.tech: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- (5 more verified domains)',
        "team_members": '- ciso@cybershield.tech (Admin, owner)\n- (19 more)',
        "api_keys": "- 'Production Send' (am_live_kr5n...) — scopes: send — last used: just now, needs rotation\n- 'Production Read' (am_live_rd2k...) — scopes: read — last used: 2 min ago, needs rotation\n- 'Integration' (am_live_ig8m...) — scopes: send, read, contacts — last used: 5 min ago, needs rotation\n- 'Staging' (am_test_st4q...) — scopes: all — last used: 1 day ago",
        "webhooks_summary": '- wh_cs01: https://api.cybershield.tech/email — Events: all — Status: active — Secret needs rotation\n- wh_cs02: https://siem.cybershield.tech/ingest — Events: all — Status: active',
        "template_count": '9',
        "templates_summary": "- 'Threat Alert' (tmpl_ta01)\n- 'Incident Report' (tmpl_ir01)\n- (7 more)",
        "contact_count": '160,000',
        "recent_events": '- 345,000 sent, 341,550 delivered (99.0%), 690 bounced (0.2%), 34 complaints (0.01%)',
        "open_issues": '- Security audit requires API key rotation — need to rotate all 4 production keys without downtime\n- Webhook signing secret also needs rotation as part of quarterly security review',
    },

    # ── scale_media ─────────────────────────────────────────────────
    "scale_media": {
        "account_id": 'acct_md9k3p',
        "plan_name": 'Scale',
        "plan_price": '350',
        "emails_sent": '470,000',
        "email_limit": '2,000,000',
        "api_calls": '4,200,000',
        "api_call_limit": '20,000,000',
        "team_count": '18',
        "team_limit": '50',
        "created_at": '2024-02-01',
        "billing_cycle_date": 'Renews on the 1st of each month',
        "domain_count": '5',
        "domain_details": '- mail.dailypulse.news: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)\n- breaking.dailypulse.news: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)\n- alerts.dailypulse.news: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)\n- (2 more verified domains)',
        "team_members": '- editor@dailypulse.news (Admin, owner)\n- cto@dailypulse.news (Admin)\n- (16 more members: 10 Editors, 6 Viewers)',
        "api_keys": "- 'Breaking News System' (am_live_md9k...) — scopes: send — last used: just now\n- 'Newsletter Platform' (am_live_nl5r...) — scopes: all — last used: 10 min ago\n- 'Analytics' (am_live_an8m...) — scopes: read — last used: 1 hour ago",
        "webhooks_summary": '- wh_dp01: https://api.dailypulse.news/email-events — Events: all — Status: active\n- wh_dp02: https://analytics.dailypulse.news/ingest — Events: opened, clicked — Status: active',
        "template_count": '15',
        "templates_summary": "- 'Breaking Alert' (tmpl_ba01)\n- 'Morning Digest' (tmpl_md01)\n- 'Weekend Roundup' (tmpl_wr01)\n- (12 more templates)",
        "contact_count": '320,000',
        "recent_events": '- 470,000 sent, 441,800 delivered (94.0%), 9,400 bounced (2.0%), 376 complaints (0.08%)\n- Email usage: 23.5% of monthly limit (470,000/2,000,000)',
        "open_issues": '- Email usage at 23.5% (470,000/2,000,000) with 8 days remaining',
    },

    # ── scale_sso_issue ─────────────────────────────────────────────
    "scale_sso_issue": {
        "account_id": 'acct_ss7o3d',
        "plan_name": 'Scale',
        "plan_price": '350',
        "emails_sent": '290,000',
        "email_limit": '2,000,000',
        "api_calls": '2,800,000',
        "api_call_limit": '20,000,000',
        "team_count": '20',
        "team_limit": '50',
        "created_at": '2024-05-01',
        "billing_cycle_date": 'Renews on the 1st of each month',
        "domain_count": '5',
        "domain_details": '- mail.legalpartners.law: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- docs.legalpartners.law: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- (3 more verified domains)',
        "team_members": '- it@legalpartners.law (Admin, owner)\n- managing-partner@legalpartners.law (Admin)\n- (18 more: 10 Editors, 8 Viewers — 5 currently locked out due to SSO issue)',
        "api_keys": "- 'Document Delivery' (am_live_ss7o...) — scopes: send, read — last used: just now\n- 'Case Updates' (am_live_cu2k...) — scopes: send — last used: 10 min ago",
        "webhooks_summary": '- wh_lp01: https://api.legalpartners.law/email — Events: delivered, bounced, opened — Status: active',
        "template_count": '8',
        "templates_summary": "- 'Document Sent' (tmpl_ds01)\n- 'Case Update' (tmpl_cu01)\n- 'Meeting Scheduled' (tmpl_ms01)\n- (5 more)",
        "contact_count": '45,000',
        "recent_events": '- 290,000 sent, 287,100 delivered (99.0%), 580 bounced (0.2%), 29 complaints (0.01%)',
        "open_issues": "- SAML SSO integration returning 'Invalid SAML Response' — metadata certificate expired yesterday\n- 5 team members unable to log in via SSO since this morning",
    },

    # ── scale_subaccounts ───────────────────────────────────────────
    "scale_subaccounts": {
        "account_id": 'acct_sa3b9k',
        "plan_name": 'Scale',
        "plan_price": '350',
        "emails_sent": '420,000',
        "email_limit": '2,000,000',
        "api_calls": '3,900,000',
        "api_call_limit": '20,000,000',
        "team_count": '25',
        "team_limit": '50',
        "created_at": '2024-04-15',
        "billing_cycle_date": 'Renews on the 15th of each month',
        "domain_count": '15',
        "domain_details": "- mail.digitalforge.agency: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- Subaccount 'ClientAlpha': alpha.digitalforge.agency (Verified)\n- Subaccount 'ClientBeta': beta-corp.com (Verified)\n- Subaccount 'ClientGamma': gamma.shop (Verified), returns.gamma.shop (Verified)\n- (10 more subaccount domains)",
        "team_members": '- ceo@digitalforge.agency (Admin, owner)\n- (24 more across parent + subaccounts)',
        "api_keys": "- 'Parent Admin' (am_live_sa3b...) — scopes: all — last used: 1 hour ago\n- 'ClientAlpha API' (am_live_ca2k...) — scopes: send, read — last used: 5 min ago\n- 'ClientBeta API' (am_live_cb7m...) — scopes: send, read — last used: 10 min ago\n- (3 more subaccount keys)",
        "webhooks_summary": '- wh_df01: https://api.digitalforge.agency/master-hook — Events: all — Status: active\n- Per-subaccount webhooks configured',
        "template_count": '40',
        "templates_summary": '- Parent and subaccount templates combined\n- (40 templates across all accounts)',
        "contact_count": '450,000',
        "recent_events": '- 420,000 sent across all subaccounts\n- Parent: 85,000 sent\n- ClientAlpha: 120,000 sent (near 150K allocation)\n- ClientBeta: 95,000 sent\n- ClientGamma: 120,000 sent',
        "open_issues": "- Subaccount 'ClientAlpha' approaching allocated quota (120K/150K = 80%)\n- Need to add a new subaccount 'ClientDelta' — current 8/10 subaccount limit",
    },

    # ======================================================================
    # Enterprise Plan Profiles
    # ======================================================================

    # ── enterprise_compliance ───────────────────────────────────────
    "enterprise_compliance": {
        "account_id": 'acct_1a3b5c',
        "plan_name": 'Enterprise',
        "plan_price": '800',
        "emails_sent": '1,450,000',
        "email_limit": '5,000,000',
        "api_calls": '12,300,000',
        "api_call_limit": 'Unlimited',
        "team_count": '45',
        "team_limit": 'Unlimited',
        "created_at": '2023-09-01',
        "billing_cycle_date": 'Renews on the 1st of each month',
        "domain_count": '15',
        "domain_details": '- mail.globalbank.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- alerts.globalbank.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- (13 more domains, all verified with DMARC reject policy)',
        "team_members": '- ciso@globalbank.com (Admin, owner)\n- it-admin@globalbank.com (Admin)\n- (43 more team members across multiple departments)',
        "api_keys": "- 'Transactional' (am_live_1a3b...) — scopes: send, read — last used: 1 min ago\n- 'Marketing Platform' (am_live_5c7d...) — scopes: all — last used: 5 min ago\n- 'Compliance Audit' (am_live_8e9f...) — scopes: read — last used: 1 hour ago\n- 'Staging' (am_test_2g4h...) — scopes: all — last used: 3 days ago",
        "webhooks_summary": '- wh_gb01: https://integrations.globalbank.com/apexmail — Events: all — Status: active\n- wh_gb02: https://compliance.globalbank.com/audit — Events: complained, bounced, unsubscribed — Status: active',
        "template_count": '42',
        "templates_summary": "- 'Account Alert' (tmpl_aa01)\n- 'Transaction Receipt' (tmpl_tr01)\n- 'Security Notice' (tmpl_sn01)\n- (39 more templates)",
        "contact_count": '1,250,000',
        "recent_events": '- 1,450,000 sent, 1,435,500 delivered (99.0%), 7,250 bounced (0.5%), 145 complaints (0.01%)\n- All metrics within healthy thresholds',
        "open_issues": 'None',
    },

    # ── enterprise_dunning ──────────────────────────────────────────
    "enterprise_dunning": {
        "account_id": 'acct_dn7g4m',
        "plan_name": 'Enterprise',
        "plan_price": '800',
        "emails_sent": '890,000',
        "email_limit": '5,000,000',
        "api_calls": '7,200,000',
        "api_call_limit": 'Unlimited',
        "team_count": '25',
        "team_limit": 'Unlimited',
        "created_at": '2024-04-01',
        "billing_cycle_date": 'Renews on the 1st of each month',
        "domain_count": '10',
        "domain_details": '- mail.retailchain.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- (9 more verified domains)',
        "team_members": '- cfo@retailchain.com (Admin, owner)\n- (24 more)',
        "api_keys": "- 'Production' (am_live_dn7g...) — scopes: all — last used: just now",
        "webhooks_summary": '- wh_rc01: https://api.retailchain.com/email — Events: all — Status: active',
        "template_count": '50',
        "templates_summary": '- (50 templates across transactional and marketing)',
        "contact_count": '2,100,000',
        "recent_events": '- 890,000 sent, 881,100 delivered (99.0%), 1,780 bounced (0.2%), 89 complaints (0.01%)\n- ⚠️ Payment failed 3 days ago — account in soft-suspended state\n- Grace period ends in 4 days — sending will be disabled',
        "open_issues": '- ⚠️ SOFT SUSPENDED — Payment failed on Feb 15 (expired credit card)\n- Grace period: 7 days (ends Feb 22)\n- Invoice #INV-2026-1847 — $800 past due\n- Sending still active during grace period but will stop if not resolved',
    },

    # ── enterprise_ecommerce ────────────────────────────────────────
    "enterprise_ecommerce": {
        "account_id": 'acct_ec8m3q',
        "plan_name": 'Enterprise',
        "plan_price": '800',
        "emails_sent": '1,820,000',
        "email_limit": '5,000,000',
        "api_calls": '18,500,000',
        "api_call_limit": 'Unlimited',
        "team_count": '60',
        "team_limit": 'Unlimited',
        "created_at": '2023-06-15',
        "billing_cycle_date": 'Renews on the 15th of each month',
        "domain_count": '20',
        "domain_details": '- orders.megamarket.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- shipping.megamarket.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- promo.megamarket.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- returns.megamarket.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- (16 more domains including regional subdomains)',
        "team_members": '- vp-eng@megamarket.com (Admin, owner)\n- devops@megamarket.com (Admin)\n- (58 more across engineering, marketing, CS, operations)',
        "api_keys": "- 'Order System' (am_live_ec8m...) — scopes: send — last used: just now\n- 'Marketing Platform' (am_live_mp5k...) — scopes: all — last used: 10 min ago\n- 'Analytics' (am_live_an6r...) — scopes: read — last used: 5 min ago\n- (5 more keys for different services)",
        "webhooks_summary": '- wh_mm01: https://platform.megamarket.com/email-events — Events: all — Status: active\n- wh_mm02: https://analytics.megamarket.com/ingest — Events: opened, clicked — Status: active\n- wh_mm03: https://fraud.megamarket.com/check — Events: bounced, complained — Status: active',
        "template_count": '85',
        "templates_summary": "- 'Order Confirmation' (tmpl_oc01)\n- 'Shipping Notification' (tmpl_sn01)\n- 'Delivery Confirmation' (tmpl_dc01)\n- 'Return Accepted' (tmpl_ra01)\n- (81 more including 12 regional variants)",
        "contact_count": '4,200,000',
        "recent_events": '- 1,820,000 sent, 1,801,800 delivered (99.0%), 5,460 bounced (0.3%), 364 complaints (0.02%)\n- 36.4% email limit used (1.82M/5M)',
        "open_issues": '- Email usage: 1.82M/5M (36.4%) with spring sale starting in 5 days',
    },

    # ── enterprise_fintech ──────────────────────────────────────────
    "enterprise_fintech": {
        "account_id": 'acct_ft6n2w',
        "plan_name": 'Enterprise',
        "plan_price": '800',
        "emails_sent": '980,000',
        "email_limit": '5,000,000',
        "api_calls": '8,900,000',
        "api_call_limit": 'Unlimited',
        "team_count": '35',
        "team_limit": 'Unlimited',
        "created_at": '2024-01-10',
        "billing_cycle_date": 'Renews on the 10th of each month',
        "domain_count": '8',
        "domain_details": '- noreply.paynexus.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- alerts.paynexus.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- auth.paynexus.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- compliance.paynexus.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- (4 more regional domains)',
        "team_members": '- cto@paynexus.com (Admin, owner)\n- security-lead@paynexus.com (Admin)\n- (33 more across engineering, compliance, operations)',
        "api_keys": "- 'Auth Service' (am_live_ft6n...) — scopes: send — last used: just now, IP-restricted\n- 'Transaction Alerts' (am_live_ta3k...) — scopes: send — last used: just now\n- 'Compliance Reports' (am_live_cr8m...) — scopes: read — last used: 1 hour ago\n- (3 more keys)",
        "webhooks_summary": '- wh_pn01: https://api.paynexus.com/email-events — Events: all — Status: active\n- wh_pn02: https://compliance.paynexus.com/audit — Events: all — Status: active',
        "template_count": '22',
        "templates_summary": "- 'Transaction Alert' (tmpl_ta01)\n- 'Login Verification' (tmpl_lv01)\n- 'Payment Received' (tmpl_pr01)\n- (19 more)",
        "contact_count": '2,800,000',
        "recent_events": '- 980,000 sent, 975,100 delivered (99.5%), 1,960 bounced (0.2%), 10 complaints (0.001%)',
        "open_issues": 'None',
    },

    # ── enterprise_government ───────────────────────────────────────
    "enterprise_government": {
        "account_id": 'acct_gv4m8s',
        "plan_name": 'Enterprise',
        "plan_price": '800',
        "emails_sent": '650,000',
        "email_limit": '5,000,000',
        "api_calls": '5,200,000',
        "api_call_limit": 'Unlimited',
        "team_count": '80',
        "team_limit": 'Unlimited',
        "created_at": '2023-12-01',
        "billing_cycle_date": 'Renews on the 1st of each month',
        "domain_count": '12',
        "domain_details": '- notifications.cityportal.gov: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- permits.cityportal.gov: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- taxes.cityportal.gov: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- (9 more department domains, all verified)',
        "team_members": '- it-director@cityportal.gov (Admin, owner)\n- (79 more across 12 departments)',
        "api_keys": "- 'Main System' (am_live_gv4m...) — scopes: send, read — last used: just now\n- (5 more departmental keys)",
        "webhooks_summary": '- wh_cp01: https://api.cityportal.gov/email — Events: all — Status: active',
        "template_count": '30',
        "templates_summary": "- 'Permit Approved' (tmpl_pa01)\n- 'Tax Notice' (tmpl_tn01)\n- 'Emergency Alert' (tmpl_ea01)\n- (27 more)",
        "contact_count": '1,500,000',
        "recent_events": '- 650,000 sent, 643,500 delivered (99.0%), 1,300 bounced (0.2%), 13 complaints (0.002%)',
        "open_issues": '- GDPR data deletion request from EU citizen — needs processing within 72 hours\n- Requesting FedRAMP compliance documentation',
    },

    # ── enterprise_hipaa ────────────────────────────────────────────
    "enterprise_hipaa": {
        "account_id": 'acct_hp4m8r',
        "plan_name": 'Enterprise',
        "plan_price": '800',
        "emails_sent": '820,000',
        "email_limit": '5,000,000',
        "api_calls": '6,800,000',
        "api_call_limit": 'Unlimited',
        "team_count": '40',
        "team_limit": 'Unlimited',
        "created_at": '2023-11-01',
        "billing_cycle_date": 'Renews on the 1st of each month',
        "domain_count": '6',
        "domain_details": '- secure.healthfirst.org: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- patient.healthfirst.org: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- billing.healthfirst.org: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- (3 more verified domains)',
        "team_members": '- ciso@healthfirst.org (Admin, owner)\n- cto@healthfirst.org (Admin)\n- compliance@healthfirst.org (Admin)\n- (37 more members)',
        "api_keys": "- 'Patient Portal' (am_live_hp4m...) — scopes: send — last used: 1 min ago — IP-restricted\n- 'EHR Integration' (am_live_ehr2...) — scopes: send, contacts — last used: 5 min ago — IP-restricted\n- 'Audit Read' (am_live_ar7k...) — scopes: read — last used: 2 hours ago — IP-restricted",
        "webhooks_summary": '- wh_hf01: https://api.healthfirst.org/email-events — Events: all — Status: active (HMAC-signed)\n- wh_hf02: https://compliance.healthfirst.org/audit — Events: all — Status: active (HMAC-signed)',
        "template_count": '14',
        "templates_summary": "- 'Appointment Reminder' (tmpl_ar01)\n- 'Lab Results' (tmpl_lr01)\n- 'Prescription Ready' (tmpl_pr01)\n- (11 more templates)",
        "contact_count": '450,000',
        "recent_events": '- 820,000 sent, 812,000 delivered (99.0%), 1,640 bounced (0.2%), 16 complaints (0.002%)\n- HIPAA BAA signed and on file (executed 2023-11-15)\n- SOC 2 Type II audit completed 2024-08-01 — compliant\n- 730-day data retention policy active',
        "open_issues": '- All compliance requirements met\n- All API keys IP-restricted\n- All webhooks HMAC-signed',
    },

    # ── enterprise_mfa_lockout ──────────────────────────────────────
    "enterprise_mfa_lockout": {
        "account_id": 'acct_ml3k7q',
        "plan_name": 'Enterprise',
        "plan_price": '800',
        "emails_sent": '750,000',
        "email_limit": '5,000,000',
        "api_calls": '6,100,000',
        "api_call_limit": 'Unlimited',
        "team_count": '50',
        "team_limit": 'Unlimited',
        "created_at": '2024-05-15',
        "billing_cycle_date": 'Renews on the 15th of each month',
        "domain_count": '8',
        "domain_details": '- mail.cloudmatrix.io: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- (7 more verified domains)',
        "team_members": '- cto@cloudmatrix.io (Admin, owner) — ⚠️ LOCKED OUT\n- devops@cloudmatrix.io (Admin)\n- (48 more)',
        "api_keys": "- 'Production' (am_live_ml3k...) — scopes: all — last used: just now\n- (5 more keys)",
        "webhooks_summary": '- wh_cm01: https://api.cloudmatrix.io/email — Events: all — Status: active',
        "template_count": '25',
        "templates_summary": '- (25 templates)',
        "contact_count": '1,800,000',
        "recent_events": '- 750,000 sent, 742,500 delivered (99.0%), 1,500 bounced (0.2%), 75 complaints (0.01%)',
        "open_issues": '- Admin user cto@cloudmatrix.io locked out — 5 failed MFA attempts, account locked for 30 minutes\n- CTO lost MFA device (phone replaced) and cannot access backup codes\n- Need to recover admin access',
    },

    # ── enterprise_whitelabel ───────────────────────────────────────
    "enterprise_whitelabel": {
        "account_id": 'acct_wl2k8p',
        "plan_name": 'Enterprise',
        "plan_price": '800',
        "emails_sent": '1,100,000',
        "email_limit": '5,000,000',
        "api_calls": '9,500,000',
        "api_call_limit": 'Unlimited',
        "team_count": '30',
        "team_limit": 'Unlimited',
        "created_at": '2024-02-15',
        "billing_cycle_date": 'Renews on the 15th of each month',
        "domain_count": '25',
        "domain_details": '- platform.emailpro.com: Verified (white-label sending domain)\n- track.emailpro.com: Verified (white-label tracking domain)\n- app.emailpro.com: Verified (white-label dashboard domain)\n- unsub.emailpro.com: Verified (white-label unsubscribe domain)\n- (21 more customer-branded white-label domains)',
        "team_members": '- founder@emailpro.com (Admin, owner)\n- (29 more across platform engineering and support)',
        "api_keys": "- 'Platform Core' (am_live_wl2k...) — scopes: all — last used: just now\n- (8 more customer-facing keys)",
        "webhooks_summary": '- wh_ep01: https://api.emailpro.com/apexmail-events — Events: all — Status: active\n- (Per white-label customer webhooks)',
        "template_count": '100+',
        "templates_summary": '- White-label platform templates managed per customer',
        "contact_count": '3,500,000',
        "recent_events": '- 1,100,000 sent across all white-label customers, 1,089,000 delivered (99.0%)',
        "open_issues": "- White-label customer 'QuickSend' reporting their branded unsubscribe page showing ApexMail branding\n- Need to update white-label CSS for unsub.quicksend.io",
    },

    # ======================================================================
    # Pay-As-You-Go Plan Profiles
    # ======================================================================

    # ── payg_active ─────────────────────────────────────────────────
    "payg_active": {
        "account_id": 'acct_7w3x5y',
        "plan_name": 'Pay-As-You-Go',
        "plan_price": '0 base',
        "emails_sent": '74,200',
        "email_limit": 'Unlimited (usage-based billing)',
        "api_calls": '52,000',
        "api_call_limit": 'First 100K free, then $0.10/1,000',
        "team_count": '1',
        "team_limit": '5',
        "created_at": '2025-09-15',
        "billing_cycle_date": 'Usage billed on the 1st of each month',
        "domain_count": '2',
        "domain_details": '- invoices.freelancer.dev: Verified (SPF: pass, DKIM: pass, DMARC: pass)\n- freelancer.dev: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)',
        "team_members": '- me@freelancer.dev (Admin, owner)',
        "api_keys": "- 'Invoicing' (am_live_7w3x...) — scopes: send — last used: 2 hours ago",
        "webhooks_summary": '- wh_fl01: https://freelancer.dev/hooks/email — Events: delivered, bounced — Status: active',
        "template_count": '2',
        "templates_summary": "- 'Invoice' (tmpl_inv01)\n- 'Payment Receipt' (tmpl_pay01)",
        "contact_count": '1,890',
        "recent_events": '- 74,200 sent, 73,100 delivered (98.5%), 410 bounced (0.6%), 12 complaints (0.02%)\n- Steady growth: 52K last month → 74K this month',
        "open_issues": 'None',
    },

    # ── payg_api_401 ────────────────────────────────────────────────
    "payg_api_401": {
        "account_id": 'acct_a4e1k',
        "plan_name": 'Pay-As-You-Go',
        "plan_price": '0 base',
        "emails_sent": '15,800',
        "email_limit": 'Unlimited (usage-based billing)',
        "api_calls": '45,000',
        "api_call_limit": 'First 100K free, then $0.10/1,000',
        "team_count": '1',
        "team_limit": '5',
        "created_at": '2025-07-10',
        "billing_cycle_date": 'Usage billed on the 1st of each month',
        "domain_count": '1',
        "domain_details": '- saaswidget.io: Verified (SPF: pass, DKIM: pass, DMARC: pass)',
        "team_members": '- founder@saaswidget.io (Admin, owner)',
        "api_keys": "- 'Production' (am_live_a4e1...) — REVOKED 3 hours ago\n- 'Staging' (am_test_b5f2...) — scopes: all — last used: yesterday",
        "webhooks_summary": '- wh_sw01: https://api.saaswidget.io/hooks — Events: delivered, bounced — Status: active',
        "template_count": '3',
        "templates_summary": "- 'Signup Welcome' (tmpl_sw01)\n- 'Password Reset' (tmpl_pr01)\n- 'Usage Report' (tmpl_ur01)",
        "contact_count": '3,200',
        "recent_events": "- 15,800 sent, 15,600 delivered (98.7%), 32 bounced (0.2%), 1 complaint (0.01%)\n- ⚠️ API key 'Production' was accidentally revoked 3 hours ago by team member\n- All API calls returning 401 Unauthorized since 1:30 PM UTC",
        "open_issues": "- API key 'Production' (am_live_a4e1...) revoked — all sends failing with 401\n- 342 queued emails stuck, not sending",
    },

    # ── payg_high_volume ────────────────────────────────────────────
    "payg_high_volume": {
        "account_id": 'acct_hv9q2m',
        "plan_name": 'Pay-As-You-Go',
        "plan_price": '0 base',
        "emails_sent": '580,000',
        "email_limit": 'Unlimited (usage-based billing)',
        "api_calls": '312,000',
        "api_call_limit": 'First 100K free, then $0.10/1,000',
        "team_count": '2',
        "team_limit": '5',
        "created_at": '2025-06-01',
        "billing_cycle_date": 'Usage billed on the 1st of each month',
        "domain_count": '3',
        "domain_details": '- notify.eventbrite-clone.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- tickets.eventbrite-clone.com: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- eventbrite-clone.com: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)',
        "team_members": '- cto@eventbrite-clone.com (Admin, owner)\n- dev@eventbrite-clone.com (Editor)',
        "api_keys": "- 'Event Engine' (am_live_hv9q...) — scopes: send, read — last used: just now",
        "webhooks_summary": '- wh_ec01: https://api.eventbrite-clone.com/email — Events: all — Status: active',
        "template_count": '8',
        "templates_summary": "- 'Ticket Confirmation' (tmpl_tc01)\n- 'Event Reminder' (tmpl_er01)\n- 'RSVP Confirmation' (tmpl_rc01)\n- (5 more)",
        "contact_count": '125,000',
        "recent_events": '- 580,000 sent, 574,200 delivered (99.0%), 1,740 bounced (0.3%), 58 complaints (0.01%)\n- Estimated bill: $10 + $72 + $240 = $322 for emails + $21.20 for API',
        "open_issues": 'None',
    },

    # ── payg_seasonal ───────────────────────────────────────────────
    "payg_seasonal": {
        "account_id": 'acct_sn8k4q',
        "plan_name": 'Pay-As-You-Go',
        "plan_price": '0 base',
        "emails_sent": '145,000',
        "email_limit": 'Unlimited (usage-based billing)',
        "api_calls": '98,000',
        "api_call_limit": 'First 100K free, then $0.10/1,000',
        "team_count": '2',
        "team_limit": '5',
        "created_at": '2025-05-15',
        "billing_cycle_date": 'Usage billed on the 1st of each month',
        "domain_count": '2',
        "domain_details": '- mail.taxseason.app: Verified (SPF: pass, DKIM: pass, DMARC: pass)\n- taxseason.app: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)',
        "team_members": '- founder@taxseason.app (Admin, owner)\n- dev@taxseason.app (Editor)',
        "api_keys": "- 'Main' (am_live_sn8k...) — scopes: send, read — last used: just now",
        "webhooks_summary": '- wh_ts01: https://api.taxseason.app/email — Events: delivered, bounced — Status: active',
        "template_count": '5',
        "templates_summary": "- 'Filing Confirmation' (tmpl_fc01)\n- 'Tax Reminder' (tmpl_tr01)\n- 'Document Ready' (tmpl_dr01)\n- (2 more)",
        "contact_count": '42,000',
        "recent_events": '- 145,000 sent this month (seasonal spike — tax filing deadline approaching)\n- Last 3 months: 5K, 8K, 145K — 18x volume increase this month\n- Deliverability holding: 98.2% delivery rate, 0.4% bounce, 0.03% complaints',
        "open_issues": '- Volume spike flagged for review (145K vs normal 5-8K)\n- Approaching free API call limit (98K/100K = 98%)',
    },

    # ======================================================================
    # Unknown Plan Profiles
    # ======================================================================

    # ── no_context ──────────────────────────────────────────────────
    "no_context": {
        "account_id": 'unknown',
        "plan_name": 'Unknown',
        "plan_price": 'unknown',
        "emails_sent": 'N/A',
        "email_limit": 'N/A',
        "api_calls": 'N/A',
        "api_call_limit": 'N/A',
        "team_count": 'N/A',
        "team_limit": 'N/A',
        "created_at": 'N/A',
        "billing_cycle_date": 'N/A',
        "domain_count": '0',
        "domain_details": '- No account data available (unauthenticated or general inquiry)',
        "team_members": '- N/A',
        "api_keys": '- N/A',
        "webhooks_summary": '- N/A',
        "template_count": 'N/A',
        "templates_summary": '- N/A',
        "contact_count": 'N/A',
        "recent_events": 'N/A',
        "open_issues": 'N/A',
    },

}
