"""
Extended Customer Profiles — Recovered from deleted files with canonical pricing.

Canonical pricing (EUR; runtime source: billing-service/src/plans.rs):
  Free: €0, 30K emails, 300K API
  Starter: €25, 50K emails, 500K API
  Pro: €65, 150K emails, 2M API
  Growth: €150, 500K emails, 5M API
  Scale: €350, 2M emails, 20M API
  Enterprise: €3,000, 5M emails, unlimited API
"""

EXTENDED_PROFILES = {
    "free_hitting_limits_v2": {
        "account_id": "acct_2n5v8q",
        "plan_name": "Free",
        "plan_price": "0",
        "emails_sent": "2,850",
        "email_limit": "30,000",
        "api_calls": "45,000",
        "api_call_limit": "300,000",
        "team_count": "1",
        "team_limit": "1",
        "created_at": "2026-01-28",
        "domain_count": "1",
        "domain_details": "- myshop.com: Verified (SPF: pass, DKIM: pass, DMARC: none)",
        "recent_events": "- 2,850 sent, 2,793 delivered (98.0%), 23 bounced (0.8%), 0 complaints",
        "open_issues": "- Approaching email limit: 28,500/30,000 (95% used)"
    },
    "free_spf_broken_v2": {
        "account_id": "acct_sp2f8z",
        "plan_name": "Free",
        "plan_price": "0",
        "emails_sent": "1,350",
        "email_limit": "30,000",
        "api_calls": "12,000",
        "api_call_limit": "300,000",
        "created_at": "2025-12-01",
        "domain_count": "1",
        "domain_details": "- petgrooming.co: Verified (SPF: fail \u2014 multiple SPF records, DKIM: pass, DMARC: none)",
        "recent_events": "- 1,350 sent, 1,140 delivered (84.4%), 75 bounced (5.6%), 0 complaints\n- Deliverability dropped after adding Mailchimp SPF record 5 days ago",
        "open_issues": "- SPF failure: 2 SPF TXT records found (ApexMail + Mailchimp). Only 1 SPF record per domain allowed."
    },
    "starter_healthy_v2": {
        "account_id": "acct_8f3k2j",
        "plan_name": "Starter",
        "plan_price": "25",
        "emails_sent": "36,240",
        "email_limit": "50,000",
        "api_calls": "285,000",
        "api_call_limit": "500,000",
        "team_count": "2",
        "team_limit": "5",
        "created_at": "2025-06-15",
        "domain_count": "1",
        "domain_details": "- acmecorp.com: Verified (SPF: pass, DKIM: pass, DMARC: pass)",
        "recent_events": "- 36,240 sent, 35,580 delivered (98.2%), 104 bounced (0.3%), 6 complaints (0.02%)",
        "open_issues": "None"
    },
    "starter_webhook_dead_v2": {
        "account_id": "acct_wh7d3k",
        "plan_name": "Starter",
        "plan_price": "25",
        "emails_sent": "24,800",
        "email_limit": "50,000",
        "api_calls": "178,000",
        "api_call_limit": "500,000",
        "team_count": "2",
        "team_limit": "5",
        "created_at": "2025-08-22",
        "domain_details": "- bakerydelight.com: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)",
        "open_issues": "- Webhook wh_bd01 auto-disabled after 8 consecutive failures (HTTP 500) over 24 hours"
    },
    "starter_dmarc_quarantine": {
        "account_id": "acct_dmq2k3",
        "plan_name": "Starter",
        "plan_price": "25",
        "emails_sent": "18,500",
        "email_limit": "50,000",
        "api_calls": "95,000",
        "api_call_limit": "500,000",
        "team_count": "1",
        "team_limit": "5",
        "domain_details": "- newsletters.example.com: Verified (SPF: pass, DKIM: pass, DMARC: quarantine)",
        "recent_events": "- 18,500 sent, 16,650 delivered (90.0%), 925 quarantined (5.0%)",
        "open_issues": "- DMARC policy causing quarantine of 5% of emails to strict ISPs"
    },
    "pro_healthy_v2": {
        "account_id": "acct_pr65k8",
        "plan_name": "Pro",
        "plan_price": "65",
        "emails_sent": "87,500",
        "email_limit": "150,000",
        "api_calls": "1,250,000",
        "api_call_limit": "2,000,000",
        "team_count": "4",
        "team_limit": "5",
        "domain_count": "3",
        "domain_details": "- techstartup.io: Verified (SPF: pass, DKIM: pass, DMARC: reject)\n- notifications.techstartup.io: Verified\n- marketing.techstartup.io: Verified",
        "recent_events": "- 87,500 sent, 86,625 delivered (99.0%), 175 bounced (0.2%)",
        "open_issues": "None"
    },
    "pro_template_issue": {
        "account_id": "acct_tpl3j9",
        "plan_name": "Pro",
        "plan_price": "65",
        "emails_sent": "45,000",
        "email_limit": "150,000",
        "api_calls": "890,000",
        "api_call_limit": "2,000,000",
        "team_count": "3",
        "team_limit": "5",
        "domain_details": "- ecommerce-shop.com: Verified (SPF: pass, DKIM: pass, DMARC: pass)",
        "open_issues": "- Template 'order-confirmation' rendering errors: {{customer.name}} variable undefined in 3% of sends"
    },
    "pro_ip_warmup": {
        "account_id": "acct_ipw5m2",
        "plan_name": "Pro",
        "plan_price": "65",
        "emails_sent": "12,000",
        "email_limit": "150,000",
        "api_calls": "350,000",
        "api_call_limit": "2,000,000",
        "dedicated_ip": "192.0.2.50",
        "domain_details": "- newbrand.com: Verified (SPF: pass, DKIM: pass, DMARC: none)",
        "open_issues": "- Dedicated IP 192.0.2.50 in warmup phase (day 8 of 30). Sending throttled to 15K/day."
    },
    "growth_bounce_spike_v2": {
        "account_id": "acct_gw150k",
        "plan_name": "Growth",
        "plan_price": "150",
        "emails_sent": "320,000",
        "email_limit": "500,000",
        "api_calls": "3,200,000",
        "api_call_limit": "5,000,000",
        "team_count": "8",
        "team_limit": "10",
        "domain_details": "- saas-platform.io: Verified\n- notifications.saas-platform.io: Verified",
        "recent_events": "- 320,000 sent, 304,000 delivered (95.0%), 9,600 bounced (3.0%), 640 complaints (0.2%)",
        "open_issues": "- Bounce rate 3.0% exceeds 2% threshold\n- Complaint rate 0.2% exceeds 0.1% threshold"
    },
    "growth_dkim_fail_v2": {
        "account_id": "acct_dkf8n3",
        "plan_name": "Growth",
        "plan_price": "150",
        "emails_sent": "267,500",
        "email_limit": "500,000",
        "api_calls": "2,450,000",
        "api_call_limit": "5,000,000",
        "team_count": "6",
        "team_limit": "10",
        "domain_details": "- techflow.io: Verified (SPF: pass, DKIM: pass)\n- marketing.techflow.io: Verified (SPF: pass, DKIM: FAIL)\n- notifications.techflow.io: Verified (all pass)",
        "recent_events": "- 267,500 sent, 247,413 delivered (92.5%), 6,688 bounced (2.5%)",
        "open_issues": "- DKIM failing on marketing.techflow.io since DNS change 3 days ago\n- Domain bounce rate: 26.2%"
    },
    "growth_subaccount_mgmt": {
        "account_id": "acct_sub7p4",
        "plan_name": "Growth",
        "plan_price": "150",
        "emails_sent": "185,000",
        "email_limit": "500,000",
        "api_calls": "1,850,000",
        "api_call_limit": "5,000,000",
        "team_count": "10",
        "team_limit": "10",
        "subaccounts": "5 active subaccounts",
        "domain_details": "- agency.co: Primary\n- client1.agency.co, client2.agency.co, client3.agency.co: Subaccount domains",
        "open_issues": "- Subaccount 'client3' approaching 90% of allocated quota"
    },
    "scale_deliverability_v2": {
        "account_id": "acct_sc350k",
        "plan_name": "Scale",
        "plan_price": "350",
        "emails_sent": "1,450,000",
        "email_limit": "2,000,000",
        "api_calls": "14,500,000",
        "api_call_limit": "20,000,000",
        "team_count": "20",
        "team_limit": "25",
        "dedicated_ips": "3 IPs: 198.51.100.10, 198.51.100.11, 198.51.100.12",
        "domain_details": "- bigretailer.com: Verified\n- mail.bigretailer.com: Verified\n- promo.bigretailer.com: Verified",
        "recent_events": "- 1,450,000 sent, 1,160,000 delivered (80.0%), 43,500 bounced (3.0%), 2,900 complaints (0.2%)",
        "open_issues": "- IP 198.51.100.12 blocklisted on Spamhaus SBL since Feb 14\n- Gmail delivery dropped from 96% to 78%"
    },
    "scale_api_rate_limit": {
        "account_id": "acct_arl9k2",
        "plan_name": "Scale",
        "plan_price": "350",
        "emails_sent": "1,200,000",
        "email_limit": "2,000,000",
        "api_calls": "18,500,000",
        "api_call_limit": "20,000,000",
        "team_count": "15",
        "team_limit": "25",
        "domain_details": "- highvolume.io: Verified",
        "recent_events": "- Several API rate limit errors (429s) during peak hours 2-4pm UTC",
        "open_issues": "- API usage at 92.5% of limit\n- Rate limiting triggered 47 times this month"
    },
    "scale_greylist_delays": {
        "account_id": "acct_gry6m8",
        "plan_name": "Scale",
        "plan_price": "350",
        "emails_sent": "980,000",
        "email_limit": "2,000,000",
        "api_calls": "8,200,000",
        "api_call_limit": "20,000,000",
        "team_count": "12",
        "team_limit": "25",
        "domain_details": "- enterprise-saas.com: Verified",
        "recent_events": "- 980,000 sent, 931,000 delivered (95.0%), 19,600 deferred (2.0%), 9,800 bounced (1.0%)",
        "open_issues": "- Greylisting causing 15-30 minute delays on ~8% of sends to Microsoft 365 recipients"
    },
    "enterprise_compliance_v2": {
        "account_id": "acct_ent800k",
        "plan_name": "Enterprise",
        "plan_price": "3000",
        "emails_sent": "3,625,000",
        "email_limit": "5,000,000",
        "api_calls": "45,000,000",
        "api_call_limit": "Unlimited",
        "team_count": "45",
        "team_limit": "Unlimited",
        "dedicated_ips": "5 IPs with automated rotation",
        "domain_details": "- globalbank.com: Verified (15+ subdomains)",
        "compliance": "SOC2, HIPAA, GDPR enabled",
        "recent_events": "- 3,625,000 sent, 3,552,500 delivered (98.0%), 36,250 bounced (1.0%)",
        "open_issues": "- GDPR data deletion request pending for 3 contacts"
    },
    "enterprise_sso_issue": {
        "account_id": "acct_sso4j7",
        "plan_name": "Enterprise",
        "plan_price": "3000",
        "emails_sent": "2,150,000",
        "email_limit": "5,000,000",
        "api_calls": "28,000,000",
        "api_call_limit": "Unlimited",
        "team_count": "82",
        "team_limit": "Unlimited",
        "sso_provider": "Okta SAML",
        "domain_details": "- megacorp.com: Verified (8 subdomains)",
        "open_issues": "- SSO login failures for 12 users since certificate rotation\n- SAML assertion signature verification failing"
    },
    "enterprise_multi_region": {
        "account_id": "acct_mrg2l5",
        "plan_name": "Enterprise",
        "plan_price": "3000",
        "emails_sent": "4,200,000",
        "email_limit": "5,000,000",
        "api_calls": "52,000,000",
        "api_call_limit": "Unlimited",
        "team_count": "125",
        "team_limit": "Unlimited",
        "regions": "US, EU, APAC",
        "dedicated_ips": "12 IPs across 3 regions",
        "domain_details": "- globalco.com: Primary\n- eu.globalco.com, apac.globalco.com: Regional",
        "open_issues": "- EU region latency spike (avg 450ms \u2192 1200ms) since 48h ago"
    }
}
