//! SOC 2 Type II compliance subsystem.
//!
//! Provides:
//!   * The Trust Service Criteria (TSC) control catalog (Common Criteria CC1–CC9
//!     plus Availability A1, Confidentiality C1, Processing Integrity PI1, and
//!     Privacy P1–P8 categories).
//!   * Automated evidence collectors that pull point-in-time evidence from the
//!     audit log, secrets table, risk-scoring data, and other compliance
//!     artifacts.  Each piece of evidence is hash-locked (SHA-256) and stored
//!     in `soc2_control_evidence` with the canonical period it covers.
//!   * A run-tracker (`soc2_evidence_collection_runs`) for the cron worker so
//!     ops can see which controls passed automated evidence collection.
//!
//! Database schema lives in migration `039_soc2_hipaa_trust_portal.sql`.
//!
//! The catalog seeded here mirrors AICPA TSP Section 100 (2017, with the 2022
//! Points of Focus refresh).  A SOC 2 report is generated by exporting the
//! controls list together with evidence for the audit period.

use chrono::{DateTime, Duration, Utc};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use sqlx::PgPool;
use std::time::Instant;
use tracing::{info, warn};
use uuid::Uuid;

// ─── Public types ──────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ControlStatus {
    InScope,
    NotApplicable,
    Deferred,
}

impl ControlStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::InScope => "in_scope",
            Self::NotApplicable => "not_applicable",
            Self::Deferred => "deferred",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AutomationLevel {
    Manual,
    Automated,
    Hybrid,
}

impl AutomationLevel {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Manual => "manual",
            Self::Automated => "automated",
            Self::Hybrid => "hybrid",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Control {
    pub id: String,
    pub control_id: String,
    pub category: String,
    pub title: String,
    pub description: String,
    pub owner: String,
    pub status: String,
    pub evidence_required: serde_json::Value,
    pub automation: String,
    pub last_attested_at: Option<DateTime<Utc>>,
    pub next_attestation_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ControlEvidence {
    pub id: String,
    pub control_id: String,
    pub evidence_type: String,
    pub source: String,
    pub payload: serde_json::Value,
    pub sha256_hash: String,
    pub storage_url: Option<String>,
    pub period_start: DateTime<Utc>,
    pub period_end: DateTime<Utc>,
    pub collected_at: DateTime<Utc>,
    pub collected_by: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CollectionRunSummary {
    pub started_at: DateTime<Utc>,
    pub finished_at: DateTime<Utc>,
    pub controls_attempted: u32,
    pub controls_succeeded: u32,
    pub controls_failed: u32,
    pub items_collected: u32,
    pub failures: Vec<String>,
}

// ─── Default control catalog (TSP-100 mapping) ─────────────────────────────

/// Catalog seed entry — single source of truth for which controls ApexMail
/// attests to.
#[derive(Debug, Clone)]
struct ControlSeed {
    control_id: &'static str,
    category: &'static str,
    title: &'static str,
    description: &'static str,
    owner: &'static str,
    evidence_required: &'static [&'static str],
    automation: AutomationLevel,
}

const DEFAULT_CONTROLS: &[ControlSeed] = &[
    // ── Common Criteria — Control Environment (CC1) ────────────────────────
    ControlSeed {
        control_id: "CC1.1",
        category: "Common Criteria — Control Environment",
        title: "Demonstrates a commitment to integrity and ethical values",
        description:
            "ApexMail maintains a published code of conduct, ethical hiring policies, and \
             documented disciplinary procedures. Annual ethics training is mandatory.",
        owner: "People Operations",
        evidence_required: &["code_of_conduct_acknowledgement", "ethics_training_log"],
        automation: AutomationLevel::Manual,
    },
    ControlSeed {
        control_id: "CC1.2",
        category: "Common Criteria — Control Environment",
        title: "Board exercises oversight responsibility",
        description:
            "An independent security committee reviews quarterly risk reports, audit \
             findings, and material policy changes.",
        owner: "Executive",
        evidence_required: &["security_committee_minutes"],
        automation: AutomationLevel::Manual,
    },
    ControlSeed {
        control_id: "CC1.3",
        category: "Common Criteria — Control Environment",
        title: "Establishes structure, authority, and responsibility",
        description:
            "Organisational chart, job descriptions, and segregation-of-duties matrix are \
             reviewed annually.",
        owner: "People Operations",
        evidence_required: &["org_chart", "sod_matrix"],
        automation: AutomationLevel::Manual,
    },
    // ── Communication and Information (CC2) ────────────────────────────────
    ControlSeed {
        control_id: "CC2.1",
        category: "Common Criteria — Communication and Information",
        title: "Obtains or generates relevant, quality information",
        description:
            "Production systems emit audit logs (hash-chained, tamper-evident) for all \
             security-relevant operations.",
        owner: "Engineering",
        evidence_required: &["audit_log_sample", "audit_chain_verification"],
        automation: AutomationLevel::Automated,
    },
    ControlSeed {
        control_id: "CC2.2",
        category: "Common Criteria — Communication and Information",
        title: "Internally communicates information about objectives and responsibilities",
        description:
            "Security policies, incident-response runbooks, and on-call rotations are \
             published and reviewed semi-annually.",
        owner: "Security",
        evidence_required: &["policy_publication_log", "runbook_review_log"],
        automation: AutomationLevel::Manual,
    },
    // ── Risk Assessment (CC3) ──────────────────────────────────────────────
    ControlSeed {
        control_id: "CC3.1",
        category: "Common Criteria — Risk Assessment",
        title: "Specifies suitable objectives",
        description:
            "Annual risk assessment identifies threats to confidentiality, integrity, \
             availability, and privacy of customer data; tracked in risk_profiles table.",
        owner: "Security",
        evidence_required: &["risk_assessment_export"],
        automation: AutomationLevel::Hybrid,
    },
    ControlSeed {
        control_id: "CC3.2",
        category: "Common Criteria — Risk Assessment",
        title: "Identifies and assesses risks",
        description:
            "Tenant-level risk scoring runs continuously; flags above the critical \
             threshold trigger automated rate-limiting and human review.",
        owner: "Engineering",
        evidence_required: &["risk_profile_snapshot", "flag_resolutions_log"],
        automation: AutomationLevel::Automated,
    },
    // ── Monitoring (CC4) ───────────────────────────────────────────────────
    ControlSeed {
        control_id: "CC4.1",
        category: "Common Criteria — Monitoring Activities",
        title: "Selects, develops, and performs ongoing monitoring",
        description:
            "Continuous monitoring via Prometheus + Grafana; alert rules in \
             deploy/alerting-rules.yml; on-call paged for SEV-1/2.",
        owner: "Engineering",
        evidence_required: &["monitoring_alerts_log"],
        automation: AutomationLevel::Automated,
    },
    ControlSeed {
        control_id: "CC4.2",
        category: "Common Criteria — Monitoring Activities",
        title: "Evaluates and communicates deficiencies",
        description:
            "Quarterly internal-audit findings are tracked to closure with assigned owner \
             and remediation date.",
        owner: "Security",
        evidence_required: &["internal_audit_report", "remediation_tracker"],
        automation: AutomationLevel::Manual,
    },
    // ── Control Activities (CC5) ───────────────────────────────────────────
    ControlSeed {
        control_id: "CC5.1",
        category: "Common Criteria — Control Activities",
        title: "Selects and develops control activities",
        description:
            "Change-management policy requires peer review for all production deploys; \
             pull-request approvals are recorded in source control.",
        owner: "Engineering",
        evidence_required: &["change_management_log"],
        automation: AutomationLevel::Hybrid,
    },
    ControlSeed {
        control_id: "CC5.2",
        category: "Common Criteria — Control Activities",
        title: "Selects and develops general controls over technology",
        description:
            "Infrastructure-as-code (Terraform/Helm) gates production changes; the \
             build pipeline blocks merges that fail tests, lints, or security scans.",
        owner: "Engineering",
        evidence_required: &["ci_pipeline_log"],
        automation: AutomationLevel::Automated,
    },
    ControlSeed {
        control_id: "CC5.3",
        category: "Common Criteria — Control Activities",
        title: "Deploys control activities through policies and procedures",
        description:
            "All security-relevant SOPs are versioned in the documentation portal and \
             reviewed annually.",
        owner: "Security",
        evidence_required: &["policy_review_log"],
        automation: AutomationLevel::Manual,
    },
    // ── Logical & Physical Access (CC6) ────────────────────────────────────
    ControlSeed {
        control_id: "CC6.1",
        category: "Common Criteria — Logical and Physical Access Controls",
        title: "Implements logical access security",
        description:
            "Role-based access control enforced via JWT scopes and admin-route guards; \
             audit log records every privileged operation.",
        owner: "Security",
        evidence_required: &["access_review", "rbac_policy", "audit_log_sample"],
        automation: AutomationLevel::Automated,
    },
    ControlSeed {
        control_id: "CC6.2",
        category: "Common Criteria — Logical and Physical Access Controls",
        title: "Manages access registration, modification, and removal",
        description:
            "Quarterly access review enumerates active human and machine identities, \
             access levels, and reasons.",
        owner: "Security",
        evidence_required: &["quarterly_access_review"],
        automation: AutomationLevel::Hybrid,
    },
    ControlSeed {
        control_id: "CC6.3",
        category: "Common Criteria — Logical and Physical Access Controls",
        title: "Manages credentials and authenticators",
        description:
            "Customer-supplied secrets are encrypted at rest with AES-256-GCM; rotation \
             policies are enforced by the secret manager (max 90 days for production).",
        owner: "Engineering",
        evidence_required: &["secret_rotation_log"],
        automation: AutomationLevel::Automated,
    },
    ControlSeed {
        control_id: "CC6.4",
        category: "Common Criteria — Logical and Physical Access Controls",
        title: "Restricts physical access",
        description:
            "All production infrastructure runs in SOC 2 / ISO 27001 certified data \
             centers (see Trust Portal subprocessor list).",
        owner: "Operations",
        evidence_required: &["subprocessor_attestations"],
        automation: AutomationLevel::Manual,
    },
    ControlSeed {
        control_id: "CC6.6",
        category: "Common Criteria — Logical and Physical Access Controls",
        title: "Implements boundary protection",
        description:
            "WAF, IDS, DDoS protection, and rate-limiting form the perimeter; events are \
             ingested into the security data lake.",
        owner: "Engineering",
        evidence_required: &["waf_event_summary", "ids_event_summary"],
        automation: AutomationLevel::Automated,
    },
    ControlSeed {
        control_id: "CC6.7",
        category: "Common Criteria — Logical and Physical Access Controls",
        title: "Restricts movement of information",
        description:
            "DLP rules block exfiltration of PHI/PII; outbound mail is scanned by the \
             DLP engine and content scanner.",
        owner: "Security",
        evidence_required: &["dlp_policy_summary"],
        automation: AutomationLevel::Automated,
    },
    ControlSeed {
        control_id: "CC6.8",
        category: "Common Criteria — Logical and Physical Access Controls",
        title: "Detects and prevents malicious software",
        description:
            "All inbound mail is sandboxed and scanned for malware; suspicious \
             attachments are quarantined.",
        owner: "Security",
        evidence_required: &["scan_results_summary"],
        automation: AutomationLevel::Automated,
    },
    // ── System Operations (CC7) ────────────────────────────────────────────
    ControlSeed {
        control_id: "CC7.1",
        category: "Common Criteria — System Operations",
        title: "Detects and monitors changes",
        description:
            "Configuration drift detection runs hourly; unexpected changes alert on-call.",
        owner: "Engineering",
        evidence_required: &["drift_detection_log"],
        automation: AutomationLevel::Automated,
    },
    ControlSeed {
        control_id: "CC7.2",
        category: "Common Criteria — System Operations",
        title: "Monitors operations to detect security events",
        description:
            "SIEM rules trigger on anomalous patterns (failed-auth bursts, privilege \
             escalations, suspicious queue volumes).",
        owner: "Security",
        evidence_required: &["siem_alert_summary"],
        automation: AutomationLevel::Automated,
    },
    ControlSeed {
        control_id: "CC7.3",
        category: "Common Criteria — System Operations",
        title: "Evaluates security events to determine response",
        description:
            "Documented incident-response playbooks; SEV-1/2 incidents tracked in the \
             trust portal incident log.",
        owner: "Security",
        evidence_required: &["incident_response_log"],
        automation: AutomationLevel::Hybrid,
    },
    ControlSeed {
        control_id: "CC7.4",
        category: "Common Criteria — System Operations",
        title: "Responds to identified security events",
        description:
            "Incident triage SLAs: SEV-1 acknowledge < 15min, mitigate < 1h; tracked in \
             trust_portal_incidents.",
        owner: "Security",
        evidence_required: &["incident_metrics"],
        automation: AutomationLevel::Automated,
    },
    ControlSeed {
        control_id: "CC7.5",
        category: "Common Criteria — System Operations",
        title: "Identifies and develops corrective actions",
        description:
            "Post-incident reviews produce action items tracked to closure.",
        owner: "Engineering",
        evidence_required: &["postmortem_log"],
        automation: AutomationLevel::Manual,
    },
    // ── Change Management (CC8) ────────────────────────────────────────────
    ControlSeed {
        control_id: "CC8.1",
        category: "Common Criteria — Change Management",
        title: "Authorises, designs, develops, and approves changes",
        description:
            "All production changes are authorised via signed pull requests; emergency \
             changes require post-hoc review.",
        owner: "Engineering",
        evidence_required: &["change_management_log"],
        automation: AutomationLevel::Hybrid,
    },
    // ── Risk Mitigation (CC9) ──────────────────────────────────────────────
    ControlSeed {
        control_id: "CC9.1",
        category: "Common Criteria — Risk Mitigation",
        title: "Identifies, selects, and develops risk-mitigation activities",
        description:
            "Annual penetration test by independent third party; findings remediated by \
             severity SLA.",
        owner: "Security",
        evidence_required: &["pentest_report", "remediation_log"],
        automation: AutomationLevel::Manual,
    },
    ControlSeed {
        control_id: "CC9.2",
        category: "Common Criteria — Risk Mitigation",
        title: "Assesses and manages risks associated with vendors",
        description:
            "Subprocessors undergo security review before onboarding and annually \
             thereafter; tracked in trust_portal_subprocessors.",
        owner: "Security",
        evidence_required: &["vendor_review_log"],
        automation: AutomationLevel::Manual,
    },
    // ── Availability (A1) ──────────────────────────────────────────────────
    ControlSeed {
        control_id: "A1.1",
        category: "Availability",
        title: "Maintains, monitors, and evaluates current processing capacity",
        description:
            "Capacity dashboards monitor send-queue depth, database connection pool \
             utilisation, and per-tenant rate-limiter state; auto-scaling configured.",
        owner: "Engineering",
        evidence_required: &["capacity_metrics"],
        automation: AutomationLevel::Automated,
    },
    ControlSeed {
        control_id: "A1.2",
        category: "Availability",
        title: "Authorises, designs, develops, implements, operates, approves, maintains, and monitors environmental protections, software, data backup processes, and recovery infrastructure",
        description:
            "Daily encrypted backups with monthly restore tests; documented BCP/DR plan \
             with quarterly tabletop exercises.",
        owner: "Engineering",
        evidence_required: &["backup_test_log", "dr_drill_log"],
        automation: AutomationLevel::Hybrid,
    },
    ControlSeed {
        control_id: "A1.3",
        category: "Availability",
        title: "Tests recovery plan procedures",
        description:
            "Annual full-scale BCP/DR exercise with measured RTO and RPO.",
        owner: "Engineering",
        evidence_required: &["dr_drill_log"],
        automation: AutomationLevel::Manual,
    },
    // ── Confidentiality (C1) ───────────────────────────────────────────────
    ControlSeed {
        control_id: "C1.1",
        category: "Confidentiality",
        title: "Identifies and maintains confidential information",
        description:
            "Customer data classified by sensitivity; encryption at rest (AES-256) and \
             in transit (TLS 1.2+); dedicated encryption keys per tenant for HIPAA.",
        owner: "Security",
        evidence_required: &["encryption_config", "kms_audit_log"],
        automation: AutomationLevel::Automated,
    },
    ControlSeed {
        control_id: "C1.2",
        category: "Confidentiality",
        title: "Disposes of confidential information",
        description:
            "GDPR right-to-erasure executed via gdpr_automation; deletion confirmed \
             with audit-log evidence.",
        owner: "Security",
        evidence_required: &["gdpr_deletion_log"],
        automation: AutomationLevel::Automated,
    },
    // ── Processing Integrity (PI1) ─────────────────────────────────────────
    ControlSeed {
        control_id: "PI1.1",
        category: "Processing Integrity",
        title: "Obtains or generates, uses, and communicates accurate, complete, and relevant information",
        description:
            "Idempotency keys protect message-submission paths; failed deliveries are \
             retried with exponential backoff and surfaced via webhooks.",
        owner: "Engineering",
        evidence_required: &["delivery_metrics"],
        automation: AutomationLevel::Automated,
    },
    // ── Privacy (P1–P8) ────────────────────────────────────────────────────
    ControlSeed {
        control_id: "P1.1",
        category: "Privacy",
        title: "Provides notice about its privacy practices",
        description:
            "Privacy policy published at /trust/privacy; updates trigger customer \
             notification.",
        owner: "Legal",
        evidence_required: &["privacy_policy_version"],
        automation: AutomationLevel::Manual,
    },
    ControlSeed {
        control_id: "P2.1",
        category: "Privacy",
        title: "Communicates choices and obtains consent",
        description:
            "Double opt-in tokens persisted in double_opt_in_tokens; consent records \
             include signed proof documents.",
        owner: "Engineering",
        evidence_required: &["consent_records_summary"],
        automation: AutomationLevel::Automated,
    },
    ControlSeed {
        control_id: "P3.1",
        category: "Privacy",
        title: "Collects personal information consistent with the entity’s objectives",
        description:
            "Subscriber-level metadata is limited to what is required for delivery; PHI \
             is suppressed in audit logs when HIPAA mode is enabled.",
        owner: "Engineering",
        evidence_required: &["pii_minimisation_review"],
        automation: AutomationLevel::Manual,
    },
    ControlSeed {
        control_id: "P4.1",
        category: "Privacy",
        title: "Limits use, retention, and disposal",
        description:
            "Retention policies enforced via gdpr_automation::enforce_retention; \
             expired consent records and exports are purged daily.",
        owner: "Engineering",
        evidence_required: &["retention_enforcement_log"],
        automation: AutomationLevel::Automated,
    },
    ControlSeed {
        control_id: "P5.1",
        category: "Privacy",
        title: "Provides access to personal information",
        description:
            "Data-subject access requests automated via /gdpr/submit and processed \
             within the configured SLA.",
        owner: "Security",
        evidence_required: &["dsr_metrics"],
        automation: AutomationLevel::Automated,
    },
    ControlSeed {
        control_id: "P6.1",
        category: "Privacy",
        title: "Discloses personal information to third parties only with consent",
        description:
            "Subprocessors disclosed in trust_portal_subprocessors; customer DPAs \
             reference the live list.",
        owner: "Legal",
        evidence_required: &["subprocessor_list"],
        automation: AutomationLevel::Automated,
    },
    ControlSeed {
        control_id: "P7.1",
        category: "Privacy",
        title: "Maintains data quality",
        description:
            "Bounce, complaint, and verification feedback loops update subscriber state \
             in near real time.",
        owner: "Engineering",
        evidence_required: &["data_quality_metrics"],
        automation: AutomationLevel::Automated,
    },
    ControlSeed {
        control_id: "P8.1",
        category: "Privacy",
        title: "Monitors privacy compliance and handles complaints",
        description:
            "Complaints intake form (privacy@apexmail) is monitored 24/7; SLAs tracked.",
        owner: "Legal",
        evidence_required: &["privacy_complaint_log"],
        automation: AutomationLevel::Manual,
    },
];

// ─── Service ───────────────────────────────────────────────────────────────

/// SOC2 service.  Constructed once at startup; cheap to clone.
#[derive(Clone)]
pub struct Soc2Service {
    db: PgPool,
    /// How frequently each control should be re-attested.  Used to compute
    /// `next_attestation_at` when seeding/updating controls.
    attestation_period_days: i64,
}

impl Soc2Service {
    /// Construct.  Pass the DB pool; the attestation period defaults to 90 days
    /// (matching common SOC 2 Type II audit cadences).
    pub fn new(db: PgPool) -> Self {
        Self {
            db,
            attestation_period_days: 90,
        }
    }

    pub fn with_attestation_period(mut self, days: i64) -> Self {
        self.attestation_period_days = days;
        self
    }

    /// Idempotently seed the default control catalog.  Existing controls are
    /// updated in-place if their description/owner has changed but their
    /// `last_attested_at` is preserved.
    pub async fn seed_default_controls(&self) -> Result<usize, String> {
        let mut inserted = 0usize;
        let now = Utc::now();
        for seed in DEFAULT_CONTROLS {
            let evidence_json = serde_json::to_value(seed.evidence_required)
                .map_err(|e| format!("evidence JSON: {e}"))?;
            let id = format!(
                "control-{}",
                seed.control_id.to_lowercase().replace('.', "-")
            );
            let res = sqlx::query(
                "INSERT INTO soc2_controls
                   (id, control_id, category, title, description, owner, status,
                    evidence_required, automation, last_attested_at,
                    next_attestation_at, created_at, updated_at)
                 VALUES ($1,$2,$3,$4,$5,$6,'in_scope',$7,$8,NULL,$9,$10,$10)
                 ON CONFLICT (control_id) DO UPDATE SET
                   category = EXCLUDED.category,
                   title = EXCLUDED.title,
                   description = EXCLUDED.description,
                   owner = EXCLUDED.owner,
                   evidence_required = EXCLUDED.evidence_required,
                   automation = EXCLUDED.automation,
                   updated_at = EXCLUDED.updated_at",
            )
            .bind(&id)
            .bind(seed.control_id)
            .bind(seed.category)
            .bind(seed.title)
            .bind(seed.description)
            .bind(seed.owner)
            .bind(&evidence_json)
            .bind(seed.automation.as_str())
            .bind(now + Duration::days(self.attestation_period_days))
            .bind(now)
            .execute(&self.db)
            .await
            .map_err(|e| format!("DB error: {e}"))?;
            inserted += res.rows_affected() as usize;
        }
        info!(controls = inserted, "Seeded SOC2 controls");
        Ok(inserted)
    }

    pub async fn list_controls(&self) -> Result<Vec<Control>, String> {
        let rows: Vec<Control> = sqlx::query_as::<_, ControlRow>(
            "SELECT id, control_id, category, title, description, owner, status,
                    evidence_required, automation, last_attested_at,
                    next_attestation_at, created_at, updated_at
             FROM soc2_controls ORDER BY control_id",
        )
        .fetch_all(&self.db)
        .await
        .map_err(|e| format!("DB error: {e}"))?
        .into_iter()
        .map(Into::into)
        .collect();
        Ok(rows)
    }

    pub async fn get_control(&self, control_id: &str) -> Result<Option<Control>, String> {
        let row: Option<ControlRow> = sqlx::query_as(
            "SELECT id, control_id, category, title, description, owner, status,
                    evidence_required, automation, last_attested_at,
                    next_attestation_at, created_at, updated_at
             FROM soc2_controls WHERE control_id = $1",
        )
        .bind(control_id)
        .fetch_optional(&self.db)
        .await
        .map_err(|e| format!("DB error: {e}"))?;
        Ok(row.map(Into::into))
    }

    pub async fn set_status(&self, control_id: &str, status: ControlStatus) -> Result<(), String> {
        sqlx::query(
            "UPDATE soc2_controls SET status = $1, updated_at = NOW() WHERE control_id = $2",
        )
        .bind(status.as_str())
        .bind(control_id)
        .execute(&self.db)
        .await
        .map_err(|e| format!("DB error: {e}"))?;
        Ok(())
    }

    /// Record an evidence item.  Caller computes the canonical payload; the
    /// SHA-256 is computed here from the JSON-serialised payload.
    pub async fn record_evidence(
        &self,
        control_id: &str,
        evidence_type: &str,
        source: &str,
        payload: serde_json::Value,
        period_start: DateTime<Utc>,
        period_end: DateTime<Utc>,
        collected_by: &str,
    ) -> Result<ControlEvidence, String> {
        let id = Uuid::new_v4().to_string();
        let canonical = serde_json::to_string(&payload).map_err(|e| format!("JSON: {e}"))?;
        let mut hasher = Sha256::new();
        hasher.update(canonical.as_bytes());
        let sha256_hash = hex::encode(hasher.finalize());
        let collected_at = Utc::now();

        sqlx::query(
            "INSERT INTO soc2_control_evidence
               (id, control_id, evidence_type, source, payload, sha256_hash,
                storage_url, period_start, period_end, collected_at, collected_by)
             VALUES ($1,$2,$3,$4,$5,$6,NULL,$7,$8,$9,$10)
             ON CONFLICT (control_id, evidence_type, period_start, period_end)
             DO UPDATE SET
               payload = EXCLUDED.payload,
               sha256_hash = EXCLUDED.sha256_hash,
               collected_at = EXCLUDED.collected_at,
               collected_by = EXCLUDED.collected_by",
        )
        .bind(&id)
        .bind(control_id)
        .bind(evidence_type)
        .bind(source)
        .bind(&payload)
        .bind(&sha256_hash)
        .bind(period_start)
        .bind(period_end)
        .bind(collected_at)
        .bind(collected_by)
        .execute(&self.db)
        .await
        .map_err(|e| format!("DB error: {e}"))?;

        // Mark the control as attested and schedule the next attestation.
        sqlx::query(
            "UPDATE soc2_controls
             SET last_attested_at = $1,
                 next_attestation_at = $2,
                 updated_at = $1
             WHERE control_id = $3",
        )
        .bind(collected_at)
        .bind(collected_at + Duration::days(self.attestation_period_days))
        .bind(control_id)
        .execute(&self.db)
        .await
        .map_err(|e| format!("DB error: {e}"))?;

        Ok(ControlEvidence {
            id,
            control_id: control_id.to_string(),
            evidence_type: evidence_type.to_string(),
            source: source.to_string(),
            payload,
            sha256_hash,
            storage_url: None,
            period_start,
            period_end,
            collected_at,
            collected_by: collected_by.to_string(),
        })
    }

    pub async fn list_evidence_for_control(
        &self,
        control_id: &str,
        limit: i64,
    ) -> Result<Vec<ControlEvidence>, String> {
        let rows: Vec<EvidenceRow> = sqlx::query_as(
            "SELECT id, control_id, evidence_type, source, payload, sha256_hash,
                    storage_url, period_start, period_end, collected_at, collected_by
             FROM soc2_control_evidence
             WHERE control_id = $1
             ORDER BY collected_at DESC
             LIMIT $2",
        )
        .bind(control_id)
        .bind(limit)
        .fetch_all(&self.db)
        .await
        .map_err(|e| format!("DB error: {e}"))?;
        Ok(rows.into_iter().map(Into::into).collect())
    }

    /// Run all configured automated collectors over the supplied period.
    /// Logs a row in `soc2_evidence_collection_runs` for each control attempted.
    pub async fn run_automated_collectors(
        &self,
        period_start: DateTime<Utc>,
        period_end: DateTime<Utc>,
    ) -> Result<CollectionRunSummary, String> {
        let started_at = Utc::now();
        let mut summary = CollectionRunSummary {
            started_at,
            finished_at: started_at,
            controls_attempted: 0,
            controls_succeeded: 0,
            controls_failed: 0,
            items_collected: 0,
            failures: Vec::new(),
        };

        let collectors: Vec<Box<dyn EvidenceCollector + Send + Sync>> = vec![
            Box::new(AuditLogEvidenceCollector),
            Box::new(SecretRotationEvidenceCollector),
            Box::new(RiskProfileEvidenceCollector),
            Box::new(ScanResultsEvidenceCollector),
            Box::new(ConsentRecordsEvidenceCollector),
            Box::new(GdprDeletionEvidenceCollector),
        ];

        for collector in collectors {
            summary.controls_attempted += 1;
            let started = Instant::now();
            match collector.collect(&self.db, period_start, period_end).await {
                Ok(item) => {
                    let _ = self
                        .record_evidence(
                            collector.control_id(),
                            collector.evidence_type(),
                            collector.source(),
                            item.payload,
                            period_start,
                            period_end,
                            "automated_collector",
                        )
                        .await
                        .map_err(|e| {
                            warn!(error = %e, control = collector.control_id(), "evidence persist failed");
                            e
                        });
                    summary.controls_succeeded += 1;
                    summary.items_collected += item.items as u32;
                    let _ = sqlx::query(
                        "INSERT INTO soc2_evidence_collection_runs
                           (control_id, evidence_type, run_at, status,
                            items_collected, duration_ms, error)
                         VALUES ($1,$2,$3,'success',$4,$5,NULL)",
                    )
                    .bind(collector.control_id())
                    .bind(collector.evidence_type())
                    .bind(Utc::now())
                    .bind(item.items as i32)
                    .bind(started.elapsed().as_millis() as i32)
                    .execute(&self.db)
                    .await;
                }
                Err(e) => {
                    summary.controls_failed += 1;
                    summary
                        .failures
                        .push(format!("{}: {e}", collector.control_id()));
                    let _ = sqlx::query(
                        "INSERT INTO soc2_evidence_collection_runs
                           (control_id, evidence_type, run_at, status,
                            items_collected, duration_ms, error)
                         VALUES ($1,$2,$3,'failed',0,$4,$5)",
                    )
                    .bind(collector.control_id())
                    .bind(collector.evidence_type())
                    .bind(Utc::now())
                    .bind(started.elapsed().as_millis() as i32)
                    .bind(e)
                    .execute(&self.db)
                    .await;
                }
            }
        }

        summary.finished_at = Utc::now();
        info!(
            attempted = summary.controls_attempted,
            succeeded = summary.controls_succeeded,
            failed = summary.controls_failed,
            items = summary.items_collected,
            "SOC2 evidence collection run finished"
        );
        Ok(summary)
    }
}

// ─── Evidence collectors ───────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct CollectedItem {
    pub payload: serde_json::Value,
    pub items: u64,
}

/// Trait implemented by automated evidence sources.  Each collector is bound
/// to a single (control_id, evidence_type, source) tuple so the resulting
/// evidence row is well-typed.
#[async_trait::async_trait]
pub trait EvidenceCollector {
    fn control_id(&self) -> &'static str;
    fn evidence_type(&self) -> &'static str;
    fn source(&self) -> &'static str;
    async fn collect(
        &self,
        db: &PgPool,
        period_start: DateTime<Utc>,
        period_end: DateTime<Utc>,
    ) -> Result<CollectedItem, String>;
}

pub struct AuditLogEvidenceCollector;

#[async_trait::async_trait]
impl EvidenceCollector for AuditLogEvidenceCollector {
    fn control_id(&self) -> &'static str {
        "CC2.1"
    }
    fn evidence_type(&self) -> &'static str {
        "audit_log_sample"
    }
    fn source(&self) -> &'static str {
        "audit_logs"
    }
    async fn collect(
        &self,
        db: &PgPool,
        period_start: DateTime<Utc>,
        period_end: DateTime<Utc>,
    ) -> Result<CollectedItem, String> {
        let (total,): (i64,) = sqlx::query_as(
            "SELECT COUNT(*) FROM audit_logs WHERE timestamp >= $1 AND timestamp < $2",
        )
        .bind(period_start)
        .bind(period_end)
        .fetch_one(db)
        .await
        .map_err(|e| format!("DB error: {e}"))?;

        let by_action: Vec<(String, i64)> = sqlx::query_as(
            "SELECT action, COUNT(*) FROM audit_logs
             WHERE timestamp >= $1 AND timestamp < $2
             GROUP BY action ORDER BY COUNT(*) DESC LIMIT 25",
        )
        .bind(period_start)
        .bind(period_end)
        .fetch_all(db)
        .await
        .map_err(|e| format!("DB error: {e}"))?;

        let by_outcome: Vec<(String, i64)> = sqlx::query_as(
            "SELECT outcome, COUNT(*) FROM audit_logs
             WHERE timestamp >= $1 AND timestamp < $2
             GROUP BY outcome",
        )
        .bind(period_start)
        .bind(period_end)
        .fetch_all(db)
        .await
        .map_err(|e| format!("DB error: {e}"))?;

        Ok(CollectedItem {
            payload: serde_json::json!({
                "total_entries": total,
                "by_action": by_action,
                "by_outcome": by_outcome,
            }),
            items: total as u64,
        })
    }
}

pub struct SecretRotationEvidenceCollector;

#[async_trait::async_trait]
impl EvidenceCollector for SecretRotationEvidenceCollector {
    fn control_id(&self) -> &'static str {
        "CC6.3"
    }
    fn evidence_type(&self) -> &'static str {
        "secret_rotation_log"
    }
    fn source(&self) -> &'static str {
        "secrets"
    }
    async fn collect(
        &self,
        db: &PgPool,
        period_start: DateTime<Utc>,
        period_end: DateTime<Utc>,
    ) -> Result<CollectedItem, String> {
        let (rotated,): (i64,) = sqlx::query_as(
            "SELECT COUNT(*) FROM secrets
             WHERE last_rotated_at IS NOT NULL
               AND last_rotated_at >= $1 AND last_rotated_at < $2",
        )
        .bind(period_start)
        .bind(period_end)
        .fetch_one(db)
        .await
        .map_err(|e| format!("DB error: {e}"))?;
        let (overdue,): (i64,) = sqlx::query_as(
            "SELECT COUNT(*) FROM secrets
             WHERE next_rotation_at IS NOT NULL AND next_rotation_at < NOW()",
        )
        .fetch_one(db)
        .await
        .map_err(|e| format!("DB error: {e}"))?;
        let (total,): (i64,) = sqlx::query_as("SELECT COUNT(*) FROM secrets")
            .fetch_one(db)
            .await
            .map_err(|e| format!("DB error: {e}"))?;
        Ok(CollectedItem {
            payload: serde_json::json!({
                "total_secrets": total,
                "rotated_in_period": rotated,
                "overdue_for_rotation": overdue,
            }),
            items: rotated as u64,
        })
    }
}

pub struct RiskProfileEvidenceCollector;

#[async_trait::async_trait]
impl EvidenceCollector for RiskProfileEvidenceCollector {
    fn control_id(&self) -> &'static str {
        "CC3.2"
    }
    fn evidence_type(&self) -> &'static str {
        "risk_profile_snapshot"
    }
    fn source(&self) -> &'static str {
        "risk_profiles"
    }
    async fn collect(
        &self,
        db: &PgPool,
        _period_start: DateTime<Utc>,
        _period_end: DateTime<Utc>,
    ) -> Result<CollectedItem, String> {
        let by_level: Vec<(String, i64)> =
            sqlx::query_as("SELECT risk_level, COUNT(*) FROM risk_profiles GROUP BY risk_level")
                .fetch_all(db)
                .await
                .map_err(|e| format!("DB error: {e}"))?;
        let (avg,): (Option<f64>,) = sqlx::query_as("SELECT AVG(risk_score) FROM risk_profiles")
            .fetch_one(db)
            .await
            .map_err(|e| format!("DB error: {e}"))?;
        let total: i64 = by_level.iter().map(|(_, c)| *c).sum();
        Ok(CollectedItem {
            payload: serde_json::json!({
                "total_profiles": total,
                "by_level": by_level,
                "avg_score": avg,
            }),
            items: total as u64,
        })
    }
}

pub struct ScanResultsEvidenceCollector;

#[async_trait::async_trait]
impl EvidenceCollector for ScanResultsEvidenceCollector {
    fn control_id(&self) -> &'static str {
        "CC6.8"
    }
    fn evidence_type(&self) -> &'static str {
        "scan_results_summary"
    }
    fn source(&self) -> &'static str {
        "scan_results"
    }
    async fn collect(
        &self,
        db: &PgPool,
        period_start: DateTime<Utc>,
        period_end: DateTime<Utc>,
    ) -> Result<CollectedItem, String> {
        let (total, spam, phishing): (i64, i64, i64) = sqlx::query_as(
            "SELECT COUNT(*),
                    SUM(CASE WHEN spam_detected THEN 1 ELSE 0 END),
                    SUM(CASE WHEN phishing_detected THEN 1 ELSE 0 END)
             FROM scan_results
             WHERE scanned_at >= $1 AND scanned_at < $2",
        )
        .bind(period_start)
        .bind(period_end)
        .fetch_one(db)
        .await
        .map_err(|e| format!("DB error: {e}"))?;
        let by_verdict: Vec<(String, i64)> = sqlx::query_as(
            "SELECT overall_verdict, COUNT(*) FROM scan_results
             WHERE scanned_at >= $1 AND scanned_at < $2
             GROUP BY overall_verdict",
        )
        .bind(period_start)
        .bind(period_end)
        .fetch_all(db)
        .await
        .map_err(|e| format!("DB error: {e}"))?;
        Ok(CollectedItem {
            payload: serde_json::json!({
                "total_scans": total,
                "spam_detected": spam,
                "phishing_detected": phishing,
                "by_verdict": by_verdict,
            }),
            items: total as u64,
        })
    }
}

pub struct ConsentRecordsEvidenceCollector;

#[async_trait::async_trait]
impl EvidenceCollector for ConsentRecordsEvidenceCollector {
    fn control_id(&self) -> &'static str {
        "P2.1"
    }
    fn evidence_type(&self) -> &'static str {
        "consent_records_summary"
    }
    fn source(&self) -> &'static str {
        "consent_records"
    }
    async fn collect(
        &self,
        db: &PgPool,
        _period_start: DateTime<Utc>,
        _period_end: DateTime<Utc>,
    ) -> Result<CollectedItem, String> {
        let (total, granted, revoked): (i64, i64, i64) = sqlx::query_as(
            "SELECT COUNT(*),
                    SUM(CASE WHEN granted THEN 1 ELSE 0 END),
                    SUM(CASE WHEN revoked_at IS NOT NULL THEN 1 ELSE 0 END)
             FROM consent_records",
        )
        .fetch_one(db)
        .await
        .map_err(|e| format!("DB error: {e}"))?;
        Ok(CollectedItem {
            payload: serde_json::json!({
                "total_consent_records": total,
                "granted": granted,
                "revoked": revoked,
            }),
            items: total as u64,
        })
    }
}

pub struct GdprDeletionEvidenceCollector;

#[async_trait::async_trait]
impl EvidenceCollector for GdprDeletionEvidenceCollector {
    fn control_id(&self) -> &'static str {
        "C1.2"
    }
    fn evidence_type(&self) -> &'static str {
        "gdpr_deletion_log"
    }
    fn source(&self) -> &'static str {
        "data_subject_requests"
    }
    async fn collect(
        &self,
        db: &PgPool,
        period_start: DateTime<Utc>,
        period_end: DateTime<Utc>,
    ) -> Result<CollectedItem, String> {
        let by_type: Vec<(String, String, i64)> = sqlx::query_as(
            "SELECT request_type, status, COUNT(*) FROM data_subject_requests
             WHERE requested_at >= $1 AND requested_at < $2
             GROUP BY request_type, status",
        )
        .bind(period_start)
        .bind(period_end)
        .fetch_all(db)
        .await
        .map_err(|e| format!("DB error: {e}"))?;
        let total: i64 = by_type.iter().map(|(_, _, c)| *c).sum();
        Ok(CollectedItem {
            payload: serde_json::json!({
                "total_requests": total,
                "by_type_status": by_type,
            }),
            items: total as u64,
        })
    }
}

// ─── DB row mapping ────────────────────────────────────────────────────────

#[derive(sqlx::FromRow)]
struct ControlRow {
    id: String,
    control_id: String,
    category: String,
    title: String,
    description: String,
    owner: String,
    status: String,
    evidence_required: serde_json::Value,
    automation: String,
    last_attested_at: Option<DateTime<Utc>>,
    next_attestation_at: Option<DateTime<Utc>>,
    created_at: DateTime<Utc>,
    updated_at: DateTime<Utc>,
}

impl From<ControlRow> for Control {
    fn from(r: ControlRow) -> Self {
        Self {
            id: r.id,
            control_id: r.control_id,
            category: r.category,
            title: r.title,
            description: r.description,
            owner: r.owner,
            status: r.status,
            evidence_required: r.evidence_required,
            automation: r.automation,
            last_attested_at: r.last_attested_at,
            next_attestation_at: r.next_attestation_at,
            created_at: r.created_at,
            updated_at: r.updated_at,
        }
    }
}

#[derive(sqlx::FromRow)]
struct EvidenceRow {
    id: String,
    control_id: String,
    evidence_type: String,
    source: String,
    payload: serde_json::Value,
    sha256_hash: String,
    storage_url: Option<String>,
    period_start: DateTime<Utc>,
    period_end: DateTime<Utc>,
    collected_at: DateTime<Utc>,
    collected_by: String,
}

impl From<EvidenceRow> for ControlEvidence {
    fn from(r: EvidenceRow) -> Self {
        Self {
            id: r.id,
            control_id: r.control_id,
            evidence_type: r.evidence_type,
            source: r.source,
            payload: r.payload,
            sha256_hash: r.sha256_hash,
            storage_url: r.storage_url,
            period_start: r.period_start,
            period_end: r.period_end,
            collected_at: r.collected_at,
            collected_by: r.collected_by,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_catalog_is_well_formed() {
        let mut control_ids = std::collections::HashSet::new();
        for c in DEFAULT_CONTROLS {
            assert!(!c.control_id.is_empty(), "control_id must be non-empty");
            assert!(
                control_ids.insert(c.control_id),
                "duplicate {}",
                c.control_id
            );
            assert!(
                !c.title.is_empty(),
                "title must be non-empty for {}",
                c.control_id
            );
            assert!(
                !c.description.is_empty(),
                "description must be non-empty for {}",
                c.control_id
            );
            assert!(
                !c.owner.is_empty(),
                "owner must be non-empty for {}",
                c.control_id
            );
            assert!(
                !c.evidence_required.is_empty(),
                "evidence_required must be non-empty for {}",
                c.control_id
            );
        }
        // Sanity:we attest to enough Common Criteria controls to be a real SOC 2.
        let cc_count = DEFAULT_CONTROLS
            .iter()
            .filter(|c| c.control_id.starts_with("CC"))
            .count();
        assert!(cc_count >= 18, "expected ≥18 CC controls, got {cc_count}");
    }

    #[test]
    fn automation_levels_serialize() {
        assert_eq!(AutomationLevel::Manual.as_str(), "manual");
        assert_eq!(AutomationLevel::Automated.as_str(), "automated");
        assert_eq!(AutomationLevel::Hybrid.as_str(), "hybrid");
    }

    #[test]
    fn control_status_serializes() {
        assert_eq!(ControlStatus::InScope.as_str(), "in_scope");
        assert_eq!(ControlStatus::NotApplicable.as_str(), "not_applicable");
        assert_eq!(ControlStatus::Deferred.as_str(), "deferred");
    }
}
