<?php

declare(strict_types=1);

namespace KiwiCaptcha;

/**
 * Optional storage capability: the resultless consumed-operation resume
 * can claim the re-derivation ownership under a short lease, so exactly
 * one concurrent same-operation recovery performs the expensive
 * derivation while the losers re-read and resolve the winner's committed
 * outcome. Not part of {@see StorageInterface}: third-party adapters
 * are not required to implement it. A verifier over a storage
 * without this capability resumes exactly like the legacy path: every
 * concurrent recovery derives, security is unaffected, and only the
 * duplicate CPU/memory expenditure is not deduplicated.
 *
 * Why the claim exists: `Verifier::resumeConsumedOperation()` re-derives
 * the deterministic proof of a consumed-resultless record (the crash
 * window between the pending->consumed transition and the result
 * commit). Two concurrent same-operation recoveries are the same
 * logical operation and would commit the same outcome either way, so
 * correctness does not depend on the claim. The claim exists to make
 * exactly one of them derive: the winner claims the nonce under
 * `resume-claim:<nonce>` with a random owner token and a short TTL.
 * The losers observe the claim and re-read the retained state,
 * resolving the winner's committed outcome when it has landed, or the
 * retryable ConsumeIndeterminate while it has not. Security semantics
 * are identical to the unclaimed path.
 *
 * Contract, mirroring the Rust production verifier
 * (`RedisChallengeStore::claim_resume_derivation`,
 * `release_resume_derivation`,
 * `commit_result_clearing_claim`):
 *
 *  - TTL: the claim expires 60 seconds after it is taken (the Rust
 *    `CLAIM_TTL_SECS`). A crashed recovery leaves only this short lease
 *    before a later retry may claim again; a 60s poison marker would
 *    block resultless recovery for its full TTL even when nothing is
 *    running.
 *  - Ownership: the claim stores a random owner token generated by the
 *    storage (16 random bytes, hex-encoded), never a repeatable process
 *    identifier. Only that token may release the claim or commit through
 *    it; a stale owner whose claim expired mid-derivation can never
 *    delete or commit past a newer recovery's claim.
 *  - Atomicity: `claimResumeDerivation()` fuses the claim with the
 *    claimability check (the record must be consumed and resultless).
 *    `releaseResumeDerivation()` is a compare-and-delete, and
 *    `commitResultResume()` fuses the result write with the claim clear
 *    in one atomic transition. A concurrent commit can never leave a
 *    stale claim behind, and a stale owner can never clear a newer
 *    recovery's claim.
 *  - Claimability: a claim is refused (null) for a missing, pending,
 *    committed (result already stored) or cancelled record, exactly the
 *    records the resume path would never derive for.
 *
 * The verifier releases the claim on every early return after
 * acquisition (expiry, derivation failure, storage failure) via
 * {@see self::releaseResumeDerivation()} and clears it with the commit
 * via {@see self::commitResultResume()}.
 */
interface ResumeDerivationClaimInterface
{
    /**
     * Atomically claim the re-derivation ownership of a consumed,
     * resultless record: exactly one concurrent same-operation recovery
     * may derive and commit; the losers re-read and resolve the winner's
     * committed outcome.
     *
     * Returns a fresh random owner token when this caller won the claim:
     * the record is consumed, carries no committed result yet, and no
     * claim is currently held. Returns null when the claim is refused:
     * the record is missing, not consumed, already has a committed
     * result, is cancelled, or another recovery currently holds the
     * claim.
     *
     * The claim is recorded in the same atomic-transition style as the
     * storage's other state transitions (a Redis backend fuses the
     * claimability check and the SET NX in one Lua script) and carries
     * the same 60-second TTL as the Rust side. A storage failure throws
     * (fail closed: the caller must never fall back to an unsynchronized
     * derive storm because the claim could not be established).
     *
     * @throws \Throwable on a storage failure
     */
    public function claimResumeDerivation(string $nonce): ?string;

    /**
     * Compare-and-delete release of the resume claim: deletes the claim
     * only when it still holds exactly this owner token. Returns true
     * when the release deleted the claim, false when the claim is
     * missing or owned by a different token (a stale owner after a
     * crash and TTL expiry can never delete a newer recovery's claim).
     *
     * The verifier calls this on every early return after a successful
     * claim (expiry, derivation failure, storage failure). A release
     * that returns false is harmless: the claim was already gone
     * (cleared by this owner's own commit, expired, or re-owned), and a
     * moved owner is never touched.
     *
     * @throws \Throwable on a storage failure
     */
    public function releaseResumeDerivation(string $nonce, string $owner): bool;

    /**
     * The resume-path result commit that clears the re-derivation claim
     * atomically with the result write: the same one-shot semantics as
     * {@see StorageInterface::commitResult()} (only a consumed,
     * resultless record is written), with the claim as a fencing
     * precondition. The caller must still hold the claim (the stored
     * claim equals this owner token) before the protected mutation is
     * written. A stale owner whose claim expired mid-derivation can
     * never commit. The successful write clears the claim in the same
     * atomic transition.
     *
     * Returns true when the result was stored and the claim cleared.
     * Returns false when the commit was refused: the record is missing,
     * not consumed, already has a result, or this caller no longer
     * holds the claim (ownership lost to a newer recovery, or the claim
     * expired). A refused commit performs no write; the caller re-reads
     * the retained state and resolves the winner's committed outcome, or
     * reports ConsumeIndeterminate while the record stays resultless.
     *
     * The verified replica-wait barrier of the plain commit applies to
     * the fresh mutation exactly as on the unclaimed path.
     *
     * @throws \Throwable on a storage failure
     */
    public function commitResultResume(string $nonce, bool $valid, ?string $binding, string $owner): bool;
}
