//! ExecutionChallengeV1 cross-language parity and verify-path tests.
//!
//! The pinned vectors in [`php_vectors`] are generated by the PHP core
//! (`KiwiCaptcha\ExecutionChallengeGenerator` with the fixed key
//! `0123456789abcdef0123456789abcdef`) — the Rust mirror must reproduce
//! the identical program blob, executed trace and executed-trace
//! digest, so a PHP-issued program verifies byte-identically in Rust
//! (and vice versa: the PHP core pins the Rust-generated vectors in
//! `tests/ExecutionChallengeTest.php`).

use base64::engine::general_purpose::STANDARD as B64;
use base64::Engine;
use kiwicaptcha::challenge::{issue_challenge_with_execution, ChallengeConfig, PoWAlgorithm};
use kiwicaptcha::execution;
use kiwicaptcha::verify::{VerifyContext, VerifyError, VerifyOutcome};

const KEY: &[u8] = b"0123456789abcdef0123456789abcdef";
const NONCE: &str = "xAfSYcl6VyvtYZcQUhvXxin2pojnG5TmZoHg7K6NG3s=";

/// PHP-generated vectors (pinned): program blob + executed-trace
/// digest for the fixed context (nonce, scope "login", action
/// "login-action", version 1). The digest is the V2 evidence digest
/// over the browser-equivalent executed trace of the program, the
/// trace a real browser execution submits. It is computed as
/// `digestOverTrace` over the trace built by `executedTraceFor` on
/// the decoded program, and re-derived here over the same trace.
/// `PROGRAM2` is a pinned legacy/foreign blob stamped with op-version
/// 2, generated by the prior PHP generator. The strict parser must
/// now reject it (the op version is exactly 1, no arbitrary byte).
mod php_vectors {
    pub const PROGRAM: &str = "AQVsb2dpbgxsb2dpbi1hY3Rpb24BFhA4D3JWcHNlVHl2TVR4TG1zKxcJVXJYczFGMllaEggUIQ9yVnBzZVR5dk1UeExtcysKCgoLYB8PclZwc2VUeXZNVHhMbXMrHw9yVnBzZVR5dk1UeExtcysaEOoOQzlzSkI0dnRXTGNEWFYI2Afyoq4QE7qNKBsSC7AZEFAPMVdiRXN3L1hhbEpHUlJQCbeTGhDgEGRTSGsyNEZBbDNXYjg1QzMUJA==";
    pub const DIGEST: &str = "595d6df929e025c559ac3393c3a006283574d33f366dbdb70501ae88f177a1b9";
    pub const PROGRAM2: &str = "AQZzaWdudXAMb3RoZXItYWN0aW9uAhEbDQU9Kz9aT2oLChUKMWBaIlI8eH43dxhFX01bT2p2UTB6YnYuPypzOlc7JGggQyQH3myJ1jKtuN0AJkSWMiV1QQcDUQB6iaivOGAGMJx6PF+rcsEYAnc3DgUsTVF5cowVCDBCdWFRPFV7GHBGakt5TF9sV1AhMCFeV3ZLIyAjclA7TxANDXdFdDNjbEhlMG1pT0QLugbjlCV9QN7z/g8BKZmkB/pZHone1eUUEwR5bEtJ";
}

#[test]
fn rust_mirror_reproduces_php_generated_program() {
    let program = execution::generate(KEY, NONCE, "login", "login-action", 1).unwrap();
    assert_eq!(
        program,
        php_vectors::PROGRAM,
        "the Rust generator must reproduce the PHP program byte-for-byte"
    );
    // The pinned digest binds the browser-equivalent executed trace
    // (the V2 evidence path): recomputed here the same way the PHP
    // reference computed it, over the executed trace of the program.
    let decoded = execution::decode(&program).expect("the pinned program must parse");
    let trace = execution::executed_trace_for(&decoded);
    assert_eq!(
        execution::expected_digest_over_trace(&program, NONCE, &trace).unwrap(),
        php_vectors::DIGEST,
        "the Rust executed-trace digest must reproduce the PHP digest"
    );
}

#[test]
fn generation_refuses_a_noncanonical_version_byte() {
    // The version argument during generation is the canonical numeric
    // byte, exactly 1: a different byte is refused before any program is
    // minted (the strict parser would reject the blob anyway, so
    // issuance never produces an unparseable program).
    assert_eq!(
        execution::generate(KEY, NONCE, "signup", "other-action", 2),
        Err(execution::GenerateError::InvalidVersion)
    );
    assert_eq!(
        execution::generate(KEY, NONCE, "signup", "other-action", 0),
        Err(execution::GenerateError::InvalidVersion)
    );
}

#[test]
fn strict_parser_rejects_the_legacy_op_version_two_blob() {
    // The pinned prior-generation blob stamped with op-version 2 is now a
    // foreign blob: the op version must be exactly 1 (no arbitrary
    // byte), so it fails the parser and the digest computation.
    assert!(execution::decode(php_vectors::PROGRAM2).is_none());
    assert!(!execution::is_valid_program(php_vectors::PROGRAM2));
    assert!(execution::expected_digest(php_vectors::PROGRAM2, NONCE).is_none());
}

#[test]
fn rust_decodes_and_traces_php_program() {
    let program = execution::decode(php_vectors::PROGRAM).expect("the PHP program must parse");
    assert_eq!(program.scope, "login");
    assert_eq!(program.action, "login-action");
    assert_eq!(program.op_version, 1);
    assert!(!execution::canonical_trace(&program).is_empty());
}

fn config() -> ChallengeConfig {
    ChallengeConfig {
        secret_key: String::from_utf8_lossy(KEY).into_owned(),
        algorithm: PoWAlgorithm::Sha256,
        m_kib: 0,
        t: 1,
        p: 1,
        target_bits: 8,
        argon2_target_bits: 8,
        ttl_secs: 120,
        min_duration_ms: Some(0),
        auto_tune: false,
        auto_tune_min_bits: 8,
        auto_tune_max_bits: 20,
        binding_mode: kiwicaptcha::challenge::BindingMode::Bound,
        policy_version: 1,
        region: None,
        issuer: None,
        kid: 1,
        execution_key: Some(String::from_utf8_lossy(KEY).into_owned()),
    }
}

fn solve_counter(prefix: &str, salt: &str, target_bits: u32) -> u64 {
    use sha2::{Digest, Sha256};
    let salt_bytes = B64.decode(salt).unwrap();
    for counter in 0..1_000_000u64 {
        let mut input = Vec::new();
        input.extend_from_slice(prefix.as_bytes());
        input.extend_from_slice(counter.to_string().as_bytes());
        input.extend_from_slice(&salt_bytes);
        let hash = Sha256::digest(&input);
        let zeros = hash.iter().take_while(|b| **b == 0).count() * 8 + {
            let first = hash.iter().find(|b| **b != 0);
            match first {
                None => 0,
                Some(b) => {
                    let mut n = 0;
                    let mut v = *b;
                    while v & 0x80 == 0 {
                        n += 1;
                        v <<= 1;
                    }
                    n
                }
            }
        };
        if zeros >= target_bits as usize {
            return counter;
        }
    }
    panic!("no winning counter found");
}

#[test]
fn armed_issuance_verifies_with_correct_digest() {
    let now = 1_700_000_000u64;
    let now_ns = 1_700_000_000_000_000u64;
    let issued = issue_challenge_with_execution(
        &config(),
        "login",
        "203.0.113.7",
        now,
        now_ns,
        0,
        None,
        true,
        Some("login-action"),
        Some(1),
        false,
    )
    .expect("armed issuance");
    let program = issued.challenge.execution_program.as_ref().expect("armed");
    let counter = solve_counter(&issued.record.prefix, &issued.record.salt, 8);

    let mut record = issued.record;
    let decoded = execution::decode(program).expect("the issued program must parse");
    let trace = execution::executed_trace_for(&decoded);
    let trace_b64: String = B64
        .encode(trace.as_bytes())
        .replace('+', "-")
        .replace('/', "_")
        .trim_end_matches('=')
        .to_string();
    let digest = execution::expected_digest_over_trace(program, &record.nonce, &trace).unwrap();
    let mut ctx = VerifyContext {
        record: &mut record,
        secret_key: std::str::from_utf8(KEY).unwrap(),
        secrets_by_kid: None,
        revoked_kids: None,
        counter,
        duration_ms: 5000,
        now_unix: Some(&mut || now + 1),
        now_ns: now_ns + 5_000_000,
        min_duration_ms: 0,
        expected_scope: Some("login"),
        expected_request_binding: kiwicaptcha::verify::RequestBindingExpectation::Unenforced,
        expected_region: None,
        expected_issuer: None,
        expected_policy_version: None,
        client_ip: Some("203.0.113.7"),
        execution_digest: Some(&digest),
        execution_trace: Some(&trace_b64),
        telemetry: None,
        enforce_telemetry: false,
        accept_legacy_v1: false,
        max_attempts: 0,
    };
    assert!(matches!(
        kiwicaptcha::verify::verify_solution(&mut ctx),
        VerifyOutcome::Valid { .. }
    ));
}

#[test]
fn armed_record_without_digest_is_execution_mismatch() {
    let now = 1_700_000_000u64;
    let now_ns = 1_700_000_000_000_000u64;
    let issued = issue_challenge_with_execution(
        &config(),
        "login",
        "203.0.113.7",
        now,
        now_ns,
        0,
        None,
        true,
        Some("login-action"),
        Some(1),
        false,
    )
    .unwrap();
    let counter = solve_counter(&issued.record.prefix, &issued.record.salt, 8);

    let mut record = issued.record;
    let mut ctx = VerifyContext {
        record: &mut record,
        secret_key: std::str::from_utf8(KEY).unwrap(),
        secrets_by_kid: None,
        revoked_kids: None,
        counter,
        duration_ms: 5000,
        now_unix: Some(&mut || now + 1),
        now_ns: now_ns + 5_000_000,
        min_duration_ms: 0,
        expected_scope: Some("login"),
        expected_request_binding: kiwicaptcha::verify::RequestBindingExpectation::Unenforced,
        expected_region: None,
        expected_issuer: None,
        expected_policy_version: None,
        client_ip: Some("203.0.113.7"),
        execution_digest: None,
        execution_trace: None,
        telemetry: None,
        enforce_telemetry: false,
        accept_legacy_v1: false,
        max_attempts: 0,
    };
    assert_eq!(
        kiwicaptcha::verify::verify_solution(&mut ctx),
        VerifyOutcome::Invalid(VerifyError::ExecutionMismatch)
    );
}

#[test]
fn wrong_digest_and_digest_from_another_challenge_are_execution_mismatch() {
    let now = 1_700_000_000u64;
    let now_ns = 1_700_000_000_000_000u64;
    let issued_a = issue_challenge_with_execution(
        &config(),
        "login",
        "203.0.113.7",
        now,
        now_ns,
        0,
        None,
        true,
        Some("login-action"),
        Some(1),
        false,
    )
    .unwrap();
    let issued_b = issue_challenge_with_execution(
        &config(),
        "login",
        "203.0.113.7",
        now,
        now_ns,
        0,
        None,
        true,
        Some("login-action"),
        Some(1),
        false,
    )
    .unwrap();
    assert_ne!(issued_a.record.nonce, issued_b.record.nonce);

    let wrong = "0".repeat(64);
    let digest_b = execution::expected_digest(
        issued_b.challenge.execution_program.as_ref().unwrap(),
        &issued_b.record.nonce,
    )
    .unwrap();
    let counter = solve_counter(&issued_a.record.prefix, &issued_a.record.salt, 8);

    for presented in [wrong.as_str(), digest_b.as_str()] {
        let mut record = issued_a.record.clone();
        let mut ctx = VerifyContext {
            record: &mut record,
            secret_key: std::str::from_utf8(KEY).unwrap(),
            secrets_by_kid: None,
            revoked_kids: None,
            counter,
            duration_ms: 5000,
            now_unix: Some(&mut || now + 1),
            now_ns: now_ns + 5_000_000,
            min_duration_ms: 0,
            expected_scope: Some("login"),
            expected_request_binding: kiwicaptcha::verify::RequestBindingExpectation::Unenforced,
            expected_region: None,
            expected_issuer: None,
            expected_policy_version: None,
            client_ip: Some("203.0.113.7"),
            execution_digest: Some(presented),
            execution_trace: None,
            telemetry: None,
            enforce_telemetry: false,
            accept_legacy_v1: false,
            max_attempts: 0,
        };
        assert_eq!(
            kiwicaptcha::verify::verify_solution(&mut ctx),
            VerifyOutcome::Invalid(VerifyError::ExecutionMismatch)
        );
    }
}

#[test]
fn arming_without_execution_key_refuses() {
    let mut cfg = config();
    cfg.execution_key = None;
    let err = issue_challenge_with_execution(
        &cfg,
        "login",
        "203.0.113.7",
        1_700_000_000,
        1_700_000_000_000_000,
        0,
        None,
        true,
        Some("login-action"),
        Some(1),
        false,
    )
    .unwrap_err();
    assert!(matches!(
        err,
        kiwicaptcha::challenge::SignError::ExecutionKeyNotConfigured
    ));
}

#[test]
fn unarmed_issuance_rejects_a_stray_digest() {
    let now = 1_700_000_000u64;
    let now_ns = 1_700_000_000_000_000u64;
    let issued = issue_challenge_with_execution(
        &config(),
        "login",
        "203.0.113.7",
        now,
        now_ns,
        0,
        None,
        false,
        None,
        None,
        false,
    )
    .unwrap();
    assert!(issued.challenge.execution_program.is_none());
    assert!(issued.record.execution_program.is_none());
    assert!(issued.record.execution_commitment.is_none());
    assert!(issued.record.execution_version.is_none());

    let counter = solve_counter(&issued.record.prefix, &issued.record.salt, 8);
    let mut record = issued.record;
    let mut ctx = VerifyContext {
        record: &mut record,
        secret_key: std::str::from_utf8(KEY).unwrap(),
        secrets_by_kid: None,
        revoked_kids: None,
        counter,
        duration_ms: 5000,
        now_unix: Some(&mut || now + 1),
        now_ns: now_ns + 5_000_000,
        min_duration_ms: 0,
        expected_scope: Some("login"),
        expected_request_binding: kiwicaptcha::verify::RequestBindingExpectation::Unenforced,
        expected_region: None,
        expected_issuer: None,
        expected_policy_version: None,
        client_ip: Some("203.0.113.7"),
        // Stray execution evidence: a digest presented for a record
        // whose signed canonical carries NO commitment is deterministic
        // invalid, never silently ignored.
        execution_digest: Some(&"a".repeat(64)),
        execution_trace: None,
        telemetry: None,
        enforce_telemetry: false,
        accept_legacy_v1: false,
        max_attempts: 0,
    };
    assert_eq!(
        kiwicaptcha::verify::verify_solution(&mut ctx),
        VerifyOutcome::Invalid(VerifyError::ExecutionMismatch)
    );
}
