//! ExecutionChallengeV1 cross-language parity and verify-path tests.
//!
//! The pinned vectors in [`php_vectors`] are generated by the PHP core
//! (`KiwiCaptcha\ExecutionChallengeGenerator` with the fixed key
//! `0123456789abcdef0123456789abcdef`) — the Rust mirror must reproduce
//! the identical program blob, executed trace and executed-trace
//! digest, so a PHP-issued program verifies byte-identically in Rust
//! (and vice versa: the PHP core pins the Rust-generated vectors in
//! `tests/ExecutionChallengeTest.php`).

use base64::engine::general_purpose::STANDARD as B64;
use base64::Engine;
use kiwicaptcha::challenge::{issue_challenge_with_execution, ChallengeConfig, PoWAlgorithm};
use kiwicaptcha::execution;
use kiwicaptcha::verify::{VerifyContext, VerifyError, VerifyOutcome};

const KEY: &[u8] = b"0123456789abcdef0123456789abcdef";
const NONCE: &str = "xAfSYcl6VyvtYZcQUhvXxin2pojnG5TmZoHg7K6NG3s=";

/// PHP-generated vectors (pinned): program blob + executed-trace
/// digest for the fixed context (nonce, scope "login", action
/// "login-action"). The digest is the executed-trace evidence digest
/// over the browser-equivalent executed trace of the program, the
/// trace a real browser execution submits. It is computed as
/// `digestOverTrace` over the trace built by the PHP test-fixture
/// `KiwiCaptcha\Tests\Support\ExecutionTraceFixture::executedTraceFor` on
/// the decoded program, and re-derived here over the same trace.
/// `PROGRAM`/`DIGEST` pin the version-2 pair (the causal observe
/// grammar, opcode 33); `PROGRAM_V1`/`DIGEST_V1` pin the version-1
/// pair (the legacy construction-to-probe grammar with no observe
/// opcode) — the N-1 vectors an old interpreter and an old verifier
/// must still accept.
mod php_vectors {
    pub const PROGRAM: &str = "AQVsb2dpbgxsb2dpbi1hY3Rpb24CEhCNDFFpRjBZNTJyeGlsLxcJVHpOaWpvNHppEgjXIQxRaUYwWTUycnhpbC8YChgJDHIfDFFpRjBZNTJyeGlsLxwMUWlGMFk1MnJ4aWwvFHUZFgg/Y1l2KUZwWgjBAHQ4GXzGbcEkCxYEK3K7YCU/jIESBS5wXzlYoYg7";
    pub const DIGEST: &str = "afb559b7ba2e8d4f2b7d04a5360e63b4e16c183f0dae9ba8f9292b7988a18566";

    /// The pinned execution-version-1 program (no observe opcode, the
    /// construction-to-probe skeleton): the N-1 compatibility vector an
    /// old interpreter and an old verifier must still accept.
    /// The pinned execution-version-3 program (the sibling-index
    /// traversal grammar with two constructed nodes): the N-1-fence
    /// vector for the newest generation.
    pub const PROGRAM_V3: &str = "AQVsb2dpbgxsb2dpbi1hY3Rpb24DFBDBDnVPWlRTamU1a2ltTk9vFwU4QWF1TBIQkQ9YeWJUOTdpQXI4bWEvN3AVDHh6MnJmcWNqZzFqcgNXcyUSCNIhDnVPWlRTamU1a2ltTk9vIAogCebGHQ51T1pUU2plNWtpbU5PbyIPWHliVDk3aUFyOG1hLzdwIBwOdU9aVFNqZTVraW1OT28YCFRuRHZOUG9sFQZ4bWg3Nm4XKVghWD44OXY9K1s1bH0wUjtOX1AkQl8AZCz2ep3N8tYJAYwTC1Q3R0h3dEcxYUV0EVMRM1k+UyJVXWgkPDFaWDdbe0s=";
    pub const PROGRAM_V4: &str = "AQVsb2dpbgxsb2dpbi1hY3Rpb24EExCjDWxzM0JqblJlVG92Rk4VBHh6b2EcR0EvalpQVmZWSi9DZUsoYVlvPUIzJnNbaUBZYhIQuQdXTXZ2SXZXEfUDPHdLEiPWDGhKMTlmOGtDeW9keCN8B2JHT0NtU1IIYCENbHMzQmpuUmVUb3ZGThMKEwlW3B8NbHMzQmpuUmVUb3ZGTiIHV012dkl2VyQHYkdPQ21TUh8NbHMzQmpuUmVUb3ZGTiAgAHgKyiaEMcDn";
    pub const DIGEST_V4: &str = "0961591245fcd407aebd70bf125bf61c11c74519e0cfa31fe8cb9797b969a143";
    /// The pinned version-5 pair (the causal object-graph grammar): the
    /// program generated by the PHP core for the fixed context, the
    /// digest over the browser-equivalent executed trace of it.
    pub const PROGRAM_V5: &str = "AQVsb2dpbgxsb2dpbi1hY3Rpb24FGBCuB1JVL0ZoMlEVA3h5ZRhbcHReK0AkOTwwKmRPdFkvaE4jTld6WVcSEDIHWkdpZEZ5UxEIED5kPzI2QkFwYGpCUXkqVkESI7kFSWxlZlojLgVHeUV3aQjHIQdSVS9GaDJRAAoACW4GHwdSVS9GaDJRIgdaR2lkRnlTJAVHeUV3aSYEeHorTxQnB1pHaWRGeVMOCg4qKxoiMGhZRTBFSCMoJS9qdVQ0T1Aie2FjPllULAwgIB4YAAQwO2IhdS8Ddg==";
    pub const DIGEST_V5: &str = "31eb00bbd3b5e29d28eccabb6d337739a9d13c5077e869062a3d05920e18dc04";
    pub const TRACE_V5: &str = "dcreate(UlUvRmgyUQ==);dset(eHll);dappend(1);dcreate(WkdpZEZ5Uw==);dattr(dGl0bGU=);dappend(1);dchild(SWxlZlo=);dchild(R3lFd2k=);u8c(0);obs(0,10);u8r(10);u8w(10);evreal(kiwi-ev:span);dsib(2);ddepth(2);dclone(1);drepar(2);u8r(2);durlc(e76cac2dfcc313d58bb0f731c433badf0651978a1769007ff3c1ab62cf59fee7);dmutate(26);sreal(9b5d5921b44c155a1158e759306b670558b30865e11e604bbd721f255c3e6c0c);sreal(9b5d5921b44c155a1158e759306b670558b30865e11e604bbd721f255c3e6c0c);point(div);and(808124960)";

    pub const DIGEST_V3: &str = "2dda24554c22f43ed405b1e2bea67997e27c849b0d6dbca930c7f2d497e85951";

    pub const PROGRAM_V1: &str = "AQVsb2dpbgxsb2dpbi1hY3Rpb24BFhA4D3JWcHNlVHl2TVR4TG1zKxcJVXJYczFGMllaEh8PclZwc2VUeXZNVHhMbXMrHA9yVnBzZVR5dk1UeExtcysdD3JWcHNlVHl2TVR4TG1zKyAXCzJBcUxDOXNKQjR2BZbLHEPX1bDYB/KirhATuo0oGxILsBkQUA8xV2JFc3cvWGFsSkdSUlAJt5MaEOAQZFNIazI0RkFsM1diODVDMxQkFgVySmkjWQdwo5mMcPosjwLkcZPOX9oyWQ==";
    pub const DIGEST_V1: &str = "1a8bcf129537218346d5e2dc0f636af10d4ea81db0cb9ca91a96cbbd9efc6f64";
}

#[test]
fn rust_mirror_reproduces_the_php_version_four_program() {
    // The pinned version-4 program (the nested-tree grammar) generated
    // by the PHP core: the Rust mirror must reproduce the identical
    // blob and the executed-trace digest.
    let program = execution::generate(KEY, NONCE, "login", "login-action", 4).unwrap();
    assert_eq!(
        program,
        php_vectors::PROGRAM_V4,
        "the Rust generator must reproduce the PHP version-4 program byte-for-byte"
    );
    let decoded = execution::decode(&program).expect("the version-4 program must parse");
    let trace = execution::fixtures::executed_trace_for(&decoded);
    assert!(
        trace.contains("ddepth("),
        "the version-4 grammar carries the nested-tree depth entry"
    );
    assert_eq!(
        execution::expected_digest_over_trace(&program, NONCE, &trace).unwrap(),
        php_vectors::DIGEST_V4,
        "the Rust version-4 executed-trace digest must reproduce the PHP digest"
    );
}

#[test]
fn rust_mirror_reproduces_the_php_version_five_program() {
    // The pinned version-5 program (the causal object-graph grammar)
    // generated by the PHP core: the Rust mirror must reproduce the
    // identical blob, the byte-identical browser-equivalent executed
    // trace and the executed-trace digest.
    let program = execution::generate(KEY, NONCE, "login", "login-action", 5).unwrap();
    assert_eq!(
        program,
        php_vectors::PROGRAM_V5,
        "the Rust generator must reproduce the PHP version-5 program byte-for-byte"
    );
    let decoded = execution::decode(&program).expect("the version-5 program must parse");
    assert_eq!(decoded.op_version, 5);
    let trace = execution::fixtures::executed_trace_for(&decoded);
    assert_eq!(
        trace,
        php_vectors::TRACE_V5,
        "the Rust executed trace must reproduce the PHP fixture trace byte-for-byte"
    );
    assert!(
        trace.contains("dclone(1);drepar(2);u8r(2);durlc("),
        "the version-5 trace carries the clone-reparent spine and the observed URL-canon digest"
    );
    assert_eq!(
        execution::expected_digest_over_trace(&program, NONCE, &trace).unwrap(),
        php_vectors::DIGEST_V5,
        "the Rust version-5 executed-trace digest must reproduce the PHP digest"
    );
    // The URL-canon walker rule: the entry must be 64 lowercase hex
    // digits. An uppercase digest and a short digest are both rejected.
    let upper = trace.replacen("e76cac2d", "E76CAC2D", 1);
    assert!(
        execution::verify_executed_trace(&program, NONCE, &upper).is_none(),
        "an uppercase urlc digest must be rejected"
    );
    let short = trace.replacen(
        "durlc(e76cac2dfcc313d58bb0f731c433badf0651978a1769007ff3c1ab62cf59fee7)",
        "durlc(abc)",
        1,
    );
    assert!(
        execution::verify_executed_trace(&program, NONCE, &short).is_none(),
        "a short urlc digest must be rejected"
    );
}

#[test]
fn rust_mirror_reproduces_the_php_version_three_program() {
    // The pinned version-3 program (the sibling-index traversal
    // grammar) generated by the PHP core: the Rust mirror must
    // reproduce the identical blob and the executed-trace digest.
    let program = execution::generate(KEY, NONCE, "login", "login-action", 3).unwrap();
    assert_eq!(
        program,
        php_vectors::PROGRAM_V3,
        "the Rust generator must reproduce the PHP version-3 program byte-for-byte"
    );
    let decoded = execution::decode(&program).expect("the version-3 program must parse");
    let trace = execution::fixtures::executed_trace_for(&decoded);
    assert!(
        trace.contains("dsib("),
        "the version-3 grammar carries the sibling-index traversal entry"
    );
    assert_eq!(
        execution::expected_digest_over_trace(&program, NONCE, &trace).unwrap(),
        php_vectors::DIGEST_V3,
        "the Rust version-3 executed-trace digest must reproduce the PHP digest"
    );
}

#[test]
fn rust_mirror_reproduces_php_generated_program() {
    // The version-2 pair: the Rust generator (version 2, the causal
    // observe grammar) must reproduce the PHP program byte-for-byte,
    // and the executed-trace digest over the executed trace of the
    // program must reproduce the PHP digest (the V2 evidence path).
    let program = execution::generate(KEY, NONCE, "login", "login-action", 2).unwrap();
    assert_eq!(
        program,
        php_vectors::PROGRAM,
        "the Rust generator must reproduce the PHP program byte-for-byte"
    );
    let decoded = execution::decode(&program).expect("the pinned program must parse");
    assert_eq!(decoded.op_version, 2);
    let trace = execution::fixtures::executed_trace_for(&decoded);
    assert_eq!(
        execution::expected_digest_over_trace(&program, NONCE, &trace).unwrap(),
        php_vectors::DIGEST,
        "the Rust executed-trace digest must reproduce the PHP digest"
    );
}

#[test]
fn rust_mirror_reproduces_the_php_version_one_vector() {
    // The version-1 pair (the N-1 grammar): the Rust generator with
    // version 1 must byte-reproduce the PHP version-1 program
    // constant, and the executed-trace digest over its executed trace
    // must reproduce the version-1 digest — so a PHP-issued version-1
    // challenge verifies byte-identically in Rust (and vice versa).
    let program = execution::generate(KEY, NONCE, "login", "login-action", 1).unwrap();
    assert_eq!(
        program,
        php_vectors::PROGRAM_V1,
        "the Rust version-1 generator must reproduce the PHP program byte-for-byte"
    );
    let decoded = execution::decode(&program).expect("the pinned program must parse");
    assert_eq!(decoded.op_version, 1);
    assert!(
        decoded.ops.iter().all(|op| op.opcode != 33),
        "a version-1 program never carries the observe opcode"
    );
    let trace = execution::fixtures::executed_trace_for(&decoded);
    assert!(
        !trace.contains("obs("),
        "a version-1 executed trace never carries the observe entry"
    );
    assert_eq!(
        execution::expected_digest_over_trace(&program, NONCE, &trace).unwrap(),
        php_vectors::DIGEST_V1,
        "the Rust version-1 executed-trace digest must reproduce the PHP digest"
    );
}

#[test]
fn generation_refuses_a_noncanonical_version_byte() {
    // The version argument during generation is a canonical numeric
    // byte, 1..=MAX_EXECUTION_VERSION: any other byte is refused before
    // any program is minted (the strict parser would reject the blob
    // anyway, so issuance never produces an unparseable program).
    assert_eq!(
        execution::generate(KEY, NONCE, "signup", "other-action", 9),
        Err(execution::GenerateError::InvalidVersion)
    );
    assert_eq!(
        execution::generate(KEY, NONCE, "signup", "other-action", 0),
        Err(execution::GenerateError::InvalidVersion)
    );
    // The canonical bytes generate and stamp their own grammar: the
    // first two rungs are sampled here (1 and 2); the higher rungs are
    // covered by the version-ladder suites.
    for version in [1u8, 2u8] {
        let p = execution::generate(KEY, NONCE, "signup", "other-action", version).unwrap();
        assert_eq!(
            execution::decode(&p).expect("must parse").op_version,
            version
        );
    }
}

#[test]
fn version_bytes_cannot_cross_the_grammar_fence() {
    // The N-1 decode fence on the pinned vectors: the version-2
    // program (which carries the observe opcode 33) with its version
    // byte rewritten to 1 must decode to null, and the version-1
    // program with a crafted opcode-33 op must decode to null too.
    let scope_len = b"login".len();
    let action_len = b"login-action".len();
    let version_at = 3 + scope_len + action_len;
    let op0_at = version_at + 2;

    let mut downgraded = B64
        .decode(php_vectors::PROGRAM)
        .expect("the pinned v2 program must decode as base64");
    assert_eq!(downgraded[version_at], 2);
    assert!(execution::decode(php_vectors::PROGRAM).is_some());
    downgraded[version_at] = 1;
    assert!(
        execution::decode(&B64.encode(downgraded)).is_none(),
        "a version-2 program with opcode 33 must never decode as version 1"
    );

    let mut crafted = B64
        .decode(php_vectors::PROGRAM_V1)
        .expect("the pinned v1 program must decode as base64");
    assert_eq!(crafted[version_at], 1);
    assert_eq!(crafted[op0_at], 16, "op 0 is the construction create");
    crafted[op0_at] = 33;
    assert!(
        execution::decode(&B64.encode(crafted)).is_none(),
        "opcode 33 inside a version-1 blob must be rejected"
    );

    // The version-5 grammar is fenced below the version-4 row: the
    // pinned version-5 program (its spine carries opcode 38) rewritten
    // to version 4 must decode to null.
    let mut v5_down = B64
        .decode(php_vectors::PROGRAM_V5)
        .expect("the pinned v5 program must decode as base64");
    assert_eq!(v5_down[version_at], 5);
    v5_down[version_at] = 4;
    assert!(
        execution::decode(&B64.encode(v5_down)).is_none(),
        "a version-5 program with opcode 38 must never decode as version 4"
    );
}

#[test]
fn rust_decodes_and_traces_php_programs() {
    let program = execution::decode(php_vectors::PROGRAM).expect("the PHP program must parse");
    assert_eq!(program.scope, "login");
    assert_eq!(program.action, "login-action");
    assert_eq!(program.op_version, 2);
    assert!(!execution::canonical_trace(&program).is_empty());

    let program_v1 =
        execution::decode(php_vectors::PROGRAM_V1).expect("the PHP version-1 program must parse");
    assert_eq!(program_v1.scope, "login");
    assert_eq!(program_v1.action, "login-action");
    assert_eq!(program_v1.op_version, 1);
    assert!(!execution::canonical_trace(&program_v1).is_empty());
    assert!(!execution::canonical_trace(&program_v1).contains("obs("));
}

fn config() -> ChallengeConfig {
    ChallengeConfig {
        secret_key: String::from_utf8_lossy(KEY).into_owned(),
        algorithm: PoWAlgorithm::Sha256,
        m_kib: 0,
        t: 1,
        p: 1,
        target_bits: 8,
        argon2_target_bits: 8,
        ttl_secs: 120,
        min_duration_ms: Some(0),
        auto_tune: false,
        auto_tune_min_bits: 8,
        auto_tune_max_bits: 20,
        binding_mode: kiwicaptcha::challenge::BindingMode::Bound,
        policy_version: 1,
        region: None,
        issuer: None,
        kid: 1,
        execution_key: Some(String::from_utf8_lossy(KEY).into_owned()),
        rsw_modulus_n: None,
        rsw_lambda: None,
        rsw_t: kiwicaptcha::challenge::DEFAULT_RSW_T,
    }
}

fn solve_counter(prefix: &str, salt: &str, target_bits: u32) -> u64 {
    use sha2::{Digest, Sha256};
    let salt_bytes = B64.decode(salt).unwrap();
    for counter in 0..1_000_000u64 {
        let mut input = Vec::new();
        input.extend_from_slice(prefix.as_bytes());
        input.extend_from_slice(counter.to_string().as_bytes());
        input.extend_from_slice(&salt_bytes);
        let hash = Sha256::digest(&input);
        let zeros = hash.iter().take_while(|b| **b == 0).count() * 8 + {
            let first = hash.iter().find(|b| **b != 0);
            match first {
                None => 0,
                Some(b) => {
                    let mut n = 0;
                    let mut v = *b;
                    while v & 0x80 == 0 {
                        n += 1;
                        v <<= 1;
                    }
                    n
                }
            }
        };
        if zeros >= target_bits as usize {
            return counter;
        }
    }
    panic!("no winning counter found");
}

#[test]
fn armed_issuance_verifies_with_correct_digest() {
    let now = 1_700_000_000u64;
    let now_ns = 1_700_000_000_000_000u64;
    let issued = issue_challenge_with_execution(
        &config(),
        "login",
        "203.0.113.7",
        now,
        now_ns,
        0,
        None,
        true,
        Some("login-action"),
        Some(1),
        false,
    )
    .expect("armed issuance");
    let program = issued.challenge.execution_program.as_ref().expect("armed");
    let counter = solve_counter(&issued.record.prefix, &issued.record.salt, 8);

    let mut record = issued.record;
    let decoded = execution::decode(program).expect("the issued program must parse");
    let trace = execution::fixtures::executed_trace_for(&decoded);
    let trace_b64: String = B64
        .encode(trace.as_bytes())
        .replace('+', "-")
        .replace('/', "_")
        .trim_end_matches('=')
        .to_string();
    let digest = execution::expected_digest_over_trace(program, &record.nonce, &trace).unwrap();
    let mut ctx = VerifyContext {
        record: &mut record,
        secret_key: std::str::from_utf8(KEY).unwrap(),
        secrets_by_kid: None,
        revoked_kids: None,
        counter,
        duration_ms: 5000,
        now_unix: Some(&mut || now + 1),
        now_ns: now_ns + 5_000_000,
        min_duration_ms: 0,
        expected_scope: Some("login"),
        expected_request_binding: kiwicaptcha::verify::RequestBindingExpectation::Unenforced,
        expected_region: None,
        expected_issuer: None,
        expected_policy_version: None,
        client_ip: Some("203.0.113.7"),
        execution_digest: Some(&digest),
        execution_trace: Some(&trace_b64),
        telemetry: None,
        enforce_telemetry: false,
        accept_legacy_v1: false,
        rsw_proof: None,
        rsw_modulus_n: None,
        rsw_lambda: None,
        max_attempts: 0,
    };
    assert!(matches!(
        kiwicaptcha::verify::verify_solution(&mut ctx),
        VerifyOutcome::Valid { .. }
    ));
}

#[test]
fn armed_record_without_digest_is_execution_mismatch() {
    let now = 1_700_000_000u64;
    let now_ns = 1_700_000_000_000_000u64;
    let issued = issue_challenge_with_execution(
        &config(),
        "login",
        "203.0.113.7",
        now,
        now_ns,
        0,
        None,
        true,
        Some("login-action"),
        Some(1),
        false,
    )
    .unwrap();
    let counter = solve_counter(&issued.record.prefix, &issued.record.salt, 8);

    let mut record = issued.record;
    let mut ctx = VerifyContext {
        record: &mut record,
        secret_key: std::str::from_utf8(KEY).unwrap(),
        secrets_by_kid: None,
        revoked_kids: None,
        counter,
        duration_ms: 5000,
        now_unix: Some(&mut || now + 1),
        now_ns: now_ns + 5_000_000,
        min_duration_ms: 0,
        expected_scope: Some("login"),
        expected_request_binding: kiwicaptcha::verify::RequestBindingExpectation::Unenforced,
        expected_region: None,
        expected_issuer: None,
        expected_policy_version: None,
        client_ip: Some("203.0.113.7"),
        execution_digest: None,
        execution_trace: None,
        telemetry: None,
        enforce_telemetry: false,
        accept_legacy_v1: false,
        rsw_proof: None,
        rsw_modulus_n: None,
        rsw_lambda: None,
        max_attempts: 0,
    };
    assert_eq!(
        kiwicaptcha::verify::verify_solution(&mut ctx),
        VerifyOutcome::Invalid(VerifyError::ExecutionMismatch)
    );
}

#[test]
fn wrong_digest_and_digest_from_another_challenge_are_execution_mismatch() {
    let now = 1_700_000_000u64;
    let now_ns = 1_700_000_000_000_000u64;
    let issued_a = issue_challenge_with_execution(
        &config(),
        "login",
        "203.0.113.7",
        now,
        now_ns,
        0,
        None,
        true,
        Some("login-action"),
        Some(1),
        false,
    )
    .unwrap();
    let issued_b = issue_challenge_with_execution(
        &config(),
        "login",
        "203.0.113.7",
        now,
        now_ns,
        0,
        None,
        true,
        Some("login-action"),
        Some(1),
        false,
    )
    .unwrap();
    assert_ne!(issued_a.record.nonce, issued_b.record.nonce);

    let wrong = "0".repeat(64);
    let digest_b = execution::expected_digest(
        issued_b.challenge.execution_program.as_ref().unwrap(),
        &issued_b.record.nonce,
    )
    .unwrap();
    let counter = solve_counter(&issued_a.record.prefix, &issued_a.record.salt, 8);

    for presented in [wrong.as_str(), digest_b.as_str()] {
        let mut record = issued_a.record.clone();
        let mut ctx = VerifyContext {
            record: &mut record,
            secret_key: std::str::from_utf8(KEY).unwrap(),
            secrets_by_kid: None,
            revoked_kids: None,
            counter,
            duration_ms: 5000,
            now_unix: Some(&mut || now + 1),
            now_ns: now_ns + 5_000_000,
            min_duration_ms: 0,
            expected_scope: Some("login"),
            expected_request_binding: kiwicaptcha::verify::RequestBindingExpectation::Unenforced,
            expected_region: None,
            expected_issuer: None,
            expected_policy_version: None,
            client_ip: Some("203.0.113.7"),
            execution_digest: Some(presented),
            execution_trace: None,
            telemetry: None,
            enforce_telemetry: false,
            accept_legacy_v1: false,
            rsw_proof: None,
            rsw_modulus_n: None,
            rsw_lambda: None,
            max_attempts: 0,
        };
        assert_eq!(
            kiwicaptcha::verify::verify_solution(&mut ctx),
            VerifyOutcome::Invalid(VerifyError::ExecutionMismatch)
        );
    }
}

#[test]
fn arming_without_execution_key_refuses() {
    let mut cfg = config();
    cfg.execution_key = None;
    let err = issue_challenge_with_execution(
        &cfg,
        "login",
        "203.0.113.7",
        1_700_000_000,
        1_700_000_000_000_000,
        0,
        None,
        true,
        Some("login-action"),
        Some(1),
        false,
    )
    .unwrap_err();
    assert!(matches!(
        err,
        kiwicaptcha::challenge::SignError::ExecutionKeyNotConfigured
    ));
}

#[test]
fn unarmed_issuance_rejects_a_stray_digest() {
    let now = 1_700_000_000u64;
    let now_ns = 1_700_000_000_000_000u64;
    let issued = issue_challenge_with_execution(
        &config(),
        "login",
        "203.0.113.7",
        now,
        now_ns,
        0,
        None,
        false,
        None,
        None,
        false,
    )
    .unwrap();
    assert!(issued.challenge.execution_program.is_none());
    assert!(issued.record.execution_program.is_none());
    assert!(issued.record.execution_commitment.is_none());
    assert!(issued.record.execution_version.is_none());

    let counter = solve_counter(&issued.record.prefix, &issued.record.salt, 8);
    let mut record = issued.record;
    let mut ctx = VerifyContext {
        record: &mut record,
        secret_key: std::str::from_utf8(KEY).unwrap(),
        secrets_by_kid: None,
        revoked_kids: None,
        counter,
        duration_ms: 5000,
        now_unix: Some(&mut || now + 1),
        now_ns: now_ns + 5_000_000,
        min_duration_ms: 0,
        expected_scope: Some("login"),
        expected_request_binding: kiwicaptcha::verify::RequestBindingExpectation::Unenforced,
        expected_region: None,
        expected_issuer: None,
        expected_policy_version: None,
        client_ip: Some("203.0.113.7"),
        // Stray execution evidence: a digest presented for a record
        // whose signed canonical carries NO commitment is deterministic
        // invalid, never silently ignored.
        execution_digest: Some(&"a".repeat(64)),
        execution_trace: None,
        telemetry: None,
        enforce_telemetry: false,
        accept_legacy_v1: false,
        rsw_proof: None,
        rsw_modulus_n: None,
        rsw_lambda: None,
        max_attempts: 0,
    };
    assert_eq!(
        kiwicaptcha::verify::verify_solution(&mut ctx),
        VerifyOutcome::Invalid(VerifyError::ExecutionMismatch)
    );
}
