//! ExecutionChallengeV1 cross-language parity and verify-path tests.
//!
//! The pinned vectors in [`php_vectors`] are generated by the PHP core
//! (`KiwiCaptcha\ExecutionChallengeGenerator` with the fixed key
//! `0123456789abcdef0123456789abcdef`) — the Rust mirror must reproduce
//! the identical program blob, canonical trace and expected digest, so a
//! PHP-issued program verifies byte-identically in Rust (and vice versa:
//! the PHP core pins the Rust-generated vectors in
//! `tests/ExecutionChallengeTest.php`).

use base64::engine::general_purpose::STANDARD as B64;
use base64::Engine;
use kiwicaptcha::challenge::{issue_challenge_with_execution, ChallengeConfig, PoWAlgorithm};
use kiwicaptcha::execution;
use kiwicaptcha::verify::{VerifyContext, VerifyError, VerifyOutcome};

const KEY: &[u8] = b"0123456789abcdef0123456789abcdef";
const NONCE: &str = "xAfSYcl6VyvtYZcQUhvXxin2pojnG5TmZoHg7K6NG3s=";

/// PHP-generated vectors (pinned): program blob + expected digest for the
/// fixed context (nonce, scope "login", action "login-action", version "1")
/// and a second context (scope "signup", action "other-action", version "2").
mod php_vectors {
    pub const PROGRAM: &str = "AQVsb2dpbgxsb2dpbi1hY3Rpb24BFgCNqxVpLB6T8gdMU7FL5ux+lQwFTXdMVUYGmFkUzg9gs4cGNoDqS0K97IkBOG+tlsscQ9cRsBlfVGNvMDN7TkgwX01xVVJwRXZ2O0VtcSE3BiXJxpHRj5W3B27w4LXd0kdkDgklYCZ4Nlw9ekP3FCQWBXJKaSNZB3CjmYxw+iyPAuRxk85f2jJZBAeyj2Cgf2bwCQkoA/Rf4OOLTV7RBiZgyZwMpiabCCgbA69WjtsHgEEvFQM1MFAaLX5reXdAKS0we1NXNFZuO3sqfmEgSDtSUEc=";
    pub const DIGEST: &str = "c5eb55408b1973d669f6fc322b0b440958858b4ffee47a4ef411a1e0b7e8a439";
    pub const PROGRAM2: &str = "AQZzaWdudXAMb3RoZXItYWN0aW9uAhEbDQU9Kz9aT2oLChUKMWBaIlI8eH43dxhFX01bT2p2UTB6YnYuPypzOlc7JGggQyQH3myJ1jKtuN0AJkSWMiV1QQcDUQB6iaivOGAGMJx6PF+rcsEYAnc3DgUsTVF5cowVCDBCdWFRPFV7GHBGakt5TF9sV1AhMCFeV3ZLIyAjclA7TxANDXdFdDNjbEhlMG1pT0QLugbjlCV9QN7z/g8BKZmkB/pZHone1eUUEwR5bEtJ";
    pub const DIGEST2: &str = "7bcffeffdc074313ceba5d4602e15fbe108e677a435c10ed95f20bb857d45156";
}

#[test]
fn rust_mirror_reproduces_php_generated_program() {
    let program = execution::generate(KEY, NONCE, "login", "login-action", "1").unwrap();
    assert_eq!(
        program,
        php_vectors::PROGRAM,
        "the Rust generator must reproduce the PHP program byte-for-byte"
    );
    assert_eq!(
        execution::expected_digest(&program, NONCE).unwrap(),
        php_vectors::DIGEST,
        "the Rust digest must reproduce the PHP digest"
    );

    let program2 = execution::generate(KEY, NONCE, "signup", "other-action", "2").unwrap();
    assert_eq!(program2, php_vectors::PROGRAM2);
    assert_eq!(
        execution::expected_digest(&program2, NONCE).unwrap(),
        php_vectors::DIGEST2
    );
    assert_ne!(program, program2);
}

#[test]
fn rust_decodes_and_traces_php_program() {
    let program = execution::decode(php_vectors::PROGRAM).expect("the PHP program must parse");
    assert_eq!(program.scope, "login");
    assert_eq!(program.action, "login-action");
    assert_eq!(program.op_version, 1);
    assert!(!execution::canonical_trace(&program).is_empty());
}

fn config() -> ChallengeConfig {
    ChallengeConfig {
        secret_key: String::from_utf8_lossy(KEY).into_owned(),
        algorithm: PoWAlgorithm::Sha256,
        m_kib: 0,
        t: 1,
        p: 1,
        target_bits: 8,
        argon2_target_bits: 8,
        ttl_secs: 120,
        min_duration_ms: Some(0),
        auto_tune: false,
        auto_tune_min_bits: 8,
        auto_tune_max_bits: 20,
        binding_mode: kiwicaptcha::challenge::BindingMode::Bound,
        policy_version: 1,
        region: None,
        issuer: None,
        kid: 1,
        execution_key: Some(String::from_utf8_lossy(KEY).into_owned()),
    }
}

fn solve_counter(prefix: &str, salt: &str, target_bits: u32) -> u64 {
    use sha2::{Digest, Sha256};
    let salt_bytes = B64.decode(salt).unwrap();
    for counter in 0..1_000_000u64 {
        let mut input = Vec::new();
        input.extend_from_slice(prefix.as_bytes());
        input.extend_from_slice(counter.to_string().as_bytes());
        input.extend_from_slice(&salt_bytes);
        let hash = Sha256::digest(&input);
        let zeros = hash.iter().take_while(|b| **b == 0).count() * 8 + {
            let first = hash.iter().find(|b| **b != 0);
            match first {
                None => 0,
                Some(b) => {
                    let mut n = 0;
                    let mut v = *b;
                    while v & 0x80 == 0 {
                        n += 1;
                        v <<= 1;
                    }
                    n
                }
            }
        };
        if zeros >= target_bits as usize {
            return counter;
        }
    }
    panic!("no winning counter found");
}

#[test]
fn armed_issuance_verifies_with_correct_digest() {
    let now = 1_700_000_000u64;
    let now_ns = 1_700_000_000_000_000u64;
    let issued = issue_challenge_with_execution(
        &config(),
        "login",
        "203.0.113.7",
        now,
        now_ns,
        0,
        None,
        true,
        Some("login-action"),
        Some("1"),
        false,
    )
    .expect("armed issuance");
    let program = issued.challenge.execution_program.as_ref().expect("armed");
    let counter = solve_counter(&issued.record.prefix, &issued.record.salt, 8);

    let mut record = issued.record;
    let digest = execution::expected_digest(program, &record.nonce).unwrap();
    let mut ctx = VerifyContext {
        record: &mut record,
        secret_key: std::str::from_utf8(KEY).unwrap(),
        secrets_by_kid: None,
        revoked_kids: None,
        counter,
        duration_ms: 5000,
        now_unix: Some(&mut || now + 1),
        now_ns: now_ns + 5_000_000,
        min_duration_ms: 0,
        expected_scope: Some("login"),
        expected_request_binding: kiwicaptcha::verify::RequestBindingExpectation::Unenforced,
        expected_region: None,
        expected_issuer: None,
        expected_policy_version: None,
        client_ip: Some("203.0.113.7"),
        execution_digest: Some(&digest),
        telemetry: None,
        enforce_telemetry: false,
        accept_legacy_v1: false,
        max_attempts: 0,
    };
    assert!(matches!(
        kiwicaptcha::verify::verify_solution(&mut ctx),
        VerifyOutcome::Valid { .. }
    ));
}

#[test]
fn armed_record_without_digest_is_execution_mismatch() {
    let now = 1_700_000_000u64;
    let now_ns = 1_700_000_000_000_000u64;
    let issued = issue_challenge_with_execution(
        &config(),
        "login",
        "203.0.113.7",
        now,
        now_ns,
        0,
        None,
        true,
        Some("login-action"),
        Some("1"),
        false,
    )
    .unwrap();
    let counter = solve_counter(&issued.record.prefix, &issued.record.salt, 8);

    let mut record = issued.record;
    let mut ctx = VerifyContext {
        record: &mut record,
        secret_key: std::str::from_utf8(KEY).unwrap(),
        secrets_by_kid: None,
        revoked_kids: None,
        counter,
        duration_ms: 5000,
        now_unix: Some(&mut || now + 1),
        now_ns: now_ns + 5_000_000,
        min_duration_ms: 0,
        expected_scope: Some("login"),
        expected_request_binding: kiwicaptcha::verify::RequestBindingExpectation::Unenforced,
        expected_region: None,
        expected_issuer: None,
        expected_policy_version: None,
        client_ip: Some("203.0.113.7"),
        execution_digest: None,
        telemetry: None,
        enforce_telemetry: false,
        accept_legacy_v1: false,
        max_attempts: 0,
    };
    assert_eq!(
        kiwicaptcha::verify::verify_solution(&mut ctx),
        VerifyOutcome::Invalid(VerifyError::ExecutionMismatch)
    );
}

#[test]
fn wrong_digest_and_digest_from_another_challenge_are_execution_mismatch() {
    let now = 1_700_000_000u64;
    let now_ns = 1_700_000_000_000_000u64;
    let issued_a = issue_challenge_with_execution(
        &config(),
        "login",
        "203.0.113.7",
        now,
        now_ns,
        0,
        None,
        true,
        Some("login-action"),
        Some("1"),
        false,
    )
    .unwrap();
    let issued_b = issue_challenge_with_execution(
        &config(),
        "login",
        "203.0.113.7",
        now,
        now_ns,
        0,
        None,
        true,
        Some("login-action"),
        Some("1"),
        false,
    )
    .unwrap();
    assert_ne!(issued_a.record.nonce, issued_b.record.nonce);

    let wrong = "0".repeat(64);
    let digest_b = execution::expected_digest(
        issued_b.challenge.execution_program.as_ref().unwrap(),
        &issued_b.record.nonce,
    )
    .unwrap();
    let counter = solve_counter(&issued_a.record.prefix, &issued_a.record.salt, 8);

    for presented in [wrong.as_str(), digest_b.as_str()] {
        let mut record = issued_a.record.clone();
        let mut ctx = VerifyContext {
            record: &mut record,
            secret_key: std::str::from_utf8(KEY).unwrap(),
            secrets_by_kid: None,
            revoked_kids: None,
            counter,
            duration_ms: 5000,
            now_unix: Some(&mut || now + 1),
            now_ns: now_ns + 5_000_000,
            min_duration_ms: 0,
            expected_scope: Some("login"),
            expected_request_binding: kiwicaptcha::verify::RequestBindingExpectation::Unenforced,
            expected_region: None,
            expected_issuer: None,
            expected_policy_version: None,
            client_ip: Some("203.0.113.7"),
            execution_digest: Some(presented),
            telemetry: None,
            enforce_telemetry: false,
            accept_legacy_v1: false,
            max_attempts: 0,
        };
        assert_eq!(
            kiwicaptcha::verify::verify_solution(&mut ctx),
            VerifyOutcome::Invalid(VerifyError::ExecutionMismatch)
        );
    }
}

#[test]
fn arming_without_execution_key_refuses() {
    let mut cfg = config();
    cfg.execution_key = None;
    let err = issue_challenge_with_execution(
        &cfg,
        "login",
        "203.0.113.7",
        1_700_000_000,
        1_700_000_000_000_000,
        0,
        None,
        true,
        Some("login-action"),
        Some("1"),
        false,
    )
    .unwrap_err();
    assert!(matches!(
        err,
        kiwicaptcha::challenge::SignError::ExecutionKeyNotConfigured
    ));
}

#[test]
fn unarmed_issuance_ignores_a_stray_digest() {
    let now = 1_700_000_000u64;
    let now_ns = 1_700_000_000_000_000u64;
    let issued = issue_challenge_with_execution(
        &config(),
        "login",
        "203.0.113.7",
        now,
        now_ns,
        0,
        None,
        false,
        None,
        None,
        false,
    )
    .unwrap();
    assert!(issued.challenge.execution_program.is_none());
    assert!(issued.record.execution_program.is_none());

    let counter = solve_counter(&issued.record.prefix, &issued.record.salt, 8);
    let mut record = issued.record;
    let mut ctx = VerifyContext {
        record: &mut record,
        secret_key: std::str::from_utf8(KEY).unwrap(),
        secrets_by_kid: None,
        revoked_kids: None,
        counter,
        duration_ms: 5000,
        now_unix: Some(&mut || now + 1),
        now_ns: now_ns + 5_000_000,
        min_duration_ms: 0,
        expected_scope: Some("login"),
        expected_request_binding: kiwicaptcha::verify::RequestBindingExpectation::Unenforced,
        expected_region: None,
        expected_issuer: None,
        expected_policy_version: None,
        client_ip: Some("203.0.113.7"),
        // A stray digest on an unarmed challenge is inert.
        execution_digest: Some(&"a".repeat(64)),
        telemetry: None,
        enforce_telemetry: false,
        accept_legacy_v1: false,
        max_attempts: 0,
    };
    assert!(matches!(
        kiwicaptcha::verify::verify_solution(&mut ctx),
        VerifyOutcome::Valid { .. }
    ));
}
