//! The shared solution-token boundary contract
//! (`protocol/solution-token-v1/fixtures.json`): the 20,000,000 solver
//! hash ceiling and the exact counter spellings both decoders accept.
//!
//! The fixture is generated by the PHP encoder; these assertions prove
//! the Rust decoder AND encoder agree with it byte-for-byte. The PHP
//! `TokenSolverLimitFixtureTest` asserts the same fixture, so a drift on
//! either side fails in the language that moved (and the semantic
//! `tools/ci/limits-parity-check.sh` lane pins the ceiling itself against
//! the manifest).

use kiwicaptcha::token::{DecodeError, SolutionToken};
use serde_json::Value;

fn fixture() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../protocol/solution-token-v1/fixtures.json"
    );
    let raw = std::fs::read_to_string(path).expect("solution-token fixture must be readable");
    serde_json::from_str(&raw).expect("solution-token fixture must be valid JSON")
}

#[test]
fn solver_ceiling_matches_the_fixture_authority() {
    let fixture = fixture();
    let ceiling = fixture["solver_max_hashes"]
        .as_u64()
        .expect("solver_max_hashes must be a number");
    assert_eq!(ceiling, 20_000_000);
    assert_eq!(ceiling, kiwicaptcha::challenge::SOLVER_MAX_HASHES);
}

#[test]
fn accepted_boundary_counters_decode_and_reencode() {
    let fixture = fixture();
    let nonce = fixture["nonce_b64"].as_str().unwrap();
    let duration = fixture["duration_ms"].as_u64().unwrap();
    let telemetry: Value =
        serde_json::from_str(fixture["telemetry_json"].as_str().unwrap()).unwrap();
    let accepted = fixture["accepted"].as_object().expect("accepted rows");

    assert!(!accepted.is_empty());
    for (counter, encoded) in accepted {
        let expected: u64 = counter.parse().unwrap();
        let encoded = encoded.as_str().unwrap();
        let decoded = SolutionToken::decode(encoded)
            .unwrap_or_else(|e| panic!("counter {counter} must decode from the fixture: {e:?}"));
        assert_eq!(decoded.counter, expected);
        // The encoder direction: exactly the same bytes, so the Rust
        // encoder and decoder are both pinned to the shared fixture.
        let token = SolutionToken {
            nonce: nonce.to_string(),
            counter: expected,
            duration_ms: duration,
            telemetry: telemetry.clone(),
            execution_digest: None,
            execution_trace: None,
            rsw_proof: None,
        };
        assert_eq!(
            token.encode(),
            encoded,
            "counter {counter} must re-encode byte-for-byte"
        );
    }
}

#[test]
fn rejected_boundary_counters_are_refused() {
    let fixture = fixture();
    let rejected = fixture["rejected"].as_object().expect("rejected rows");
    assert!(!rejected.is_empty());
    for (counter, encoded) in rejected {
        let encoded = encoded.as_str().unwrap();
        assert_eq!(
            SolutionToken::decode(encoded).err(),
            Some(DecodeError::InvalidCounter),
            "counter {counter} must be rejected as beyond the solver maximum"
        );
    }
}

#[test]
fn cross_language_token_above_the_historical_five_million_ceiling() {
    // 5,000,001 is a counter the 20M browser solver really can mint but
    // the historical 5M decoder refused; both languages must decode it.
    let fixture = fixture();
    let cross = &fixture["cross_language"];
    let counter = cross["counter"].as_u64().unwrap();
    assert!(counter > 5_000_000);
    assert!(counter < kiwicaptcha::challenge::SOLVER_MAX_HASHES);
    let encoded = cross["encoded"].as_str().unwrap();

    let decoded = SolutionToken::decode(encoded).expect("the cross-language token must decode");
    assert_eq!(decoded.counter, counter);

    let telemetry: Value =
        serde_json::from_str(fixture["telemetry_json"].as_str().unwrap()).unwrap();
    let token = SolutionToken {
        nonce: fixture["nonce_b64"].as_str().unwrap().to_string(),
        counter,
        duration_ms: fixture["duration_ms"].as_u64().unwrap(),
        telemetry,
        execution_digest: None,
        execution_trace: None,
        rsw_proof: None,
    };
    assert_eq!(token.encode(), encoded);
}
