apiVersion: v1
kind: ServiceAccount
metadata:
  name: mta
  namespace: apexmail
  labels:
    app.kubernetes.io/name: mta
    app.kubernetes.io/component: mail-server
automountServiceAccountToken: false