#!/usr/bin/env node
// Regenerates assets/kiwicaptcha-wasm.js from the wasm-pack `--target web` output.
//
// The wasm-bindgen web glue uses ESM (`export`, `import.meta.url`) and fetches
// the .wasm over the network. The widget needs a single self-contained inline
// script with no external requests, so this script:
//   1. strips all ESM syntax (`export function` -> `function`, drops export tails)
//   2. removes the fetch/URL loading branch (we always pass bytes directly)
//   3. inlines the .wasm binary as base64
//   4. wraps everything in an `IIFE` exposing `window.__kiwiCaptchaWasm.load()`
//
// Usage: node build-embed.mjs [pkgDir] [outFile]
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkgDir = process.argv[2] || join(here, "pkg");
const outFile = process.argv[3] || join(here, "assets", "kiwicaptcha-wasm.js");

let glue = readFileSync(join(pkgDir, "kiwicaptcha_wasm.js"), "utf8");

// 1. Strip ESM function exports.
glue = glue.replaceAll("export function", "function");

// 2. Drop ALL remaining export statements (tail exports vary by build mode).
glue = glue.replace(/^export\s*\{[^}]*\};?\s*$/gm, "");

// 3. Remove the URL/import.meta loading branch: we always pass bytes.
glue = glue.replace(
  /if \(module_or_path === undefined\) \{\s*module_or_path = new URL\([^;]+;\s*\}/s,
  ""
);
glue = glue.replace(
  /if \(typeof module_or_path === 'string' \|\| \(typeof Request === 'function' && module_or_path instanceof Request\) \|\| \(typeof URL === 'function' && module_or_path instanceof URL\)\) \{\s*module_or_path = fetch\(module_or_path\);\s*\}/s,
  ""
);

// 4. Drop sourcemap region markers and any stray import.meta references.
glue = glue.replace(/\/\/#endregion/g, "");
glue = glue.replace(/\/\/#sourceMappingURL=[^\n]*/g, "");
glue = glue.replace(/import\.meta\.[a-zA-Z]+/g, "location.href");

// Sanity checks: the transformed glue must be plain classic JS.
if (glue.includes("export ") || glue.includes("import.meta")) {
  console.error("FATAL: transformed glue still contains ESM/import.meta");
  process.exit(1);
}

// 5. Inline the wasm as base64.
const wasm = readFileSync(join(pkgDir, "kiwicaptcha_wasm_bg.wasm"));
const b64 = wasm.toString("base64");

const banner = `/* Generated by packages/kiwicaptcha-wasm/build-embed.mjs — do not edit. */
/* Source: wasm-pack --target web (wasm-bindgen 0.2.127), wasm inlined as base64. */
(function () {
  "use strict";
  var KIWI_WASM_B64 = "${b64}";
${glue}
  async function load() {
    var bytes = Uint8Array.from(atob(KIWI_WASM_B64), function (c) { return c.charCodeAt(0); });
    return __wbg_init(bytes);
  }
  if (typeof window !== "undefined") {
    window.__kiwiCaptchaWasm = { load: load, initSync: initSync };
  }
})();
`;

writeFileSync(outFile, banner);
console.log(`wrote ${outFile} (${banner.length} bytes, wasm ${wasm.length} bytes)`);
