{{- if .Values.apiServer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apexmail.fullname" . }}-api-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apexmail.labels" . | nindent 4 }}
    {{- include "apexmail.selectorLabels" (dict "name" "api-server" "context" .) | nindent 4 }}
spec:
  type: {{ .Values.apiServer.service.type }}
  selector:
    {{- include "apexmail.selectorLabels" (dict "name" "api-server" "context" .) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.apiServer.service.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.apiServer.metricsPort }}
      targetPort: metrics
      protocol: TCP
{{- end }}
