{{- if .Values.enterprise.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apexmail.fullname" . }}-enterprise
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apexmail.labels" . | nindent 4 }}
    {{- include "apexmail.selectorLabels" (dict "name" "enterprise" "context" .) | nindent 4 }}
spec:
  type: {{ .Values.enterprise.service.type }}
  selector:
    {{- include "apexmail.selectorLabels" (dict "name" "enterprise" "context" .) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.enterprise.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
