{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "apexmail.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apexmail.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - secretName: {{ .secretName }}
      hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- if or (eq .service "api-server") (eq .service "web") }}
                name: {{ include "apexmail.fullname" $ }}-api-server
                port:
                  name: http
                {{- else if eq .service "tracking-service" }}
                name: {{ include "apexmail.fullname" $ }}-tracking-service
                port:
                  name: http
                {{- else if eq .service "web" }}
                name: {{ include "apexmail.fullname" $ }}-web
                port:
                  name: http
                {{- else if eq .service "enterprise" }}
                name: {{ include "apexmail.fullname" $ }}-enterprise
                port:
                  name: http
                {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
