#!/bin/sh
# =============================================================================
# ci/stages/images.sh — stage 5: build ALL service images on the host.
# =============================================================================
# Replaces deploy.yml's "Build & Push Docker Images" job, minus the registry:
# nothing is pushed (the host deploys from its local images), so there is no
# GHCR dependency at all.
#
# Implementation: deploy/scripts/deploy.sh IS the single build implementation
# (its Step 2/3 build the Rust workspace + every service image from the same
# Dockerfile targets the GitHub workflow used). This stage invokes it with
# --build-only, then:
#   * tags every canonical image with :<sha> in addition to :latest
#     (rollback pins — deploy/DEPLOYMENT.md § Rollback expects :<sha> tags)
#   * runs the post-build Trivy gate on EVERY runtime image the compose
#     files define (the scan list is derived from the merged compose
#     config — audit §2: the old gate scanned only api-server + mta, 2 of
#     ~20 built images)
#   * writes SPDX SBOMs for runtime images (advisory, like the Syft step)
#   * records the RELEASE MANIFEST (release-manifest.json: content digest,
#     SBOM digest, provenance null) and renders the IMMUTABLE DIGEST
#     OVERRIDE (docker-compose.digest-override.yml) so manual compose
#     invocations pin the exact built content instead of the mutable
#     :latest tag (external audit item 5 — deploy/DEPLOYMENT.md
#     § "Immutable deployment artifacts")
#   * prunes :<sha> tags older than CI_KEEP_SHAS (default 5) per service so
#     image storage cannot grow without bound
#
# Skips (exit 75) when not on the deploy host (no $CI_DEPLOY_DIR/.env) —
# e.g. a developer machine or the selftest.
# =============================================================================
set -eu

. "${CI_ROOT:-$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd -P)}/lib.sh"

CANONICAL_SERVICES="api-server mta imap-server mailstore worker enterprise observability
                    status-server billing-service sales-autopilot compliance analytics-worker pdf-renderer ai-service migrator"
# Images with their own Dockerfiles, built by deploy.sh's separate loop:
# marketing + tracking + the four backup sidecars (postgres / clickhouse /
# redis / analytics-cold).
EXTRA_IMAGES="marketing tracking-service postgres-backup clickhouse-backup redis-backup analytics-backup"

# Compose service key for an image name. Exactly ONE divergence between the
# canonical image names and the compose service keys (docker-compose.prod.yml):
# the tracking IMAGE is `tracking-service`, its compose service key is
# `tracking` (same as ci/stages/deploy.sh STACK_SERVICES). The digest override
# must merge INTO the compose config, so it is keyed by compose service keys.
image_compose_key() {
    case "$1" in
        tracking-service) printf 'tracking' ;;
        *)                printf '%s' "$1" ;;
    esac
}

# release_manifest_and_override — external audit item 5 (immutable deployment
# artifacts). Called with the images built and :<sha>-tagged; writes into
# $RUN_DIR:
#
#   release-manifest.json
#     [{service, image_repository, git_sha, oci_digest, sbom_digest|null,
#       provenance_digest|null}] for every CANONICAL_SERVICES + EXTRA_IMAGES
#     image. oci_digest prefers the OCI repo digest the daemon recorded
#     (RepoDigests — present with the containerd image store and after any
#     registry push) and falls back to the image ID (`.Id`), which is the
#     exact content the deploy-stage tamper guard re-verifies. sbom_digest is
#     the sha256 of the Trivy SPDX SBOM this stage generated for the image
#     (null when the image was outside the blocking gate — e.g. the backup
#     sidecars). Nothing in this pipeline produces provenance attestations,
#     so provenance_digest is always null (recorded for the audit shape).
#
#   docker-compose.digest-override.yml
#     A compose override mapping every first-party service to pinned content:
#     `repo@sha256:<digest>` when a repo digest exists locally, else the full
#     `:<git-sha>` rollback tag (daemons without local repo digests cannot
#     resolve digest refs for local builds — the tag + the deploy-stage digest
#     verification are the tamper evidence there). ci/stages/deploy.sh APPLIES
#     this file to its compose() calls and runs tools/check_image_pinning.py
#     over the live rendering; manual compose invocations must append it too
#     (deploy/DEPLOYMENT.md § "Immutable deployment artifacts").
release_manifest_and_override() {
    command -v jq >/dev/null 2>&1 \
        || { ci_err "jq is required to write the release manifest (ci/install.sh installs it)"; return 1; }

    _rm_entries="$RUN_DIR/.release-manifest.entries.jsonl"
    _rm_override="$RUN_DIR/docker-compose.digest-override.yml"
    : >"$_rm_entries"
    _rm_tmp="$_rm_override.tmp"
    {
        printf '# GENERATED by ci/stages/images.sh for run %s — do not edit, do not commit.\n' "${CI_RUN_ID:-}"
        printf '# Immutable pins for the images THIS run built, gated and recorded in\n'
        printf '# release-manifest.json (external audit item 5). Manual compose invocations\n'
        printf '# MUST append this file:\n'
        printf '#   docker compose -f docker-compose.yml -f docker-compose.prod.yml \\\n'
        printf '#     -f <run-dir>/docker-compose.digest-override.yml --env-file .env ...\n'
        printf '# Pin form: repo@sha256:<digest> when the daemon records the local repo\n'
        printf '# digest; otherwise the full :<git-sha> rollback tag (content re-verified\n'
        printf '# against the manifest by the deploy stage).\n'
        printf 'services:\n'
    } >"$_rm_tmp"

    _rm_count=0
    for _svc in $CANONICAL_SERVICES $EXTRA_IMAGES; do
        _img="$_ns/$_svc:$CI_SHA"
        _img_id=$(docker image inspect "$_img" --format '{{.Id}}' 2>/dev/null) || _img_id=""
        if [ -z "$_img_id" ]; then
            ci_err "cannot inspect $_img for the release manifest"
            rm -f "$_rm_tmp" "$_rm_entries"
            return 1
        fi
        # Prefer a real OCI repo digest; fall back to the image content ID.
        _repo_digests=$(docker image inspect "$_img" \
            --format '{{range .RepoDigests}}{{printf "%s\n" .}}{{end}}' 2>/dev/null) || _repo_digests=""
        _oci_digest=""
        for _rd in $_repo_digests; do
            case "$_rd" in
                "$_ns/$_svc@"*) _oci_digest=${_rd#*@}; break ;;
            esac
        done
        if [ -n "$_oci_digest" ]; then
            _pin="$_ns/$_svc@$_oci_digest"
        else
            _oci_digest=$_img_id
            _pin="$_img"
        fi
        # SBOM digest: the Trivy SPDX artifact section 3 wrote for this image
        # (the scan list excludes the backup sidecars — null there).
        _sbom_digest=""
        for _sname in \
            "$(printf '%s' "$_ns/$_svc:$CI_SHA" | tr '/:' '__')" \
            "$(printf '%s' "$_ns/$_svc:latest" | tr '/:' '__')"; do
            if [ -f "$RUN_DIR/sbom-$_sname.spdx.json" ] && command -v sha256sum >/dev/null 2>&1; then
                _sbom_digest="sha256:$(sha256sum "$RUN_DIR/sbom-$_sname.spdx.json" | cut -d' ' -f1)"
                break
            fi
        done
        jq -n \
            --arg service "$_svc" \
            --arg repo "$_ns/$_svc" \
            --arg sha "$CI_SHA" \
            --arg digest "$_oci_digest" \
            --arg sbom "$_sbom_digest" \
            '{service:$service, image_repository:$repo, git_sha:$sha,
              oci_digest:$digest,
              sbom_digest:(if $sbom == "" then null else $sbom end),
              provenance_digest:null}' >>"$_rm_entries" \
            || { ci_err "jq failed to build the release-manifest entry for $_svc"; rm -f "$_rm_tmp" "$_rm_entries"; return 1; }
        printf '  %s:\n    image: %s\n' "$(image_compose_key "$_svc")" "$_pin" >>"$_rm_tmp"
        _rm_count=$((_rm_count + 1))
    done

    jq -s '.' "$_rm_entries" >"$RUN_DIR/release-manifest.json" \
        || { ci_err "jq failed to assemble release-manifest.json"; rm -f "$_rm_tmp" "$_rm_entries"; return 1; }
    rm -f "$_rm_entries"
    mv "$_rm_tmp" "$_rm_override"
    [ "$_rm_count" -gt 0 ] || { ci_err "release manifest would be empty — refusing"; return 1; }
    ci_info "release evidence: $RUN_DIR/release-manifest.json ($_rm_count images)"
    ci_info "immutable digest override: $_rm_override (applied by the deploy stage; append it to manual compose invocations)"
    return 0
}

stage_main() {
    if ! ci_on_deploy_host; then
        ci_skip_stage "images stage runs only on the deploy host ($CI_DEPLOY_DIR) — local/docker builds happen there"
    fi
    cd "$CI_DEPLOY_DIR"

    # --- 1. build everything through deploy.sh (the single implementation) -------
    ci_info "building all images via deploy/scripts/deploy.sh --build-only"
    # The pipeline holds the deploy flock for the whole run; deploy.sh would
    # try to flock the SAME file as a child and refuse (self-deadlock — the
    # first end-to-end images run hit exactly this). The flag makes deploy.sh
    # inherit the parent's lock instead of re-acquiring it; standalone
    # manual deploy.sh runs are unaffected.
    APEXMAIL_DEPLOY_LOCK_INHERITED=1 ci_exec bash deploy/scripts/deploy.sh --build-only \
        || { ci_err "deploy.sh --build-only failed"; return "$CI_EXIT_FAIL"; }

    # --- 2. tag :<sha> rollback pins ------------------------------------------------
    _ns=${GHCR_NS:-ghcr.io/sbelakho2/apexmail}
    ci_info "tagging images with sha $CI_SHA"
    for _svc in $CANONICAL_SERVICES $EXTRA_IMAGES; do
        if docker image inspect "$_ns/$_svc:latest" >/dev/null 2>&1; then
            ci_exec docker tag "$_ns/$_svc:latest" "$_ns/$_svc:$CI_SHA" \
                || { ci_err "failed to tag $_ns/$_svc:$CI_SHA"; return "$CI_EXIT_FAIL"; }
        else
            ci_err "expected image missing after build: $_ns/$_svc:latest"
            return "$CI_EXIT_FAIL"
        fi
    done

    # --- 3. post-build Trivy gate — EVERY runtime image the compose files define
    # Audit §2 (Trivy scanned only 2 of ~20 images): the scan list is now
    # DERIVED from the merged compose config (base + prod overlay + the
    # monitoring/migrate profiles the deploy activates) instead of a
    # hardcoded api-server+mta pair. Every service whose resolved image is
    # one of OUR builds — the GHCR_NS namespace deploy.sh tags into, or the
    # apexmail/* namespace of the monitoring sidecars — is gated. Stock
    # third-party images (postgres, redis, nginx, certbot, prometheus, ...)
    # are pulled, not built by this pipeline, and stay outside the gate.
    # The ignore policy (.trivyignore) is unchanged.
    if command -v trivy >/dev/null 2>&1; then
        # Blocking gate scope: the CANONICAL SERVING services the pipeline
        # builds (internet/tenant-facing). Ancillary sidecars — the backup
        # one-shots (postgres/clickhouse/redis-backup: offline, volume-only,
        # no network) and the date-pinned monitoring exporters — carry fat
        # base images whose long CVE tails are base-package findings with
        # no reachable path in an offline job; they are scanned ADVISORILY
        # below instead of blocking the deploy. Revisit on base bumps.
        _sidecars='postgres-backup|clickhouse-backup|redis-backup|clickhouse-exporter|redis-exporter|node-exporter|postgres-exporter|synthetic-monitor|otel-collector|tempo|loki|prometheus|alertmanager|grafana|certbot|clickhouse|postgres|redis|nginx-traefik'
        _scan_refs=$(docker compose -f docker-compose.yml -f docker-compose.prod.yml \
                --profile monitoring --profile migrate config --format json 2>>"$CI_STAGE_LOG" \
            | jq -r --arg ns "$_ns" --arg sidecars "^($_sidecars)$" '.services | to_entries[]
                | select(.value.image != null)
                | select(.key | test($sidecars) | not)
                | select(.value.image | startswith($ns + "/") or startswith("apexmail/"))
                | .value.image' | sort -u || true)
        if [ -z "$_scan_refs" ]; then
            ci_err "derived an EMPTY trivy scan list from the compose config — refusing to silently skip the gate (check the compose config output above)"
            return "$CI_EXIT_FAIL"
        fi
        for _ref in $_scan_refs; do
            # Prefer the :<sha> rollback pin (byte-identical to :latest and
            # exactly what the digest manifest below records).
            _scan_img="$_ref"
            case "$_ref" in
                "$_ns"/*:latest)
                    if docker image inspect "${_ref%:latest}:$CI_SHA" >/dev/null 2>&1; then
                        _scan_img="${_ref%:latest}:$CI_SHA"
                    fi
                    ;;
            esac
            if ! docker image inspect "$_scan_img" >/dev/null 2>&1; then
                # Not built by this pipeline (e.g. a monitoring sidecar
                # pinned to a date tag) — advisory skip, matching the fact
                # that deploy.sh never builds it.
                ci_warn "image $_scan_img (from compose config) not built by this pipeline — trivy scan skipped (advisory)"
                continue
            fi
            ci_check "trivy gate $_scan_img" \
                trivy image --ignorefile "$REPO_ROOT/.trivyignore" --severity "$CI_TRIVY_SEVERITY" --exit-code 1 --quiet "$_scan_img" \
                || { ci_err "Trivy gate FAILED for $_scan_img — fix vulnerabilities before deploying"; return "$CI_EXIT_FAIL"; }
            _sbom_name=$(printf '%s' "$_scan_img" | tr '/:' '__')
            trivy image --format spdx-json --output "$RUN_DIR/sbom-$_sbom_name.spdx.json" \
                "$_scan_img" >>"$CI_STAGE_LOG" 2>&1 \
                && ci_info "SBOM: $RUN_DIR/sbom-$_sbom_name.spdx.json" \
                || ci_warn "SBOM generation failed for $_scan_img (advisory)"
        done
    else
        ci_warn "trivy missing — post-build vulnerability gate skipped (install with ci/install.sh)"
    fi

    # --- 4. digest manifest (deploy-stage tamper guard) ------------------------------
    # Record the exact image content IDs the deploy will bring up. The deploy
    # stage re-inspects the images and refuses to continue on any mismatch —
    # nothing runs in production that this run did not build and gate.
    ci_info "recording image digest manifest"
    if ci_dry; then
        # Dry-run builds nothing — the :<sha> tags the manifest records do
        # not exist, so recording them is echo-only intent (the previous
        # code hard-failed here, which the selftest's full dry-run caught).
        ci_info "check (dry-run): digest manifest + release manifest + digest override would be recorded"
    else
        : >"$RUN_DIR/image-digests.txt"
        for _svc in $CANONICAL_SERVICES $EXTRA_IMAGES; do
            _digest=$(docker image inspect "$_ns/$_svc:$CI_SHA" \
                --format '{{.Id}}' 2>/dev/null) || _digest=""
            if [ -n "$_digest" ]; then
                printf '%s %s\n' "$_svc" "$_digest" >>"$RUN_DIR/image-digests.txt"
            else
                ci_err "cannot inspect $_ns/$_svc:$CI_SHA for the digest manifest"
                return "$CI_EXIT_FAIL"
            fi
        done
        release_manifest_and_override || return "$CI_EXIT_FAIL"
        # Sign ALL release evidence together: the tamper guard the deploy
        # stage verifies (image-digests.txt) plus the manifest + digest
        # override this run publishes.
        ( cd "$RUN_DIR" && sha256sum image-digests.txt release-manifest.json \
            docker-compose.digest-override.yml > SHA256SUMS.images 2>/dev/null ) \
            || ci_warn "sha256sum unavailable — release evidence left unsigned (advisory)"
    fi

    # --- 5. bounded :<sha> history ---------------------------------------------------
    _keep=${CI_KEEP_SHAS:-5}
    ci_info "pruning :<sha> image tags beyond the newest $_keep per service"
    if ci_dry; then
        ci_info "check (dry-run): :<sha> pruning and dangling-image prune skipped"
    else
    for _svc in $CANONICAL_SERVICES $EXTRA_IMAGES; do
        docker images "$_ns/$_svc" --format '{{.Tag}} {{.ID}}' 2>/dev/null \
            | grep -E '^[0-9a-f]{7,40} ' | grep -v "^${CI_SHA:-} " | head -n -"$_keep" | while IFS=' ' read -r _tag _id; do
                [ -n "$_tag" ] || continue
                ci_info "removing old sha tag $_svc:$_tag"
                docker rmi "$_ns/$_svc:$_tag" >/dev/null 2>&1 || true
            done
    done
    docker image prune -f >/dev/null 2>&1 || true
    fi

    ci_info "images: all canonical images built, sha-tagged and gated"
    return "$CI_EXIT_OK"
}

stage_main
