services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KiwiCaptcha\Symfony\Controller\ChallengeController:
        tags: ['controller.service_arguments']

    KiwiCaptcha\Symfony\Twig\KiwiCaptchaRuntime:
        tags: ['twig.runtime']

    KiwiCaptcha\Symfony\Twig\KiwiCaptchaExtension:
        tags: ['twig.extension']

    KiwiCaptcha\Symfony\Form\KiwiCaptchaType:
        tags: ['form.type']

    KiwiCaptcha\Symfony\Validator\KiwiCaptchaValidator:
        arguments:
            $verifier: '@kiwicaptcha.verifier'
        tags: ['validator.constraint_validator']
