-- KMD VAT return tracking table
-- Stores monthly Estonia VAT return (Käibedeklaratsioon) summaries
-- generated by the billing-service periodic job.

CREATE TABLE IF NOT EXISTS vat_kmd_returns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Tax period (year and month, e.g. 2026-04 for April 2026)
    tax_year INT NOT NULL,
    tax_month INT NOT NULL CHECK (tax_month BETWEEN 1 AND 12),
    -- Status: draft, final, filed, acknowledged
    status TEXT NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'final', 'filed', 'acknowledged')),
    -- VAT rate breakdown (JSON)
    -- {
    --   "rates": [
    --     { "rate": 24, "taxable_amount_cents": 100000, "vat_amount_cents": 24000 },
    --     { "rate": 0,  "taxable_amount_cents": 50000,  "vat_amount_cents": 0, "reason": "reverse_charge" },
    --     { "rate": 0,  "taxable_amount_cents": 20000,  "vat_amount_cents": 0, "reason": "non_eu" }
    --   ],
    --   "total_taxable_cents": 170000,
    --   "total_vat_cents": 24000,
    --   "invoice_count": 45,
    --   "tenant_count": 12
    -- }
    breakdown JSONB NOT NULL DEFAULT '{}'::jsonb,
    -- Total number of invoices included in this return
    invoice_count INT NOT NULL DEFAULT 0,
    -- Total taxable amount in cents
    total_taxable_cents BIGINT NOT NULL DEFAULT 0,
    -- Total VAT amount in cents
    total_vat_cents BIGINT NOT NULL DEFAULT 0,
    -- Generated at (when the periodic job ran)
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Filed at (when submitted to EMTA)
    filed_at TIMESTAMPTZ,
    -- EMTA filing reference (acknowledgment code)
    filing_reference TEXT,
    -- Error message if filing failed
    filing_error TEXT,
    -- Created/updated timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Unique constraint: one return per tax period
CREATE UNIQUE INDEX IF NOT EXISTS idx_vat_kmd_returns_period
    ON vat_kmd_returns(tax_year, tax_month);

CREATE INDEX IF NOT EXISTS idx_vat_kmd_returns_status
    ON vat_kmd_returns(status);

CREATE INDEX IF NOT EXISTS idx_vat_kmd_returns_generated_at
    ON vat_kmd_returns(generated_at DESC);

-- =============================================================================
-- Invoice archival tracking
-- =============================================================================
CREATE TABLE IF NOT EXISTS invoice_archives (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_id UUID NOT NULL,
    tenant_id TEXT NOT NULL,
    invoice_number TEXT NOT NULL,
    -- S3/R2 URL of the archived PDF
    pdf_url TEXT,
    -- S3/R2 URL of the e-invoice XML
    xml_url TEXT,
    -- Archive batch identifier
    batch_id UUID NOT NULL DEFAULT gen_random_uuid(),
    -- Archived at
    archived_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_invoice_archives_batch
    ON invoice_archives(batch_id);

CREATE INDEX IF NOT EXISTS idx_invoice_archives_tenant
    ON invoice_archives(tenant_id, archived_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_invoice_archives_invoice
    ON invoice_archives(invoice_id);
