-- 064_standardize_tenant_id_varchar26.sql
--
-- =============================================================================
-- H-01 FINALIZATION: Standardize tenant identifiers to VARCHAR(26)
-- =============================================================================
-- Goal:
--   Normalize all tenant identity columns to VARCHAR(26) so runtime tenant IDs
--   generated by application code are represented consistently in the database.
--
-- Scope:
--   1) Ensure tenants.id is VARCHAR(26) and application-compatible columns exist.
--   2) Normalize and convert every public column named tenant_id or *_tenant_id
--      from UUID/TEXT/VARCHAR to VARCHAR(26).
--   3) Preserve referential integrity by capturing, dropping, and recreating
--      all FK constraints that involve tenant identity columns.
--
-- Data conversion rules:
--   - Values already <=26 chars and [A-Za-z0-9_-] are preserved.
--   - UUID values are converted deterministically to URL-safe base64 (22 chars).
--   - Other long/non-conforming values are deterministically hashed to 26 hex chars.
--
-- Idempotency:
--   - Safe to re-run; all DDL uses IF [NOT] EXISTS guards or dynamic checks.
-- =============================================================================


CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION apexmail_normalize_tenant_id(raw_input TEXT)
RETURNS VARCHAR(26)
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
    trimmed TEXT;
    parsed_uuid UUID;
    encoded TEXT;
BEGIN
    IF raw_input IS NULL THEN
        RETURN NULL;
    END IF;

    trimmed := btrim(raw_input);
    IF trimmed = '' THEN
        RETURN NULL;
    END IF;

    -- Preserve canonical runtime-style tenant identifiers.
    IF char_length(trimmed) <= 26 AND trimmed ~ '^[A-Za-z0-9_-]+$' THEN
        RETURN trimmed::VARCHAR(26);
    END IF;

    -- Deterministic UUID -> 22-char URL-safe base64.
    BEGIN
        parsed_uuid := trimmed::UUID;
        encoded := encode(uuid_send(parsed_uuid), 'base64');
        encoded := replace(encoded, E'\n', '');
        encoded := replace(encoded, '=', '');
        encoded := replace(encoded, '+', '-');
        encoded := replace(encoded, '/', '_');
        RETURN encoded::VARCHAR(26);
    EXCEPTION
        WHEN invalid_text_representation THEN
            -- Deterministic fallback for non-UUID values.
            RETURN substr(encode(digest(trimmed, 'sha256'), 'hex'), 1, 26)::VARCHAR(26);
    END;
END;
$$;

-- Ensure tenants exists and includes columns used by the auth flow.
CREATE TABLE IF NOT EXISTS tenants (
    id          VARCHAR(26) PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    slug        VARCHAR(255) UNIQUE,
    plan        VARCHAR(50) NOT NULL DEFAULT 'starter',
    status      VARCHAR(50) NOT NULL DEFAULT 'pending',
    settings    JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE tenants ADD COLUMN IF NOT EXISTS plan VARCHAR(50) NOT NULL DEFAULT 'starter';
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'pending';
-- settings was only in the CREATE TABLE above — reconcile it on shapes where
-- tenants pre-exists (e.g. apexmail-db SCHEMA-provisioned databases), or the
-- 072 system-tenant seed INSERT fails on the missing column.
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS settings JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE TEMP TABLE _tenant_id_map (
    old_id TEXT PRIMARY KEY,
    new_id VARCHAR(26) NOT NULL UNIQUE
) ON COMMIT DROP;

CREATE TEMP TABLE _tenant_related_fk (
    table_schema TEXT NOT NULL,
    table_name TEXT NOT NULL,
    constraint_name TEXT NOT NULL,
    constraint_def TEXT NOT NULL
) ON COMMIT DROP;

CREATE OR REPLACE FUNCTION apexmail_lookup_tenant_id(raw_input TEXT)
RETURNS VARCHAR(26)
LANGUAGE plpgsql
AS $$
DECLARE
    mapped_id VARCHAR(26);
BEGIN
    IF raw_input IS NULL THEN
        RETURN NULL;
    END IF;

    SELECT m.new_id
    INTO mapped_id
    FROM _tenant_id_map m
    WHERE m.old_id = raw_input;

    IF mapped_id IS NOT NULL THEN
        RETURN mapped_id;
    END IF;

    RETURN apexmail_normalize_tenant_id(raw_input);
END;
$$;

-- Build a collision-safe mapping for existing tenant primary keys.
DO $$
DECLARE
    rec RECORD;
    base_id VARCHAR(26);
    candidate VARCHAR(26);
    suffix INT;
BEGIN
    IF to_regclass('public.tenants') IS NULL THEN
        RETURN;
    END IF;

    FOR rec IN
        SELECT id::TEXT AS old_id
        FROM public.tenants
        ORDER BY id::TEXT
    LOOP
        base_id := apexmail_normalize_tenant_id(rec.old_id);
        candidate := base_id;
        suffix := 0;

        WHILE EXISTS (SELECT 1 FROM _tenant_id_map WHERE new_id = candidate) LOOP
            suffix := suffix + 1;
            candidate := substr(base_id, 1, 22)
                      || right(lpad(to_hex(suffix), 4, '0'), 4);
        END LOOP;

        INSERT INTO _tenant_id_map (old_id, new_id)
        VALUES (rec.old_id, candidate);
    END LOOP;
END;
$$;

-- Capture every FK touching tenant_id or *_tenant_id columns.
INSERT INTO _tenant_related_fk (table_schema, table_name, constraint_name, constraint_def)
SELECT ns.nspname,
       rel.relname,
       con.conname,
       pg_get_constraintdef(con.oid)
FROM pg_constraint con
JOIN pg_class rel ON rel.oid = con.conrelid
JOIN pg_namespace ns ON ns.oid = rel.relnamespace
WHERE con.contype = 'f'
  AND ns.nspname = 'public'
  AND (
        EXISTS (
            SELECT 1
            FROM unnest(con.conkey) AS k(attnum)
            JOIN pg_attribute att
              ON att.attrelid = con.conrelid
             AND att.attnum = k.attnum
                WHERE att.attname = 'tenant_id'
                    OR att.attname LIKE '%\_tenant_id' ESCAPE '\'
        )
        OR EXISTS (
            SELECT 1
            FROM unnest(con.confkey) AS k(attnum)
            JOIN pg_attribute att
              ON att.attrelid = con.confrelid
             AND att.attnum = k.attnum
                WHERE att.attname = 'tenant_id'
                    OR att.attname LIKE '%\_tenant_id' ESCAPE '\'
        )
    );

-- Drop captured FKs before type conversion.
DO $$
DECLARE
    rec RECORD;
BEGIN
    FOR rec IN
        SELECT table_schema, table_name, constraint_name
        FROM _tenant_related_fk
        ORDER BY table_schema, table_name, constraint_name
    LOOP
        BEGIN
            EXECUTE format(
                'ALTER TABLE %I.%I DROP CONSTRAINT %I',
                rec.table_schema,
                rec.table_name,
                rec.constraint_name
            );
        EXCEPTION WHEN undefined_object OR undefined_table THEN
            RAISE NOTICE '064: constraint %.% already absent', rec.table_name, rec.constraint_name;
        END;
    END LOOP;
END;
$$;

-- Convert tenants.id to VARCHAR(26) using the prepared mapping.
DO $$
BEGIN
    IF to_regclass('public.tenants') IS NULL THEN
        RETURN;
    END IF;

    EXECUTE '
        ALTER TABLE public.tenants
        ALTER COLUMN id TYPE VARCHAR(26)
        USING CASE
                WHEN id IS NULL THEN NULL
                ELSE apexmail_lookup_tenant_id(id::TEXT)
              END
    ';

    EXECUTE 'ALTER TABLE public.tenants ALTER COLUMN id DROP DEFAULT';
    EXECUTE 'ALTER TABLE public.tenants ALTER COLUMN id SET NOT NULL';

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'public.tenants'::regclass
          AND contype = 'p'
    ) THEN
        EXECUTE 'ALTER TABLE public.tenants ADD PRIMARY KEY (id)';
    END IF;
END;
$$;

-- Convert all tenant identity columns to VARCHAR(26).
DO $$
DECLARE
    rec RECORD;
BEGIN
    FOR rec IN
        SELECT ns.nspname AS table_schema,
               cls.relname AS table_name,
               att.attname AS column_name
        FROM pg_attribute att
        JOIN pg_class cls ON cls.oid = att.attrelid
        JOIN pg_namespace ns ON ns.oid = cls.relnamespace
        LEFT JOIN pg_inherits inh ON inh.inhrelid = cls.oid
        WHERE ns.nspname = 'public'
          AND inh.inhrelid IS NULL
          AND cls.relkind IN ('r', 'p')
          AND att.attnum > 0
          AND NOT att.attisdropped
          AND (
                att.attname = 'tenant_id'
                OR att.attname LIKE '%\_tenant_id' ESCAPE '\'
              )
          AND att.atttypid IN ('uuid'::regtype, 'text'::regtype, 'varchar'::regtype)
        ORDER BY ns.nspname, cls.relname, att.attname
    LOOP
        EXECUTE format(
            'ALTER TABLE %I.%I ALTER COLUMN %I TYPE VARCHAR(26) '
          || 'USING CASE '
          || '        WHEN %I IS NULL THEN NULL '
                    || '        ELSE apexmail_lookup_tenant_id(%I::TEXT) '
          || '     END',
            rec.table_schema,
            rec.table_name,
            rec.column_name,
            rec.column_name,
            rec.column_name
        );
    END LOOP;
END;
$$;

-- Recreate all previously captured tenant-related FKs.
DO $$
DECLARE
    rec RECORD;
BEGIN
    FOR rec IN
        SELECT table_schema, table_name, constraint_name, constraint_def
        FROM _tenant_related_fk
        ORDER BY table_schema, table_name, constraint_name
    LOOP
        BEGIN
            EXECUTE format(
                'ALTER TABLE %I.%I ADD CONSTRAINT %I %s',
                rec.table_schema,
                rec.table_name,
                rec.constraint_name,
                rec.constraint_def
            );
        EXCEPTION WHEN duplicate_object OR undefined_object OR undefined_table THEN
            RAISE NOTICE '064: FK %.% not re-added (%)', rec.table_name, rec.constraint_name, SQLERRM;
        END;
    END LOOP;
END;
$$;

ALTER TABLE tenants DROP CONSTRAINT IF EXISTS chk_tenants_id_length;
ALTER TABLE tenants
    ADD CONSTRAINT chk_tenants_id_length
    CHECK (char_length(id) BETWEEN 1 AND 26);

COMMENT ON COLUMN tenants.id IS
    'Canonical tenant identifier, standardized to VARCHAR(26).';

DROP FUNCTION IF EXISTS apexmail_normalize_tenant_id(TEXT);
DROP FUNCTION IF EXISTS apexmail_lookup_tenant_id(TEXT);

