apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mta-ingress
  namespace: apexmail
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mta
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 25
          protocol: TCP
        - port: 587
          protocol: TCP
        - port: 465
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - port: 9090
          protocol: TCP