apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mta
  namespace: apexmail
  labels:
    app.kubernetes.io/name: mta
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mta