apiVersion: v1
kind: Service
metadata:
  name: mta
  namespace: apexmail
  labels:
    app.kubernetes.io/name: mta
    app.kubernetes.io/component: mail-server
spec:
  selector:
    app.kubernetes.io/name: mta
  type: LoadBalancer
  ports:
    - name: smtp
      port: 25
      targetPort: smtp
      protocol: TCP
    - name: submission
      port: 587
      targetPort: submission
      protocol: TCP
    - name: smtps
      port: 465
      targetPort: smtps
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP