-- Proposed migration (NOT WIRED — coordinate with the migrations owner).
--
-- Audit item K asked for lease fencing via a lease_token column. The
-- queue_jobs schema has no such column, so fail()/dead_letter() currently
-- fence on `status = 'processing'` only — the strongest guard available
-- without a schema change. That closes the re-claimed-job corruption
-- window, but two workers can still both believe they hold a lease if the
-- job is recovered and immediately re-dequeued while the old worker's
-- fail() races the new dequeue. A lease token makes the fence exact:
--
--     ALTER TABLE queue_jobs
--         ADD COLUMN lease_token UUID;
--
-- Application changes required alongside (queue-provider):
--   * dequeue generates lease_token = gen_random_uuid() and returns it on
--     the Job.
--   * complete()/fail()/dead_letter() add
--       AND lease_token = $lease_token
--     to their UPDATE ... WHERE clauses.
--   * recover_stale NULLs lease_token when it flips status.
