//! EMTA (Eesti Maksu- ja Tolliamet) e-MTA API client for automated KMD
//! VAT return filing.
//!
//! Overview
//! ========
//! The Estonian Tax and Customs Board provides the e-MTA web service for
//! electronic filing of VAT returns (Käibedeklaratsioon / KMD).  Submissions
//! use the X-Road SOAP envelope format over HTTPS.
//!
//! This module handles:
//! - Building the KMD INF XML payload from our internal [`VatKmdResult`]
//! - Submitting via HTTP POST to the configured e-MTA endpoint
//! - Parsing the acknowledgment response
//! - Storing filing status back in the `vat_kmd_returns` table
//!
//! Configuration
//! =============
//! ```ignore
//! EMTA_API_BASE_URL          = https://xroad.ee/...    # or sandbox
//! EMTA_CLIENT_CERT_PATH      = /etc/certs/emta.pem
//! EMTA_CLIENT_KEY_PATH       = /etc/certs/emta-key.pem
//! EMTA_COMPANY_REGISTRY_CODE = 12345678                # your registry code
//! EMTA_ENABLED               = true                    # toggle filing
//! ```

use reqwest::{Client as HttpClient, StatusCode};
use serde_json::Value;
use std::fs;
use std::time::Duration;
use tokio::time::sleep;
use tracing::warn;
use uuid::Uuid;

use crate::vat_kmd::{VatKmdResult, VatRateBucket};

const EMTA_MAX_SUBMISSION_ATTEMPTS: usize = 3;
const EMTA_INITIAL_RETRY_DELAY: Duration = Duration::from_millis(250);

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/// e-MTA API connection settings.
#[derive(Debug, Clone)]
pub struct EmtaConfig {
    /// Base URL for the e-MTA X-Road endpoint (production or sandbox).
    pub api_base_url: String,
    /// Path to the PEM-encoded client certificate for mutual TLS.
    pub client_cert_path: String,
    /// Path to the PEM-encoded client private key.
    pub client_key_path: String,
    /// Estonian business registry code (äriregistri kood).
    pub company_registry_code: String,
    /// Master switch — filing is only attempted when `true`.
    pub enabled: bool,
}

impl EmtaConfig {
    /// Create an [`EmtaConfig`] from environment variables with sensible
    /// defaults (all disabled by default — safe for development).
    pub fn from_env() -> Self {
        Self {
            api_base_url: std::env::var("EMTA_API_BASE_URL")
                .unwrap_or_else(|_| "https://xroad.ee".into()),
            client_cert_path: std::env::var("EMTA_CLIENT_CERT_PATH").unwrap_or_default(),
            client_key_path: std::env::var("EMTA_CLIENT_KEY_PATH").unwrap_or_default(),
            company_registry_code: std::env::var("EMTA_COMPANY_REGISTRY_CODE").unwrap_or_default(),
            enabled: std::env::var("EMTA_ENABLED")
                .ok()
                .and_then(|v| v.parse::<bool>().ok())
                .unwrap_or(false),
        }
    }
}

// ---------------------------------------------------------------------------
// Error type
// ---------------------------------------------------------------------------

/// Errors that can occur during EMTA API interactions.
#[derive(Debug)]
pub enum EmtaError {
    /// Configuration is missing or invalid.
    Config(String),
    /// HTTP transport failure.
    Http(String),
    /// API returned a non-success status.
    Api { status: u16, body: String },
    /// Could not parse the acknowledgment response.
    ResponseParse(String),
    /// Internal XML build error.
    XmlBuild(String),
    /// Client TLS certificate could not be loaded.
    Tls(String),
}

impl std::fmt::Display for EmtaError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Config(msg) => write!(f, "EMTA config error: {msg}"),
            Self::Http(msg) => write!(f, "EMTA HTTP error: {msg}"),
            Self::Api { status, body } => {
                write!(f, "EMTA API error (HTTP {status}): {body}")
            }
            Self::ResponseParse(msg) => write!(f, "EMTA response parse error: {msg}"),
            Self::XmlBuild(msg) => write!(f, "EMTA XML build error: {msg}"),
            Self::Tls(msg) => write!(f, "EMTA TLS error: {msg}"),
        }
    }
}

impl std::error::Error for EmtaError {}

// ---------------------------------------------------------------------------
// Submission result
// ---------------------------------------------------------------------------

/// Outcome of a KMD filing attempt.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct EmtaSubmissionResult {
    /// Unique submission ID generated by the e-MTA system (if acknowledged).
    pub filing_reference: Option<String>,
    /// Raw acknowledgment XML or status message.
    pub acknowledgment: String,
    /// Whether the submission was accepted.
    pub accepted: bool,
    /// Human-readable status description.
    pub status_message: String,
}

// ---------------------------------------------------------------------------
// Client
// ---------------------------------------------------------------------------

/// Client for interacting with the e-MTA API.
pub struct EmtaClient {
    config: EmtaConfig,
    http: HttpClient,
}

impl EmtaClient {
    /// Create a new [`EmtaClient`].
    ///
    /// Returns an error if EMTA is disabled or config is incomplete and the
    /// caller requested a check (validation is deferred until actual use).
    pub fn new(config: EmtaConfig, http: HttpClient) -> Self {
        Self { config, http }
    }

    /// Build a client from configuration, validating TLS material immediately
    /// when e-MTA filing is enabled.
    pub fn from_config(config: EmtaConfig) -> Result<Self, EmtaError> {
        let http = Self::build_http_client(&config)?;
        Ok(Self::new(config, http))
    }

    fn build_http_client(config: &EmtaConfig) -> Result<HttpClient, EmtaError> {
        if !config.enabled {
            return Ok(HttpClient::new());
        }

        Self::validate_required_config(config)?;
        let identity = Self::load_tls_identity(config)?;
        HttpClient::builder()
            .https_only(true)
            .identity(identity)
            .build()
            .map_err(|error| EmtaError::Tls(format!("failed to build mTLS HTTP client: {error}")))
    }

    fn validate_required_config(config: &EmtaConfig) -> Result<(), EmtaError> {
        if config.api_base_url.trim().is_empty() {
            return Err(EmtaError::Config("EMTA_API_BASE_URL is required".into()));
        }
        if config.company_registry_code.trim().is_empty() {
            return Err(EmtaError::Config(
                "EMTA_COMPANY_REGISTRY_CODE is required".into(),
            ));
        }
        if config.client_cert_path.trim().is_empty() {
            return Err(EmtaError::Config(
                "EMTA_CLIENT_CERT_PATH is required".into(),
            ));
        }
        if config.client_key_path.trim().is_empty() {
            return Err(EmtaError::Config("EMTA_CLIENT_KEY_PATH is required".into()));
        }
        Ok(())
    }

    fn load_tls_identity(config: &EmtaConfig) -> Result<reqwest::Identity, EmtaError> {
        let cert = fs::read(&config.client_cert_path).map_err(|error| {
            EmtaError::Tls(format!(
                "failed to read EMTA client certificate '{}': {error}",
                config.client_cert_path
            ))
        })?;
        let key = fs::read(&config.client_key_path).map_err(|error| {
            EmtaError::Tls(format!(
                "failed to read EMTA client private key '{}': {error}",
                config.client_key_path
            ))
        })?;

        let mut pem = Vec::with_capacity(cert.len() + key.len() + 1);
        pem.extend_from_slice(&cert);
        if !pem.ends_with(b"\n") {
            pem.push(b'\n');
        }
        pem.extend_from_slice(&key);

        reqwest::Identity::from_pem(&pem).map_err(|error| {
            EmtaError::Tls(format!(
                "failed to parse EMTA client certificate/private key PEM: {error}"
            ))
        })
    }

    /// Check whether the client is ready to submit (enabled + configured).
    pub fn is_ready(&self) -> bool {
        if !self.config.enabled {
            return false;
        }
        if self.config.api_base_url.is_empty() || self.config.company_registry_code.is_empty() {
            return false;
        }
        if self.config.client_cert_path.is_empty() || self.config.client_key_path.is_empty() {
            return false;
        }
        true
    }

    /// Submit a KMD VAT return to the e-MTA API.
    ///
    /// # Arguments
    /// * `kmd` — The KMD return result (from [`generate_kmd_return`]).
    /// * `breakdown` — The full breakdown JSON stored in `vat_kmd_returns`.
    ///
    /// # Returns
    /// An [`EmtaSubmissionResult`] with the filing acknowledgment.
    pub async fn submit_kmd_return(
        &self,
        kmd: &VatKmdResult,
        breakdown: &Value,
        kmd_id: Uuid,
    ) -> Result<EmtaSubmissionResult, EmtaError> {
        if !self.is_ready() {
            return Err(EmtaError::Config(
                "EMTA is disabled or not configured. Set EMTA_ENABLED=true and \
                 provide EMTA_API_BASE_URL and EMTA_COMPANY_REGISTRY_CODE."
                    .into(),
            ));
        }

        // 1. Build the KMD INF XML payload.
        let xml_body = self.build_kmd_inf_xml(kmd, breakdown)?;

        // 2. Build the X-Road SOAP envelope.
        let soap_envelope = self.wrap_in_xroad_soap(&xml_body, kmd, kmd_id);

        // 3. POST to the e-MTA endpoint.
        let url = format!(
            "{}/api/v1/kmd/submit",
            self.config.api_base_url.trim_end_matches('/')
        );

        let idempotency_key = Self::submission_idempotency_key(kmd_id);
        let body = self
            .post_submission_with_retry(&url, &soap_envelope, &idempotency_key)
            .await?;

        // 4. Parse the acknowledgment.
        let result = self.parse_acknowledgment(&body, kmd_id)?;

        Ok(result)
    }

    async fn post_submission_with_retry(
        &self,
        url: &str,
        soap_envelope: &str,
        idempotency_key: &str,
    ) -> Result<String, EmtaError> {
        let mut last_transport_error = None;

        for attempt in 0..EMTA_MAX_SUBMISSION_ATTEMPTS {
            let response = self
                .http
                .post(url)
                .header("Content-Type", "text/xml; charset=utf-8")
                .header("SOAPAction", "submitKmdReturn")
                .header("Idempotency-Key", idempotency_key)
                .header("X-Idempotency-Key", idempotency_key)
                .body(soap_envelope.to_owned())
                .send()
                .await;

            match response {
                Ok(response) => {
                    let status = response.status();
                    let body = response.text().await.map_err(|error| {
                        EmtaError::Http(format!("Failed to read response body: {error}"))
                    })?;

                    if status.is_success() {
                        return Ok(body);
                    }

                    if Self::is_retryable_status(status)
                        && attempt + 1 < EMTA_MAX_SUBMISSION_ATTEMPTS
                    {
                        let delay = Self::submission_retry_delay(attempt);
                        warn!(
                            status = status.as_u16(),
                            attempt = attempt + 1,
                            max_attempts = EMTA_MAX_SUBMISSION_ATTEMPTS,
                            delay_ms = delay.as_millis(),
                            idempotency_key = %idempotency_key,
                            "retrying transient EMTA submission failure"
                        );
                        sleep(delay).await;
                        continue;
                    }

                    return Err(EmtaError::Api {
                        status: status.as_u16(),
                        body,
                    });
                }
                Err(error) => {
                    if attempt + 1 < EMTA_MAX_SUBMISSION_ATTEMPTS {
                        let delay = Self::submission_retry_delay(attempt);
                        warn!(
                            error = %error,
                            attempt = attempt + 1,
                            max_attempts = EMTA_MAX_SUBMISSION_ATTEMPTS,
                            delay_ms = delay.as_millis(),
                            idempotency_key = %idempotency_key,
                            "retrying EMTA submission after transport error"
                        );
                        last_transport_error = Some(error.to_string());
                        sleep(delay).await;
                        continue;
                    }

                    return Err(EmtaError::Http(format!("Request failed: {error}")));
                }
            }
        }

        Err(EmtaError::Http(format!(
            "Request failed after {EMTA_MAX_SUBMISSION_ATTEMPTS} attempts: {}",
            last_transport_error.unwrap_or_else(|| "unknown transport error".into())
        )))
    }

    fn submission_idempotency_key(kmd_id: Uuid) -> String {
        format!("kmd-return-{kmd_id}")
    }

    fn submission_retry_delay(attempt: usize) -> Duration {
        EMTA_INITIAL_RETRY_DELAY.saturating_mul(1 << attempt.min(6))
    }

    fn is_retryable_status(status: StatusCode) -> bool {
        status.is_server_error()
            || matches!(
                status,
                StatusCode::REQUEST_TIMEOUT | StatusCode::TOO_MANY_REQUESTS
            )
    }

    /// Check the filing status of a previously submitted KMD return.
    pub async fn check_submission_status(
        &self,
        filing_reference: &str,
    ) -> Result<String, EmtaError> {
        if !self.is_ready() {
            return Err(EmtaError::Config(
                "EMTA is disabled or not configured".into(),
            ));
        }

        let url = format!(
            "{}/api/v1/kmd/status/{}",
            self.config.api_base_url.trim_end_matches('/'),
            filing_reference
        );

        let response = self
            .http
            .get(&url)
            .send()
            .await
            .map_err(|e| EmtaError::Http(format!("Status check failed: {e}")))?;

        let status = response.status();
        let body = response
            .text()
            .await
            .map_err(|e| EmtaError::Http(format!("Failed to read status body: {e}")))?;

        if !status.is_success() {
            return Err(EmtaError::Api {
                status: status.as_u16(),
                body,
            });
        }

        Ok(body)
    }

    // ------------------------------------------------------------------
    // XML builders
    // ------------------------------------------------------------------

    /// Build the KMD INF XML document (the actual VAT return data).
    ///
    /// The KMD INF XML follows the EMTA XSD schema for the KMD form,
    /// containing lines 1–7 (sales, VAT, adjustments).
    fn build_kmd_inf_xml(
        &self,
        kmd: &VatKmdResult,
        _breakdown: &Value,
    ) -> Result<String, EmtaError> {
        let registry_code = self.escape_xml(&self.config.company_registry_code);
        let period_start = format!("{:04}-{:02}-01", kmd.tax_year, kmd.tax_month);
        // Compute the last calendar day of the tax month for the filing period.
        // This ensures each monthly filing reports the correct period end date
        // (e.g. January → 01-31, February → 02-28/29, December → 12-31).
        let period_end = match kmd.tax_month {
            1 | 3 | 5 | 7 | 8 | 10 | 12 => {
                format!("{:04}-{:02}-31", kmd.tax_year, kmd.tax_month)
            }
            4 | 6 | 9 | 11 => {
                format!("{:04}-{:02}-30", kmd.tax_year, kmd.tax_month)
            }
            2 => {
                let feb_days = if kmd.tax_year % 4 == 0
                    && (kmd.tax_year % 100 != 0 || kmd.tax_year % 400 == 0)
                {
                    29
                } else {
                    28
                };
                format!("{:04}-02-{:02}", kmd.tax_year, feb_days)
            }
            _ => unreachable!("tax_month must be 1–12"),
        };

        // Extract rate buckets
        let rate_24_taxable = Self::rate_sum(&kmd.rates, 24.0, None);
        let rate_24_vat = Self::rate_vat_sum(&kmd.rates, 24.0, None);
        let rate_0_reverse_charge = Self::rate_sum(&kmd.rates, 0.0, Some("reverse_charge"));
        let rate_0_non_eu = Self::rate_sum(&kmd.rates, 0.0, Some("non_eu"));

        // The XML header declares EUR and the KMD XSD expects euro DECIMALS
        // (2-fraction dot format) — the internal integer-cents values MUST
        // be divided by 100 at this boundary. Interpolating raw cents used
        // to overstate the filed return 100× (audit 1.3). Integer math
        // only (same shape as the e-arve renderer's
        // cents_to_decimal_string).
        let total_taxable = Self::cents_to_euro_decimal(kmd.total_taxable_cents);
        let total_vat = Self::cents_to_euro_decimal(kmd.total_vat_cents);

        let xml = format!(
            r#"<?xml version="1.0" encoding="UTF-8"?>
<KMDInf xmlns="http://www.emta.ee/xml/kmd/inf/v1"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.emta.ee/xml/kmd/inf/v1 kmd-inf-v1.xsd">
  <Header>
    <SubmissionType>ORIGINAL</SubmissionType>
    <PeriodStart>{period_start}</PeriodStart>
    <PeriodEnd>{period_end}</PeriodEnd>
    <Currency>EUR</Currency>
    <CompanyRegistryCode>{registry_code}</CompanyRegistryCode>
    <SubmissionDate>{now_rfc3339}</SubmissionDate>
  </Header>
  <Body>
    <!-- Line 1: Taxable turnover (24% VAT) -->
    <Line number="1">
      <Amount>{rate_24_taxable}</Amount>
      <Description>Müük Eestis 24% käibemaksumääraga</Description>
    </Line>
    <!-- Line 2: Output VAT (24%) -->
    <Line number="2">
      <Amount>{rate_24_vat}</Amount>
      <Description>Käibemaks 24%</Description>
    </Line>
    <!-- Line 3: Zero-rated supplies (EU reverse charge + non-EU exports) -->
    <Line number="3">
      <Amount>{zero_rated}</Amount>
      <Description>0% käibemaksumääraga maksustatud käive</Description>
    </Line>
    <!-- Summary -->
    <TotalTaxableTurnover>{total_taxable}</TotalTaxableTurnover>
    <TotalVatLiability>{total_vat}</TotalVatLiability>
    <InvoiceCount>{invoice_count}</InvoiceCount>
  </Body>
</KMDInf>"#,
            period_start = period_start,
            period_end = period_end,
            registry_code = registry_code,
            now_rfc3339 = chrono::Utc::now().to_rfc3339(),
            rate_24_taxable = Self::cents_to_euro_decimal(rate_24_taxable),
            rate_24_vat = Self::cents_to_euro_decimal(rate_24_vat),
            zero_rated = Self::cents_to_euro_decimal(rate_0_reverse_charge + rate_0_non_eu),
            total_taxable = total_taxable,
            total_vat = total_vat,
            invoice_count = kmd.invoice_count,
        );

        Ok(xml)
    }

    /// Wrap the KMD INF XML in an X-Road SOAP envelope.
    fn wrap_in_xroad_soap(&self, inner_xml: &str, _kmd: &VatKmdResult, kmd_id: Uuid) -> String {
        let registry_code = self.escape_xml(&self.config.company_registry_code);
        let kmd_id_str = kmd_id.to_string();
        let _now = chrono::Utc::now();

        format!(
            r#"<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
               xmlns:xrd="http://x-road.ee/xsd/x-road.xsd"
               xmlns:id="http://x-road.ee/xsd/identifier.xsd">
  <soap:Header>
    <xrd:client id:objectType="MEMBER">
      <id:xRoadInstance>EE</id:xRoadInstance>
      <id:memberClass>COM</id:memberClass>
      <id:memberCode>{registry_code}</id:memberCode>
    </xrd:client>
    <xrd:service id:objectType="SERVICE">
      <id:xRoadInstance>EE</id:xRoadInstance>
      <id:memberClass>GOV</id:memberClass>
      <id:memberCode>70000317</id:memberCode>
      <id:subsystemCode>emta</id:subsystemCode>
      <id:serviceCode>submitKmdReturn</id:serviceCode>
      <id:serviceVersion>v1</id:serviceVersion>
    </xrd:service>
    <xrd:userId>SYSTEM</xrd:userId>
    <xrd:id>{kmd_id_str}</xrd:id>
    <xrd:protocolVersion>4.0</xrd:protocolVersion>
  </soap:Header>
  <soap:Body>
    <kmd:submitKmdReturnRequest xmlns:kmd="http://www.emta.ee/xml/kmd/v1">
      <kmd:returnData>
{inner_xml}
      </kmd:returnData>
    </kmd:submitKmdReturnRequest>
  </soap:Body>
</soap:Envelope>"#,
            registry_code = registry_code,
            kmd_id_str = kmd_id_str,
            inner_xml = inner_xml,
        )
    }

    /// Parse the SOAP acknowledgment response.
    fn parse_acknowledgment(
        &self,
        response_xml: &str,
        _kmd_id: Uuid,
    ) -> Result<EmtaSubmissionResult, EmtaError> {
        // Extract filing reference from the response.
        let filing_reference = Self::extract_xml_tag(
            response_xml,
            "<xrd:filingReference>",
            "</xrd:filingReference>",
        )
        .or_else(|| Self::extract_xml_tag(response_xml, "<filingReference>", "</filingReference>"))
        .or_else(|| Self::extract_xml_tag(response_xml, "<FilingReference>", "</FilingReference>"));

        let accepted = Self::extract_xml_tag(response_xml, "<xrd:accepted>", "</xrd:accepted>")
            .or_else(|| Self::extract_xml_tag(response_xml, "<accepted>", "</accepted>"))
            .or_else(|| Self::extract_xml_tag(response_xml, "<Accepted>", "</Accepted>"));

        let status_message =
            Self::extract_xml_tag(response_xml, "<xrd:statusMessage>", "</xrd:statusMessage>")
                .or_else(|| {
                    Self::extract_xml_tag(response_xml, "<statusMessage>", "</statusMessage>")
                })
                .or_else(|| {
                    Self::extract_xml_tag(response_xml, "<StatusMessage>", "</StatusMessage>")
                })
                .unwrap_or_else(|| {
                    // Fall back to returning a snippet of the response.
                    let snippet = if response_xml.len() > 200 {
                        &response_xml[..200]
                    } else {
                        response_xml
                    };
                    format!("Received (unparsed): {snippet}")
                });

        let is_accepted = accepted
            .as_deref()
            .map(|v| v.trim().eq_ignore_ascii_case("true"))
            .unwrap_or(false);

        Ok(EmtaSubmissionResult {
            filing_reference,
            acknowledgment: response_xml.to_string(),
            accepted: is_accepted,
            status_message,
        })
    }

    // ------------------------------------------------------------------
    // helpers
    // ------------------------------------------------------------------

    /// Simple XML tag content extractor (case‑sensitive, no namespace
    /// awareness — sufficient for the well-known EMTA response fields).
    fn extract_xml_tag(xml: &str, open_tag: &str, close_tag: &str) -> Option<String> {
        let start = xml.find(open_tag)?;
        let value_start = start + open_tag.len();
        let end = xml[value_start..].find(close_tag)?;
        Some(xml[value_start..value_start + end].to_string())
    }

    /// Escape text for inclusion in an XML text node or attribute value.
    fn escape_xml(&self, input: &str) -> String {
        input
            .replace('&', "&amp;")
            .replace('<', "&lt;")
            .replace('>', "&gt;")
            .replace('"', "&quot;")
            .replace('\'', "&apos;")
    }

    /// Render integer cents as a euro decimal string ("15000.00") with a
    /// dot separator and exactly two fraction digits — the format the KMD
    /// XSD expects for every `<Amount>` given the header's
    /// `<Currency>EUR</Currency>`. Integer math only: money formatting
    /// must never round-trip through f64 (see money_invariants).
    fn cents_to_euro_decimal(cents: i64) -> String {
        let sign = if cents < 0 { "-" } else { "" };
        let abs = cents.unsigned_abs();
        format!("{sign}{}.{:02}", abs / 100, abs % 100)
    }

    /// Sum `taxable_amount_cents` for buckets matching a rate and optional reason.
    fn rate_sum(rates: &[VatRateBucket], rate: f64, reason: Option<&str>) -> i64 {
        rates
            .iter()
            .filter(|b| {
                b.rate == rate
                    && match reason {
                        Some(r) => b.reason.as_deref() == Some(r),
                        None => b.reason.is_none(),
                    }
            })
            .map(|b| b.taxable_amount_cents)
            .sum()
    }

    /// Sum `vat_amount_cents` for buckets matching a rate and optional reason.
    fn rate_vat_sum(rates: &[VatRateBucket], rate: f64, reason: Option<&str>) -> i64 {
        rates
            .iter()
            .filter(|b| {
                b.rate == rate
                    && match reason {
                        Some(r) => b.reason.as_deref() == Some(r),
                        None => b.reason.is_none(),
                    }
            })
            .map(|b| b.vat_amount_cents)
            .sum()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_kmd_result() -> VatKmdResult {
        VatKmdResult {
            tax_year: 2026,
            tax_month: 4,
            invoice_count: 42,
            tenant_count: 5,
            total_taxable_cents: 1_500_000,
            total_vat_cents: 360_000,
            rates: vec![
                VatRateBucket {
                    rate: 24.0,
                    taxable_amount_cents: 1_200_000,
                    vat_amount_cents: 288_000,
                    reason: None,
                    invoice_count: 30,
                },
                VatRateBucket {
                    rate: 0.0,
                    taxable_amount_cents: 200_000,
                    vat_amount_cents: 0,
                    reason: Some("reverse_charge".into()),
                    invoice_count: 8,
                },
                VatRateBucket {
                    rate: 0.0,
                    taxable_amount_cents: 100_000,
                    vat_amount_cents: 0,
                    reason: Some("non_eu".into()),
                    invoice_count: 4,
                },
            ],
            excluded_other_currency: Vec::new(),
            kmd_id: Uuid::nil(),
        }
    }

    fn sample_breakdown() -> Value {
        serde_json::json!({
            "rates": [
                { "rate": 24, "taxableAmountCents": 1200000, "vatAmountCents": 288000, "invoiceCount": 30 },
                { "rate": 0,  "taxableAmountCents": 200000,  "vatAmountCents": 0,      "reason": "reverse_charge", "invoiceCount": 8 },
                { "rate": 0,  "taxableAmountCents": 100000,  "vatAmountCents": 0,      "reason": "non_eu",          "invoiceCount": 4 }
            ],
            "totalTaxableCents": 1500000,
            "totalVatCents": 360000,
            "invoiceCount": 42,
            "tenantCount": 5
        })
    }

    #[test]
    fn test_is_ready_requires_enabled_and_configured() {
        let client = EmtaClient::new(
            EmtaConfig {
                api_base_url: "".into(),
                client_cert_path: "".into(),
                client_key_path: "".into(),
                company_registry_code: "".into(),
                enabled: false,
            },
            HttpClient::new(),
        );
        assert!(!client.is_ready());

        let client = EmtaClient::new(
            EmtaConfig {
                api_base_url: "https://xroad.ee".into(),
                client_cert_path: "/certs/cert.pem".into(),
                client_key_path: "/certs/key.pem".into(),
                company_registry_code: "12345678".into(),
                enabled: true,
            },
            HttpClient::new(),
        );
        assert!(client.is_ready());
    }

    #[test]
    fn test_from_config_skips_tls_validation_when_disabled() {
        let result = EmtaClient::from_config(EmtaConfig {
            api_base_url: "https://xroad.ee".into(),
            client_cert_path: "".into(),
            client_key_path: "".into(),
            company_registry_code: "12345678".into(),
            enabled: false,
        });

        assert!(result.is_ok());
    }

    #[test]
    fn test_from_config_requires_tls_paths_when_enabled() {
        let result = EmtaClient::from_config(EmtaConfig {
            api_base_url: "https://xroad.ee".into(),
            client_cert_path: "".into(),
            client_key_path: "".into(),
            company_registry_code: "12345678".into(),
            enabled: true,
        });

        assert!(matches!(result, Err(EmtaError::Config(message)) if message.contains("CERT_PATH")));
    }

    #[test]
    fn test_from_config_reads_tls_paths_when_enabled() {
        let result = EmtaClient::from_config(EmtaConfig {
            api_base_url: "https://xroad.ee".into(),
            client_cert_path: "/definitely/missing/emta-cert.pem".into(),
            client_key_path: "/definitely/missing/emta-key.pem".into(),
            company_registry_code: "12345678".into(),
            enabled: true,
        });

        assert!(matches!(result, Err(EmtaError::Tls(message)) if message.contains("certificate")));
    }

    #[test]
    fn test_submission_idempotency_key_is_stable() {
        let kmd_id = Uuid::parse_str("018f3a26-01f5-7b80-a221-d6df4f6a9c42").unwrap();
        assert_eq!(
            EmtaClient::submission_idempotency_key(kmd_id),
            "kmd-return-018f3a26-01f5-7b80-a221-d6df4f6a9c42"
        );
    }

    #[test]
    fn test_submission_retry_policy_is_exponential_and_transient_only() {
        assert_eq!(
            EmtaClient::submission_retry_delay(0),
            Duration::from_millis(250)
        );
        assert_eq!(
            EmtaClient::submission_retry_delay(1),
            Duration::from_millis(500)
        );
        assert_eq!(
            EmtaClient::submission_retry_delay(2),
            Duration::from_millis(1000)
        );

        assert!(EmtaClient::is_retryable_status(
            StatusCode::INTERNAL_SERVER_ERROR
        ));
        assert!(EmtaClient::is_retryable_status(
            StatusCode::TOO_MANY_REQUESTS
        ));
        assert!(!EmtaClient::is_retryable_status(StatusCode::BAD_REQUEST));
    }

    #[test]
    fn test_build_kmd_inf_xml_contains_expected_lines() {
        let config = EmtaConfig {
            api_base_url: "https://xroad.ee".into(),
            client_cert_path: "/certs/cert.pem".into(),
            client_key_path: "/certs/key.pem".into(),
            company_registry_code: "12345678".into(),
            enabled: true,
        };
        let http = HttpClient::new();
        let client = EmtaClient::new(config, http);

        let kmd = sample_kmd_result();
        let breakdown = sample_breakdown();
        let xml = client.build_kmd_inf_xml(&kmd, &breakdown).unwrap();

        // Contains the KMDInf root element
        assert!(xml.contains("<KMDInf"), "Should have KMDInf root");

        // Contains registry code
        assert!(xml.contains("12345678"), "Should contain registry code");

        // Contains period markers
        assert!(xml.contains("2026-04-01"), "Should contain period start");
        assert!(xml.contains("<Line number=\"1\">"), "Should have line 1");
        assert!(xml.contains("<Line number=\"2\">"), "Should have line 2");
        assert!(xml.contains("<Line number=\"3\">"), "Should have line 3");

        // Contains correct amounts — in EUROS (2-decimal dot format), not
        // raw cents: the header declares EUR and the XSD expects decimals.
        assert!(xml.contains("12000.00"), "Should contain 24% taxable amount in euros");
        assert!(xml.contains("2880.00"), "Should contain 24% VAT amount in euros");
        assert!(
            xml.contains("3000.00"),
            "Should contain zero-rated amount in euros (200k + 100k cents)"
        );
        assert!(xml.contains("15000.00"), "Should contain total taxable in euros");
        assert!(xml.contains("3600.00"), "Should contain total VAT in euros");
        assert!(xml.contains("42"), "Should contain invoice count");
        // The raw cent values must NOT appear in any amount element.
        assert!(!xml.contains("<Amount>1200000</Amount>"));
        assert!(!xml.contains("<TotalVatLiability>360000</TotalVatLiability>"));
    }

    // ------------------------------------------------------------------
    // Audit 1.3 — the KMD XML must divide cents by 100. A one-env flip of
    // EMTA_ENABLED used to file a 100× overstated return.
    // ------------------------------------------------------------------

    #[test]
    fn test_cents_to_euro_decimal_known_values() {
        // 1 500 000 cents = €15 000.00 (the sample return's taxable base).
        assert_eq!(EmtaClient::cents_to_euro_decimal(1_500_000), "15000.00");
        // 360 000 cents = €3 600.00 output VAT.
        assert_eq!(EmtaClient::cents_to_euro_decimal(360_000), "3600.00");
        // Fractional cents render with exactly two digits.
        assert_eq!(EmtaClient::cents_to_euro_decimal(1), "0.01");
        assert_eq!(EmtaClient::cents_to_euro_decimal(5), "0.05");
        assert_eq!(EmtaClient::cents_to_euro_decimal(99), "0.99");
        assert_eq!(EmtaClient::cents_to_euro_decimal(100), "1.00");
        assert_eq!(EmtaClient::cents_to_euro_decimal(0), "0.00");
        // Negative amounts (adjustments) keep the sign.
        assert_eq!(EmtaClient::cents_to_euro_decimal(-2_409), "-24.09");
    }

    #[test]
    fn test_kmd_xml_amounts_are_euros_not_cents() {
        let config = EmtaConfig {
            api_base_url: "https://xroad.ee".into(),
            client_cert_path: "".into(),
            client_key_path: "".into(),
            company_registry_code: "12345678".into(),
            enabled: true,
        };
        let client = EmtaClient::new(config, HttpClient::new());

        // A known return: 123 456 789 cents taxable, 29 629 629 cents VAT.
        let mut kmd = sample_kmd_result();
        kmd.total_taxable_cents = 123_456_789;
        kmd.total_vat_cents = 29_629_629;
        let xml = client
            .build_kmd_inf_xml(&kmd, &sample_breakdown())
            .unwrap();

        assert!(
            xml.contains("<TotalTaxableTurnover>1234567.89</TotalTaxableTurnover>"),
            "total taxable must render as euro decimals"
        );
        assert!(
            xml.contains("<TotalVatLiability>296296.29</TotalVatLiability>"),
            "total VAT must render as euro decimals"
        );
    }

    #[test]
    fn test_soap_envelope_contains_xroad_headers() {
        let config = EmtaConfig {
            api_base_url: "https://xroad.ee".into(),
            client_cert_path: "".into(),
            client_key_path: "".into(),
            company_registry_code: "12345678".into(),
            enabled: true,
        };
        let http = HttpClient::new();
        let client = EmtaClient::new(config, http);

        let kmd = sample_kmd_result();
        let breakdown = sample_breakdown();
        let inner = client.build_kmd_inf_xml(&kmd, &breakdown).unwrap();

        let envelope = client.wrap_in_xroad_soap(&inner, &kmd, Uuid::nil());

        assert!(
            envelope.contains("soap:Envelope"),
            "Should be SOAP envelope"
        );
        assert!(envelope.contains("x-road.ee"), "Should reference X-Road");
        assert!(
            envelope.contains("submitKmdReturn"),
            "Should reference service"
        );
        assert!(
            envelope.contains("12345678"),
            "Should contain client member code"
        );
        assert!(
            envelope.contains("70000317"),
            "Should contain EMTA member code"
        );
        assert!(
            envelope.contains("<kmd:submitKmdReturnRequest"),
            "Should have request wrapper"
        );
        assert!(
            envelope.contains("<KMDInf"),
            "Should contain inner KMD INF XML"
        );
    }

    #[test]
    fn test_parse_acknowledgment_accepted() {
        let config = EmtaConfig {
            api_base_url: "https://xroad.ee".into(),
            client_cert_path: "".into(),
            client_key_path: "".into(),
            company_registry_code: "12345678".into(),
            enabled: true,
        };
        let http = HttpClient::new();
        let client = EmtaClient::new(config, http);

        let response = r#"<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <xrd:submitKmdReturnResponse>
      <xrd:filingReference>EMTA-2026-04-12345</xrd:filingReference>
      <xrd:accepted>true</xrd:accepted>
      <xrd:statusMessage>Return accepted and registered</xrd:statusMessage>
    </xrd:submitKmdReturnResponse>
  </soap:Body>
</soap:Envelope>"#;

        let result = client.parse_acknowledgment(response, Uuid::nil()).unwrap();
        assert_eq!(
            result.filing_reference.as_deref(),
            Some("EMTA-2026-04-12345")
        );
        assert!(result.accepted);
        assert_eq!(result.status_message, "Return accepted and registered");
    }

    #[test]
    fn test_parse_acknowledgment_rejected() {
        let config = EmtaConfig {
            api_base_url: "https://xroad.ee".into(),
            client_cert_path: "".into(),
            client_key_path: "".into(),
            company_registry_code: "12345678".into(),
            enabled: true,
        };
        let http = HttpClient::new();
        let client = EmtaClient::new(config, http);

        let response = r#"<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <xrd:submitKmdReturnResponse>
      <xrd:accepted>false</xrd:accepted>
      <xrd:statusMessage>Validation failed: invalid period</xrd:statusMessage>
    </xrd:submitKmdReturnResponse>
  </soap:Body>
</soap:Envelope>"#;

        let result = client.parse_acknowledgment(response, Uuid::nil()).unwrap();
        assert!(!result.accepted);
        assert!(result.filing_reference.is_none());
        assert!(result.status_message.contains("Validation failed"));
    }

    #[test]
    fn test_parse_acknowledgment_without_namespace_prefixes() {
        let config = EmtaConfig {
            api_base_url: "https://xroad.ee".into(),
            client_cert_path: "".into(),
            client_key_path: "".into(),
            company_registry_code: "12345678".into(),
            enabled: true,
        };
        let http = HttpClient::new();
        let client = EmtaClient::new(config, http);

        let response = r#"<?xml version="1.0" encoding="UTF-8"?>
<Envelope>
  <Body>
    <submitKmdReturnResponse>
      <FilingReference>EMTA-2026-04-67890</FilingReference>
      <Accepted>true</Accepted>
      <StatusMessage>Filed successfully</StatusMessage>
    </submitKmdReturnResponse>
  </Body>
</Envelope>"#;

        let result = client.parse_acknowledgment(response, Uuid::nil()).unwrap();
        assert_eq!(
            result.filing_reference.as_deref(),
            Some("EMTA-2026-04-67890")
        );
        assert!(result.accepted);
    }

    #[test]
    fn test_rate_sum_filters_correctly() {
        let rates = sample_kmd_result().rates;
        assert_eq!(EmtaClient::rate_sum(&rates, 24.0, None), 1_200_000);
        assert_eq!(
            EmtaClient::rate_sum(&rates, 0.0, Some("reverse_charge")),
            200_000
        );
        assert_eq!(EmtaClient::rate_sum(&rates, 0.0, Some("non_eu")), 100_000);
        assert_eq!(EmtaClient::rate_sum(&rates, 0.0, None), 0); // no generic 0% bucket
        assert_eq!(EmtaClient::rate_sum(&rates, 99.0, None), 0);
    }

    #[test]
    fn test_rate_vat_sum_filters_correctly() {
        let rates = sample_kmd_result().rates;
        assert_eq!(EmtaClient::rate_vat_sum(&rates, 24.0, None), 288_000);
        assert_eq!(
            EmtaClient::rate_vat_sum(&rates, 0.0, Some("reverse_charge")),
            0
        );
        assert_eq!(EmtaClient::rate_vat_sum(&rates, 0.0, Some("non_eu")), 0);
    }

    #[test]
    fn test_escape_xml_encodes_special_chars() {
        let config = EmtaConfig {
            api_base_url: "".into(),
            client_cert_path: "".into(),
            client_key_path: "".into(),
            company_registry_code: "".into(),
            enabled: false,
        };
        let http = HttpClient::new();
        let client = EmtaClient::new(config, http);

        assert_eq!(client.escape_xml("AT&T"), "AT&amp;T");
        assert_eq!(client.escape_xml("<tag>"), "&lt;tag&gt;");
        assert_eq!(client.escape_xml("value=\"x\""), "value=&quot;x&quot;");
        assert_eq!(client.escape_xml("plain"), "plain");
    }

    #[test]
    fn test_from_env_defaults_to_disabled() {
        let config = EmtaConfig::from_env();
        // In test environment, env vars won't be set, so defaults apply.
        assert!(!config.enabled);
    }
}
