//! KiwiCaptcha widget — premium, zero-dependency proof-of-work security.
//! Developed by Bel Consulting OÜ.
//!
//! The widget renders a self-contained `<div>` with an inline `<script>` that:
//! 1. Fetches a challenge from `/api/kcaptcha/challenge`
//! 2. Solves the proof-of-work (WASM solver with a pure-JS SHA-256 fallback)
//! 3. Submits a signed solution token via a hidden input.
//!
//! The solver dispatches on the challenge's explicit `algorithm` field
//! (`"sha256"` or `"argon2id"`), never on a numeric heuristic, so it always
//! computes exactly what the server will verify.

use crate::kiwi_mark_svg;

/// The generated WASM solver + glue, embedded as a self-contained script that
/// exposes `window.__kiwiCaptchaWasm.load()` (returns the wasm exports).
/// Regenerate with `packages/kiwicaptcha-wasm/build.sh`.
// The embedded assets live INSIDE this crate (`resources/`), so `cargo
// package` verification can compile the packaged representation (audit
// round 18: reaching outside the crate broke tarball verification). The
// copies are regenerated by packages/kiwicaptcha-wasm/build.sh and pinned
// byte-identical by CI (widget-assets parity job).
const KIWI_DRIVER_JS: &str = include_str!("../resources/widget-driver.js");
const KIWI_CSS: &str = include_str!("../resources/widget.css");
const KIWI_WASM_EMBED: &str = include_str!("../resources/kiwicaptcha-wasm.js");

/// Render the premium KiwiCaptcha widget HTML block.
///
/// `endpoint` and `scope` are inserted into HTML attributes and are therefore
/// HTML-attribute-escaped (the `&`, `"`, `'`, `<`, `>` characters) so a
/// caller-supplied value can never break out of the attribute — the values
/// are also validated at the protocol layer (scope must not contain `|`).
///
/// `csp_nonce` — when [`Some`], the nonce is applied to the `<style>` and both
/// `<script>` tags (`nonce="..."`), making the widget compatible with strict
/// Content-Security-Policy deployments (`style-src 'nonce-...'`,
/// `script-src 'nonce-...'`). When `None`, no nonce attributes are emitted
/// (the widget then requires a CSP that allows the inline blocks, or an
/// application that post-processes the HTML to inject nonces — as the
/// ApexMail api-server does).
pub fn kiwi_widget_html(endpoint: &str, scope: &str, csp_nonce: Option<&str>) -> String {
    let svg = kiwi_mark_svg();
    let nonce_attr = csp_nonce
        .filter(|n| !n.is_empty())
        .map(|n| format!(" nonce=\"{}\"", html_attr_escape(n)))
        .unwrap_or_default();
    format!(
        "<style{nonce}>\n{css}\n</style>\n\
        <div class=\"kiwi-container\" data-kiwi-endpoint=\"{endpoint}\" data-kiwi-scope=\"{scope}\">\n  \
        <input type=\"hidden\" name=\"kiwi__token\" data-kiwi-token value=\"\" />\n  \
        <div class=\"kiwi-widget\" data-kiwi-widget data-state=\"idle\"\n       \
        role=\"group\" aria-label=\"KiwiCaptcha security check\">\n    \
        <div class=\"kiwi-icon-wrapper\" aria-hidden=\"true\">\n      {svg}\n      <div class=\"kiwi-glow\"></div>\n    \
        </div>\n    <div class=\"kiwi-main\">\n      <div class=\"kiwi-top\">\n        <span class=\"kiwi-label\" data-kiwi-label>Security Check</span>\n        <span class=\"kiwi-badge\" data-kiwi-badge>Idle</span>\n      </div>\n      <div class=\"kiwi-track\" role=\"progressbar\" aria-valuemin=\"0\" aria-valuemax=\"100\" aria-valuenow=\"0\">\n        <div class=\"kiwi-bar\" data-kiwi-bar></div>\n      </div>\n      <div class=\"kiwi-bottom\">\n        <p class=\"kiwi-info\" data-kiwi-info>Protected by KiwiCaptcha</p>\n        <span class=\"kiwi-timer\" data-kiwi-timer></span>\n      </div>\n    </div>\n    <span class=\"kiwi-sr-only\" data-kiwi-status role=\"status\" aria-live=\"polite\"></span>\n  </div>\n\
        </div>\n\
        <script{nonce}>\n{wasm}\n</script>\n\
        <script{nonce}>\n{driver}\n</script>",
        nonce = nonce_attr,
        css = KIWI_CSS,
        svg = svg,
        endpoint = html_attr_escape(endpoint),
        scope = html_attr_escape(scope),
        wasm = KIWI_WASM_EMBED,
        driver = KIWI_DRIVER_JS,
    )
}

/// Escape a value for safe interpolation inside a double-quoted HTML
/// attribute. Handles the five characters that terminate or alter an
/// attribute value.
fn html_attr_escape(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for c in value.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            _ => out.push(c),
        }
    }
    out
}

/// Compatibility wrapper for default settings (no CSP nonce).
pub fn kiwi_widget_html_default() -> String {
    kiwi_widget_html("/api/kcaptcha/challenge", "login", None)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn widget_escapes_endpoint_and_scope_attributes() {
        // XSS: a caller-supplied scope/endpoint containing quotes or markup
        // must never break out of the data-* attribute.
        let html = kiwi_widget_html(
            "/x\"><script>alert(1)</script>",
            "login\"><img src=x onerror=alert(2)>",
            None,
        );

        assert!(html
            .contains("data-kiwi-endpoint=\"/x&quot;&gt;&lt;script&gt;alert(1)&lt;/script&gt;\""));
        assert!(
            html.contains("data-kiwi-scope=\"login&quot;&gt;&lt;img src=x onerror=alert(2)&gt;\"")
        );
        // No raw attacker markup survives.
        assert!(!html.contains("<script>alert(1)"));
        assert!(!html.contains("<img src=x"));
    }

    #[test]
    fn widget_contains_all_required_elements() {
        let html = kiwi_widget_html_default();
        assert!(html.contains("data-kiwi-widget"));
        assert!(html.contains("data-kiwi-token"));
        assert!(html.contains("data-kiwi-endpoint=\"/api/kcaptcha/challenge\""));
        assert!(html.contains("data-kiwi-scope=\"login\""));
        assert!(html.contains("window.KiwiCaptcha"));
        assert!(html.contains("KIWI_WASM_B64"));
        assert!(html.contains(".kiwi-container"));
    }

    #[test]
    fn widget_applies_csp_nonce_to_style_and_scripts() {
        let html = kiwi_widget_html("/challenge", "login", Some("abc123XYZ"));
        // Nonce on the style tag and BOTH script tags.
        assert!(html.contains("<style nonce=\"abc123XYZ\">"));
        assert!(html.contains("<script nonce=\"abc123XYZ\">"));
        assert_eq!(html.matches("<script nonce=\"abc123XYZ\">").count(), 2);
        // No nonce-less style/script remains.
        assert!(!html.contains("<style>\n"));
        assert!(!html.contains("<script>\n"));
    }

    #[test]
    fn widget_omits_nonce_attribute_when_none() {
        let html = kiwi_widget_html("/challenge", "login", None);
        assert!(html.contains("<style>"));
        assert!(!html.contains("nonce="));
        // Empty-string nonce is treated as absent.
        let html2 = kiwi_widget_html("/challenge", "login", Some(""));
        assert!(!html2.contains("nonce="));
    }

    #[test]
    fn widget_escapes_nonce_value() {
        // A nonce derived from attacker input must not break out of the tag.
        let html = kiwi_widget_html("/challenge", "login", Some("x\" onload=\"alert(1)"));
        assert!(html.contains("nonce=\"x&quot; onload=&quot;alert(1)\""));
        assert!(!html.contains("onload=\"alert(1)"));
    }

    #[test]
    fn widget_renderer_contract_matches_the_driver_dom() {
        // Audit round 15: the Rust-generated markup must stay in structural
        // parity with the Symfony Twig widget — any divergence breaks
        // accessibility and the driver's element contract. Pinned here so
        // the accessibility structure cannot silently drift again.
        let html = kiwi_widget_html_default();

        // No root id: multiple widgets on one page must never collide, and
        // the driver locates elements via data attributes/classes only.
        assert!(
            !html.contains("kiwi-container\" id="),
            "the container must not carry an id (duplicate-id hazard)"
        );

        // Neutral group semantics: no checkbox role, no aria-checked, no
        // whole-widget live region, no focus target (the Retry button is
        // the focusable control).
        assert!(
            html.contains("role=\"group\""),
            "the widget is a passive group, never a checkbox"
        );
        assert!(
            !html.contains("role=\"checkbox\""),
            "checkbox semantics were removed (round 13/15)"
        );
        assert!(!html.contains("aria-checked"), "no checkbox state");
        assert_eq!(
            html.matches("aria-live=\"polite\"").count(),
            1,
            "the ONLY aria-live region is the dedicated status announcer"
        );
        assert!(
            !html.contains("tabindex=\"0\""),
            "the widget itself is not focusable"
        );
        assert!(
            html.contains("aria-label=\"KiwiCaptcha security check\""),
            "explicit accessible name"
        );

        // The ONLY live region is the dedicated status announcer the driver
        // queries ([data-kiwi-status]), inside the widget subtree so
        // W.querySelector finds it.
        assert!(
            html.contains("data-kiwi-status role=\"status\" aria-live=\"polite\""),
            "dedicated status announcer present"
        );

        // The decorative mascot is hidden from assistive technology.
        assert!(
            html.contains("kiwi-icon-wrapper\" aria-hidden=\"true\""),
            "icon hidden from AT"
        );
    }
}
