[package]
name = "smtp-edge"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "smtp-edge"
path = "src/main.rs"

[dependencies]
mail-common = { path = "../mail-common" }
mail-proto = { path = "../mail-proto" }

tokio.workspace = true
async-trait.workspace = true
futures.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
thiserror.workspace = true
bytes.workspace = true
chrono.workspace = true
uuid.workspace = true
clap.workspace = true
tokio-rustls.workspace = true
rustls.workspace = true
rustls-pemfile = "2"
trust-dns-resolver.workspace = true
mail-parser.workspace = true
mail-auth.workspace = true
