#!/usr/bin/env python3
"""Generate tools/repo-map.md FROM SOURCE.

The hand-written May-era repo map drifted the moment the tree moved (crate
counts, Dockerfile targets, migration counts, route baselines). This script
regenerates the map deterministically from the manifests that own those
facts — stdlib only, no clock-stamped output, so the generated bytes only
change when the tree does:

  * Cargo workspace members .......... services/mail-server/Cargo.toml
                                       (globs expanded against the tree; each
                                       member classified binary/library from
                                       its own Cargo.toml)
  * Dockerfile runtime targets ....... services/mail-server/Dockerfile
                                       (`FROM runtime-base AS <target>`)
  * compose services ................. docker-compose.yml +
                                       docker-compose.prod.yml (2-space keys
                                       under the top-level `services:` block)
  * capability stages ................ docs/development/capability-registry.json
  * schema migrations ................ services/mail-server/migrations/*.sql
                                       (count + latest file, the `ls | tail`)
  * UI route baseline ................ docs/development/ui-baseline-manifest.json
                                       (per-surface routeCount + total)

Usage:
  python3 tools/generate_repo_map.py            # rewrite tools/repo-map.md
  python3 tools/generate_repo_map.py --check    # exit 1 on drift, write nothing
  python3 tools/generate_repo_map.py --out PATH # write to PATH instead

ci/stages/validate.sh runs --check so a stale map fails the validate stage
(the coverage-catalog pattern: regenerate to a temp file, compare, fail).
"""
from __future__ import annotations

import json
import re
import sys
import tempfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WORKSPACE_MANIFEST = ROOT / "services/mail-server/Cargo.toml"
CRATES_DIR = ROOT / "services/mail-server/crates"
DOCKERFILE = ROOT / "services/mail-server/Dockerfile"
COMPOSE_DEV = ROOT / "docker-compose.yml"
COMPOSE_PROD = ROOT / "docker-compose.prod.yml"
REGISTRY = ROOT / "docs/development/capability-registry.json"
MIGRATIONS = ROOT / "services/mail-server/migrations"
TOOL_MIGRATIONS = ROOT / "tools/migrations"
UI_MANIFEST = ROOT / "docs/development/ui-baseline-manifest.json"
OUTPUT = ROOT / "tools/repo-map.md"

HEADER = """# ApexMail — Repository Map (generated)

> GENERATED FILE — do not edit by hand. `tools/generate_repo_map.py`
> regenerates this document from the source manifests listed per section;
> `ci/stages/validate.sh` runs the generator with `--check` and fails the
> validate stage when this file drifts from the tree.
"""


def workspace_members() -> list[str]:
    """Expand the workspace `members` globs (tomllib parses the table; the
    globs are resolved against the crate root so the map reflects the TREE,
    not just the manifest strings)."""
    data = tomllib.loads(WORKSPACE_MANIFEST.read_text())
    members: list[str] = []
    for pattern in data.get("workspace", {}).get("members", []):
        pattern = pattern.rstrip("/")
        if any(ch in pattern for ch in "*?[]"):
            matches = sorted(str(p.relative_to(WORKSPACE_MANIFEST.parent)) for p in WORKSPACE_MANIFEST.parent.glob(pattern))
        elif (WORKSPACE_MANIFEST.parent / pattern).is_dir():
            matches = [pattern]
        else:
            matches = []  # a listed member missing from the tree is real drift;
            # the validate stage's cargo-metadata-free check keeps it visible
            # here by simply omitting it.
        for m in matches:
            if m not in members:
                members.append(m)
    return members


def crate_kind(rel: str) -> str:
    """`binary` when the member declares [[bin]] targets, else `library`."""
    manifest = WORKSPACE_MANIFEST.parent / rel / "Cargo.toml"
    if manifest.is_file():
        try:
            data = tomllib.loads(manifest.read_text())
        except tomllib.TOMLDecodeError:
            return "library"
        if data.get("bin"):
            return "binary"
    if (WORKSPACE_MANIFEST.parent / rel / "src/bin").is_dir():
        return "binary"
    return "library"


def dockerfile_runtime_targets() -> list[str]:
    return re.findall(r"^FROM runtime-base AS ([A-Za-z0-9_-]+)\s*$", DOCKERFILE.read_text(), re.M)


def compose_services(path: Path) -> list[str]:
    """Top-level `services:` block, 2-space-indented keys. A tiny line parser
    keeps this stdlib-only (no YAML dependency) and deterministic."""
    services: list[str] = []
    in_services = False
    for line in path.read_text().splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if re.match(r"^\S", line):  # any top-level key ends the block
            in_services = line.rstrip() == "services:"
            continue
        if in_services:
            m = re.match(r"^  ([A-Za-z0-9_-]+):\s*(?:#.*)?$", line)
            if m:
                services.append(m.group(1))
    return services


def capability_stages() -> tuple[list[str], list[tuple[str, str, str]]]:
    data = json.loads(REGISTRY.read_text())
    ladder = data["lifecycle_ladder"]
    rows = []
    for entry in data["capabilities"]:
        gate = (entry.get("evidence") or {}).get("env_gate") or {}
        gate_name = gate.get("name") if isinstance(gate, dict) else None
        rows.append((entry["capability"], entry["stage"], gate_name or "—"))
    rows.sort(key=lambda row: (ladder.index(row[1]) if row[1] in ladder else len(ladder), row[0]))
    return ladder, rows


def migration_facts() -> tuple[int, str, int]:
    sqls = sorted(MIGRATIONS.glob("*.sql"))
    tool_sqls = sorted(TOOL_MIGRATIONS.glob("*.sql")) if TOOL_MIGRATIONS.is_dir() else []
    return len(sqls), (sqls[-1].name if sqls else "—"), len(tool_sqls)


def ui_route_counts() -> tuple[list[tuple[str, int, int]], int]:
    data = json.loads(UI_MANIFEST.read_text())
    rows = [(s["id"], s["routeCount"], len(s["routes"])) for s in data["surfaces"]]
    return rows, sum(r[2] for r in rows)


def build_map() -> str:
    lines: list[str] = [HEADER, ""]

    members = workspace_members()
    binaries = [m for m in members if crate_kind(m) == "binary"]
    libraries = [m for m in members if crate_kind(m) != "binary"]
    lines += [
        "## 1. Cargo workspace (`services/mail-server`)",
        "",
        f"{len(members)} workspace members: {len(binaries)} binary crates, "
        f"{len(libraries)} library crates.",
        "",
        "**Binary crates:** " + ", ".join(f"`{m}`" for m in binaries),
        "",
        "**Library crates:** " + ", ".join(f"`{m}`" for m in libraries),
        "",
    ]

    targets = dockerfile_runtime_targets()
    lines += [
        "## 2. Dockerfile runtime targets",
        "",
        f"{len(targets)} `FROM runtime-base AS <target>` stages in "
        "`services/mail-server/Dockerfile` (the deploy surfaces the "
        "capability-registry evidence cites):",
        "",
    ]
    lines += [f"- `{t}`" for t in targets]
    lines += [""]

    dev = compose_services(COMPOSE_DEV)
    prod = compose_services(COMPOSE_PROD)
    prod_only = [s for s in prod if s not in dev]
    lines += [
        "## 3. Compose services",
        "",
        f"`docker-compose.yml` ({len(dev)} services): " + ", ".join(f"`{s}`" for s in dev),
        "",
        f"`docker-compose.prod.yml` adds {len(prod_only)} services: "
        + (", ".join(f"`{s}`" for s in prod_only) if prod_only else "—"),
        "",
    ]

    ladder, rows = capability_stages()
    lines += [
        "## 4. Capability registry stages",
        "",
        "Source of truth: `docs/development/capability-registry.json` "
        f"(ladder: {' → '.join(ladder)}). The gate "
        "`tools/check_capability_claims.py` proves stage >= runtime-wired "
        "evidence exists in the tree and that claim surfaces only name "
        "runtime-wired capabilities outside `[roadmap]` context.",
        "",
        "| Capability | Stage | Env gate |",
        "|---|---|---|",
    ]
    lines += [f"| {cap} | {stage} | {gate} |" for cap, stage, gate in rows]
    lines += [""]

    count, latest, tool_count = migration_facts()
    lines += [
        "## 4b. Schema migrations",
        "",
        f"`services/mail-server/migrations/`: **{count} `*.sql` files**, latest "
        f"`{latest}` (regenerated as the `ls | tail`).",
        "",
    ]
    if tool_count:
        lines += [f"`tools/migrations/`: {tool_count} `*.sql` files.", ""]

    surfaces, total = ui_route_counts()
    lines += [
        "## 5. UI route baseline",
        "",
        "Source of truth: `docs/development/ui-baseline-manifest.json` "
        "(the pinned counts live in `services/mail-server/crates/ui-foundation/"
        "src/routing.rs`):",
        "",
        "| Surface | routeCount | Routes listed |",
        "|---|---|---|",
    ]
    lines += [f"| {sid} | {rc} | {n} |" for sid, rc, n in surfaces]
    lines += ["", f"**Total: {total} routes.**", ""]

    return "\n".join(lines)


def main(argv: list[str]) -> int:
    args = list(argv)
    check = "--check" in args
    if check:
        args.remove("--check")
    out = OUTPUT
    if "--out" in args:
        i = args.index("--out")
        out = Path(args[i + 1])
        del args[i : i + 2]
    if args:
        print(__doc__.strip().splitlines()[-4], file=sys.stderr)
        return 2

    content = build_map()
    if check:
        if not out.is_file():
            print(f"repo-map drift: {out} missing — run `python3 tools/generate_repo_map.py`", file=sys.stderr)
            return 1
        with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False) as fh:
            fh.write(content)
            tmp = Path(fh.name)
        try:
            if tmp.read_text() != out.read_text():
                print(
                    f"repo-map drift: {out} is stale — regenerate with "
                    "`python3 tools/generate_repo_map.py` (source manifests "
                    "moved ahead of the map)",
                    file=sys.stderr,
                )
                return 1
        finally:
            tmp.unlink(missing_ok=True)
        print(f"repo-map: up to date ({out})")
        return 0

    out.write_text(content)
    print(f"repo-map: wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
