#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  bash tools/update-checksums.sh <name> <artifact-path> [<name> <artifact-path> ...]

Example:
  bash tools/update-checksums.sh \
    node-darwin-arm64 /tmp/node-v22.11.0-darwin-arm64.tar.gz \
    go-linux-amd64 /tmp/go1.24.2.linux-amd64.tar.gz
EOF
}

if [[ $# -eq 0 || $(( $# % 2 )) -ne 0 ]]; then
  usage
  exit 1
fi

output="tools/checksums.sha256"
tmp_file="$(mktemp)"

cleanup() {
  rm -f "$tmp_file"
}
trap cleanup EXIT

cat > "$tmp_file" <<'EOF'
# ApexMail Toolchain Checksums
# Format: name sha256hash
# Generated by: bash tools/update-checksums.sh <name> <artifact-path> [...]
# Verify a downloaded artifact with:
#   shasum -a 256 /path/to/artifact

EOF

while [[ $# -gt 0 ]]; do
  name="$1"
  artifact_path="$2"
  shift 2

  if [[ ! -f "$artifact_path" ]]; then
    echo "missing artifact: $artifact_path" >&2
    exit 1
  fi

  checksum="$(shasum -a 256 "$artifact_path" | awk '{print $1}')"
  printf '%s %s\n' "$name" "$checksum" >> "$tmp_file"
done

mv "$tmp_file" "$output"
trap - EXIT

echo "updated $output"
