#!/usr/bin/env node
// The packaged SVG is the source of truth. Generate renderer copies at
// development time; widgets make no extra request for their brand mark.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const root = fileURLToPath(new URL('../../../', import.meta.url));
const check = process.argv.includes('--check');
const read = (path) => readFileSync(join(root, path), 'utf8');
const mark = read('packages/kiwicaptcha/resources/kiwi-mark.svg').trim();
const paths = [...mark.matchAll(/<path d="([^"]+)"\s*\/>/g)].map((m) => m[1]);
if (paths.length !== 2 || !mark.includes('viewBox="0 0 64 64"')
  || /<(?:script|filter|animate|linearGradient|radialGradient)\b|\bon\w+=/.test(mark)) {
  throw new Error('The primary mark must remain a static, two-stroke SVG on the 64x64 grid.');
}
const inner = mark.replace(/^<svg[^>]*>\s*/, '').replace(/\s*<\/svg>$/, '');
const compact = mark.replace(/>\s+</g, '><');
const generated = new Map();
generated.set('packages/kiwicaptcha/resources/kiwi-lockup.svg',
  `<svg viewBox="0 0 200 40" fill="none" xmlns="http://www.w3.org/2000/svg">\n  <g transform="translate(4, 1) scale(0.56)">${inner}</g>\n  <text x="48" y="27" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="700" letter-spacing="-0.4" fill="currentColor">KiwiCaptcha</text>\n</svg>\n`);
generated.set('packages/kiwicaptcha/resources/kiwi-shield.svg',
  `<svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">\n  <path d="M16 2L6 6v8c0 7 4.5 12 10 14 5.5-2 10-7 10-14V6L16 2z" fill="currentColor" opacity="0.08"/>\n  <path d="M16 2L6 6v8c0 7 4.5 12 10 14 5.5-2 10-7 10-14V6L16 2z" stroke="currentColor" stroke-width="1.2" stroke-linejoin="round"/>\n  <g transform="translate(8, 8) scale(0.25)">${inner}</g>\n</svg>\n`);
generated.set('packages/kiwicaptcha-client-core/src/brand.ts',
  `// Generated by packages/kiwicaptcha/tools/sync-brand.mjs. Do not edit.\nexport const KIWI_MARK_PATHS = ${JSON.stringify(paths, null, 2)} as const;\n`);

for (const [file, name] of [['widget-compat.js', 'COMPAT_SVG'], ['widget-shims.js', 'SHIMS_SVG']]) {
  const path = `packages/kiwicaptcha-wasm/assets/${file}`;
  const source = read(path);
  const pattern = new RegExp(`  var ${name} = '[^'\\n]*';`);
  if (!pattern.test(source)) throw new Error(`Missing brand slot in ${path}`);
  generated.set(path, source.replace(pattern, () => `  var ${name} = '${compact}';`));
}
const twig = 'packages/kiwicaptcha/integrations/symfony/src/Resources/views/form_div_layout.html.twig';
const template = read(twig);
const svgPattern = /<svg viewBox="0 0 64 64"[\s\S]*?<\/svg>/;
if (!svgPattern.test(template)) throw new Error('Missing brand slot in the Twig renderer');
generated.set(twig, template.replace(svgPattern, () => compact));

const preview = 'packages/kiwicaptcha/design/brand-preview.html';
if (existsSync(join(root, preview))) {
  generated.set(preview, read(preview).replace(
    /<!-- kiwi-mark:start -->[\s\S]*?<!-- kiwi-mark:end -->/,
    () => `<!-- kiwi-mark:start -->\n${mark}\n  <!-- kiwi-mark:end -->`,
  ));
}

// Asset copies ship inside the Rust crate and the Symfony bundle. Keep
// their byte identity without rebuilding the unrelated WASM solver.
for (const file of ['widget.css', 'widget-compat.js', 'widget-shims.js']) {
  const asset = `packages/kiwicaptcha-wasm/assets/${file}`;
  const content = generated.get(asset) ?? read(asset);
  for (const dir of ['packages/kiwicaptcha/resources', 'packages/kiwicaptcha/integrations/symfony/Resources/public']) {
    generated.set(`${dir}/${file}`, content);
  }
}

let stale = false;
for (const [path, expected] of generated) {
  const full = join(root, path);
  if (existsSync(full) && readFileSync(full, 'utf8') === expected) continue;
  if (check) { console.error(`Stale brand asset: ${path}`); stale = true; }
  else writeFileSync(full, expected);
}
if (stale) process.exitCode = 1;
else console.log(check ? 'Brand geometry and widget asset copies are synchronized.' : 'Updated Spiral Lock renderer assets.');
