<?php

declare(strict_types=1);

namespace BelConsulting\KiwiCaptchaBundle\DependencyInjection;

use KiwiCaptcha\Config;
use KiwiCaptcha\Risk\RiskAction;
use KiwiCaptcha\Risk\RiskV2Weights;
use KiwiCaptcha\Risk\RiskWeights;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    private const RISK_ACTIONS = ['allow', 'sha16', 'sha18', 'sha20', 'argon16', 'argon32', 'argon64', 'step_up', 'deny'];
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('kiwi_captcha');
        $root = $treeBuilder->getRootNode();

        $root
            ->children()
                ->scalarNode('secret_key')
                    ->info('HMAC secret key for signing/verifying challenges (min 16 bytes).')
                    ->isRequired()
                    ->cannotBeEmpty()
                ->end()
                ->scalarNode('issuer')
                    ->info('Deployment issuer stamped into every issued challenge (e.g. "auth-prod"). When set, the verifier REJECTS any record whose issuer does not match exactly — a dev/staging/prod mixup cannot validate cross-environment. The core long supported issuer; this makes it first-class bundle configuration.')
                    ->defaultNull()
                ->end()
                ->integerNode('kid')
                    ->info('Signing key id (1..4294967295) stamped into every issued challenge. Paired with secrets_by_kid + revoked_kids this is the controlled HMAC-key rotation control. The rotation procedure: move the superseded old kid and its key into secrets_by_kid, update secret_key to the new key, then bump kid to the new id. The current kid must never appear in secrets_by_kid — a historical entry for the current signing key would make the verifier select the wrong secret. The superseded secret remains valid for verification until its kid is revoked.')
                    ->min(1)
                    ->max(4294967295)
                    ->defaultValue(1)
                ->end()
                ->arrayNode('secrets_by_kid')
                    ->info('Verification-only secrets for historical signing key ids (map of canonical kid => secret, each >= 16 bytes). Rotation: move the superseded old kid and its key here, update secret_key to the new key, then bump kid — the current kid must never appear in this map. Verification of records signed under superseded kids uses these secrets.')
                    ->scalarPrototype()->end()
                    ->useAttributeAsKey('kid')
                    ->normalizeKeys(false)
                    ->defaultValue([])
                    ->validate()
                        ->ifTrue(static function (array $secrets): bool {
                            // Two distinct map keys that canonicalize to
                            // the same integer (e.g. the string key '02'
                            // next to the int key 2) would silently
                            // overwrite one historical secret downstream,
                            // so the duplicate is refused before any
                            // shape rule.
                            $seen = [];
                            foreach (\array_keys($secrets) as $kid) {
                                $canonical = (int) $kid;
                                if (isset($seen[$canonical])) {
                                    return true;
                                }
                                $seen[$canonical] = true;
                            }

                            return false;
                        })
                        ->thenInvalid('secrets_by_kid keys must be distinct canonical kids: two entries that resolve to the same integer would silently overwrite one historical secret')
                    ->end()
                    ->validate()
                        ->ifTrue(static function (array $secrets): bool {
                            foreach (\array_keys($secrets) as $kid) {
                                if (\is_int($kid)) {
                                    if ($kid < 1 || $kid > 4294967295) {
                                        return true;
                                    }

                                    continue;
                                }
                                if (preg_match('/^[1-9][0-9]*$/D', (string) $kid) !== 1) {
                                    return true;
                                }
                                $canonical = (int) $kid;
                                if ($canonical < 1 || $canonical > 4294967295) {
                                    return true;
                                }
                            }

                            return false;
                        })
                        ->thenInvalid('secrets_by_kid keys must be canonical decimal integers in 1..4294967295: a historical signing kid is written without leading zeros and without text, so "02", "0" and "foo" are all refused')
                    ->end()
                    ->validate()
                        ->ifTrue(static function (array $secrets): bool {
                            foreach ($secrets as $k => $v) {
                                if (!\is_string($v) || \strlen($v) < 16) {
                                    return true;
                                }
                            }

                            return false;
                        })
                        ->thenInvalid('secrets_by_kid values must be strings of at least 16 bytes')
                    ->end()
                ->end()
                ->arrayNode('revoked_kids')
                    ->info('Signing key ids whose verification is REVOKED (emergency key-compromise response). A record signed under a revoked kid is rejected with UnknownKid IMMEDIATELY — even when its secret is present in secrets_by_kid. Revocation always wins over rotation.')
                    ->integerPrototype()->min(1)->max(4294967295)->end()
                    ->defaultValue([])
                ->end()
                ->enumNode('algorithm')
                    ->values(['sha256', 'argon2id'])
                    ->defaultValue('sha256')
                ->end()
                ->enumNode('privacy_mode')
                    ->info("Privacy posture. 'strict' (default) FORCES: telemetry 'off', same_origin_only true, and min_duration_ms 0 (the server-side solve-timing floor is a timing heuristic and is disabled). 'standard' leaves those options under operator control. In strict mode the operator may still opt back INTO IP binding via binding_mode (binding is a relay-mitigation, not a privacy leak — the stored tag is nonce-bound, never a stable IP-derived identifier).")
                    ->values(['strict', 'standard'])
                    ->defaultValue('strict')
                ->end()
                ->enumNode('telemetry')
                    ->info("Widget behavioral telemetry collection: 'off' (default) sends no signal fields, 'minimal' and 'full' opt the widget into reporting bot-heuristic fields (client-controlled and forgeable — a supplement, never the security boundary). Forced to 'off' when privacy_mode is 'strict'.")
                    ->values(['off', 'minimal', 'full'])
                    ->defaultValue('off')
                ->end()
                ->enumNode('binding_mode')
                    ->info("Challenge binding: 'nonce_ip_hmac' (default) binds each challenge to the client IP via a nonce-bound HMAC tag (relay mitigation; the stored tag is unique per challenge, never a stable IP identifier). 'none' disables binding entirely — the core Issuer emits an EMPTY binding tag and verification skips the check (maximum privacy; relay protection off).")
                    ->values(['none', 'nonce_ip_hmac'])
                    ->defaultValue('nonce_ip_hmac')
                ->end()
                ->booleanNode('same_origin_only')
                    ->info('Reject challenge requests whose Origin header is not the application origin with HTTP 403 CROSS_ORIGIN_DENIED (cross-site abuse/CSRF hardening). Requests without an Origin header (curl, same-origin navigation) are allowed. Forced true when privacy_mode is strict.')
                    ->defaultValue(true)
                ->end()
                ->integerNode('rate_limit')
                    ->info('Max challenge issuances per client IP per rate_limit_window_secs (0 = disabled; default 10). Production deployments should keep this on — it bounds the aggregate verification work an attacker can trigger.')
                    ->defaultValue(10)
                    ->min(0)
                ->end()
                ->integerNode('rate_limit_global')
                    ->info('DEPLOYMENT-WIDE cap on challenge issuances per rate_limit_window_secs (0 = disabled; default 500). Enforced on every backend. The enforcement ladder: Redis executes an exact distributed sliding window, atomic and shared by all PHP-FPM workers. A shared PSR-6 pool keeps a best-effort shared window: a non-atomic read-modify-write can briefly exceed the cap under concurrency. Without either, the in-process window is exact per process, so N workers can approach N times the cap in aggregate. Global-only mode (rate_limit: 0) is supported on all backends. Exhaustion returns HTTP 429 with a distinct GLOBAL_RATE_LIMITED code. This hard limiter is the binding constraint on the default deployment: its window throughput (500 per 60s, about 8.3/s) is far below the default resource_capacity.issuance_per_second, so the default deployment is bounded here, not by the resource-pressure signal. Operators scaling beyond this limit must raise BOTH this cap and resource_capacity.issuance_per_second together; the global limiter stores one exact-timestamp member per admitted request, so its Redis cardinality is bounded by this cap itself, never by the window.')
                    ->defaultValue(500)
                    ->min(0)
                ->end()
                ->integerNode('rate_limit_rotation_secs')
                    ->info('HMAC rate-limit identity rotation period in seconds (default 3600; 0 disables rotation). The rate-limit key is HMAC(pepper, "kiwi-rate-v2|epoch|ip"): the same IP yields a DIFFERENT keyed pseudonym in every epoch, so Redis snapshots cannot correlate one source across time periods. The previous-epoch key is still checked so the sliding window stays exact across a rotation boundary. Linkability within one epoch is unavoidable for rate limiting.')
                    ->defaultValue(3600)
                    ->min(0)
                    ->max(86400)
                ->end()
                ->integerNode('rate_limit_window_secs')
                    ->info('Sliding-window size (seconds) for the issuance rate limits (per-client and global). The global limiter stores one exact-ms member per admitted request and prunes on every admission, so its Redis cardinality is bounded by rate_limit_global, never by this window; the value is capped at 3600 (1 hour) so a misconfiguration can never create a multi-hour window whose staleness weakens the limit.')
                    ->defaultValue(60)
                    ->min(1)
                    ->max(3600)
                ->end()
                ->integerNode('argon2_lease_ms')
                    ->info('Tokenized Redis lease lifetime in ms (default 45000). Must exceed the maximum verification request runtime (e.g. PHP request_terminate_timeout) by a safety margin — otherwise a lease can expire while its Argon2 hash is still running and another worker may enter.')
                    ->defaultValue(45000)
                    ->min(1000)
                    ->max(300000)
                ->end()
                ->scalarNode('argon2_semaphore_namespace')
                    ->info("Per-deployment discriminator for the Redis-backed Argon2 admission leases and the Redis global rate-limit key (defaults to kernel.project_dir). Two deployments sharing one Redis instance must use different namespaces so their lease sets and global windows do not compete. Sanitized to [A-Za-z0-9_.-] before being embedded in a key.")
                    ->defaultValue('%kernel.project_dir%')
                ->end()
                ->booleanNode('enforce_telemetry')
                    ->info('When true, the validator rejects tokens whose client-reported telemetry scores as bot-like. LEGACY opt-in hard gate kept only for explicit compatibility — new automation signals must become bounded risk factors instead; telemetry is client-controlled, so this is never the security boundary.')
                    ->defaultValue(false)
                ->end()
                ->integerNode('min_duration_ms')
                    ->info('Minimum solve duration in ms, enforced by SERVER-side timing (null/0 = disabled; the default derives the floor from the difficulty). In strict privacy mode this is forced to 0 — the timing heuristic is off.')
                    ->defaultNull()
                    ->min(0)
                ->end()
                ->integerNode('argon_m_kib')
                    ->info('Argon2id memory cost in KiB (only for argon2id; must be >= 8 * argon_p).')
                    ->defaultValue(0)
                    ->min(0)
                    // Same browser-solvable ceiling as the core
                    // (KiwiCaptcha\Config validates m_kib <= 65536).
                    ->max(65536)
                ->end()
                ->integerNode('argon_t')
                    // Unconditional floor only; the conditional Argon2id
                    // profile rules (t >= 3, p == 1, m_kib >= 8 * p) are
                    // enforced by KiwiCaptcha\Config when the extension builds
                    // it, so this tree must not duplicate those protocol
                    // constraints. The issuance-side ceiling
                    // (Config::MAX_ARGON_T = 6) is the browser-solver cap;
                    // the verifier's structural ceiling is 16 (a signed
                    // record with t in 7..16 passes the structural gates but
                    // is never issued), so the tree refuses the issuance
                    // ceiling at configuration time.
                    ->defaultValue(3)
                    ->min(1)
                    ->max(Config::MAX_ARGON_T)
                ->end()
                ->integerNode('argon_p')
                    ->defaultValue(1)
                    ->min(1)
                ->end()
                ->integerNode('difficulty_bits')
                    ->info('Leading zero bits for SHA-256 challenges (default 18). 18 is the ordinary baseline: mean ≈ 262k hashes, p99 ≈ 1.21M, and exhaustion within the widget\'s 5,000,000-hash cap ≈ 5.2×10⁻⁹. 20 is the elevated rung, reached via adaptive risk escalation (Argon and StepUp sit above it) — as the default it would collapse the ladder, because the risk resolver treats the configured difficulty as the floor and Allow/SHA16/SHA18/SHA20 would all issue SHA20, whose 5,000,000-hash exhaustion probability is ≈ 0.8494% (about 1 in 118 legitimate solves).')
                    ->defaultValue(18)
                    ->min(1)
                    // Do not re-derive the protocol ceiling here: the single
                    // source of truth is KiwiCaptcha\Config (20, the wasm
                    // solver cannot go higher), so the tree can never drift
                    // from the core's constraint.
                    ->max(Config::MAX_SHA_TARGET_BITS)
                ->end()
                ->integerNode('argon2_difficulty_bits')
                    ->info('Leading zero bits for Argon2id challenges (default 8, max 10).')
                    ->defaultValue(8)
                    ->min(1)
                    // Same ceiling as the core's Argon2id target-bits max.
                    ->max(10)
                ->end()
                ->integerNode('challenge_ttl_secs')
                    ->defaultValue(120)
                    ->min(10)
                    ->max(Config::MAX_TTL_SECS)
                ->end()
                ->scalarNode('storage')
                    ->info('Service id implementing KiwiCaptcha\StorageInterface. Defaults to the in-memory ArrayStorage, which is only allowed in test/dev environments — in prod a shared storage is required or the container fails to compile. production verification also REQUIRES an atomic backend (KiwiCaptcha\AtomicStorageInterface — e.g. RedisStorage) so strict single-use holds under concurrency; the explicitly-named allow_best_effort_storage: true option is the escape hatch for deliberately weaker semantics. Siteverify additionally ALWAYS requires an atomic backend when siteverify_secrets is configured (its one-success provider contract depends on it).')
                    ->defaultValue('kiwi_captcha.storage.array')
                ->end()
                ->booleanNode('allow_best_effort_storage')
                    ->info('explicitly-named escape hatch accepting non-atomic storage semantics (e.g. Psr6Storage, whose consume is NOT atomic under concurrency — two racing requests can both win). Default false: production verification requires KiwiCaptcha\AtomicStorageInterface. NEVER set true for Siteverify — its one-success contract is impossible on a non-atomic backend and the container refuses the combination regardless.')
                    ->defaultFalse()
                ->end()
                ->booleanNode('allow_nonredis_rate_limit_fallback')
                    ->info('Explicitly accepts the non-Redis issuance rate limiter in production when any temporal issuance limit (rate_limit or rate_limit_global) is configured but no Redis client and no rate_limit_cache PSR-6 pool are wired. The documented choices: Redis (redis_service) is the exact distributed window; a shared PSR-6 pool (rate_limit_cache) is a cross-request best-effort window; the object-memory window is persistent-runtime-only (RoadRunner/Swoole/amphp or a single CLI process) and request-local under conventional PHP-FPM, so it provides no cross-request protection at all. Default false: production refuses the combination unless the weaker semantics are explicitly accepted.')
                    ->defaultFalse()
                ->end()
                ->booleanNode('allow_local_global_limit_fallback')
                    ->info('DEPRECATED alias for allow_nonredis_rate_limit_fallback: the old name still enables the non-Redis issuance rate limiter in production, but the new name covers ANY non-Redis temporal issuance limit (the per-client rate_limit included), not just the global cap. Production temporal limiting requires Redis (redis_service) or a genuinely persistent or shared PSR-6 pool (rate_limit_cache); the object-memory fallback is long-lived-runtime-only (RoadRunner/Swoole/amphp or a single CLI process) and gives no cross-request protection under conventional PHP-FPM. Default false: production refuses the combination.')
                    ->setDeprecated('bel-consulting/kiwicaptcha-symfony', '1.x', 'The "%node%" option is deprecated; use "allow_nonredis_rate_limit_fallback" instead.')
                    ->defaultFalse()
                ->end()
                ->booleanNode('allow_local_argon_admission_fallback')
                    ->info('Explicitly accepts the in-process Argon admission gate in production when argon2_max_concurrent_verifications > 0 but no Redis client is wired. The deployment-wide ceiling then degrades to the per-process gate: the aggregate of N workers can approach N times the configured concurrency. Default false: production refuses the combination.')
                    ->defaultFalse()
                ->end()
                ->scalarNode('redis_service')
                    ->info('Optional service id of a Redis client (\Redis or Predis\Client) used for the Redis-backed Argon2id admission semaphore AND the atomic global rate limiter. When set (and algorithm=argon2id with a positive argon2_max_concurrent_verifications), the concurrency cap is enforced ACROSS PHP-FPM workers, not just per process. When null, the extension falls back to the storage service itself if it is KiwiCaptcha\Storage\RedisStorage (its client is reused), and otherwise to the in-process semaphore (per-process only — see README).')
                    ->defaultNull()
                ->end()
                ->scalarNode('route_prefix')
                    ->info('Prefix for the challenge endpoint route.')
                    ->defaultValue('/kiwi-captcha')
                ->end()
                ->scalarNode('rate_limit_cache')
                    ->info('Optional service id of a PSR-6 pool (Psr\\Cache\\CacheItemPoolInterface) used as SHARED, multi-process rate-limit state, e.g. a Redis-backed Symfony Cache pool. Only used when no Redis client is available for the atomic limiter. When omitted, a per-process in-memory sliding window is used (single-worker only — PHP-FPM workers share no memory).')
                    ->defaultNull()
                ->end()
                ->scalarNode('rate_limit_pepper')
                    ->info('Secret used to HMAC client IPs before they are used as rate-limit keys, so raw IPs are never stored. Defaults to secret_key when not set. Configure a dedicated, stable pepper instead: the HMAC identities anchor the per-client rate-limit memory, and a routine signing-key rotation must not silently reset that memory. A fresh pepper derives fresh identities, so every client window would restart empty. An emergency root compromise may intentionally rotate everything; a routine rotation should leave the rate-limit identities untouched.')
                    ->defaultNull()
                ->end()
                ->integerNode('argon2_max_concurrent_verifications')
                    ->info('Max concurrent Argon2id verifications (0 = unlimited). Each verification allocates argon_m_kib of memory, so size this to the available memory. The gate applies REGARDLESS of the locally selected issuance algorithm: shared Rust/PHP Argon records stay protected (a Symfony service issuing SHA challenges may still receive a solution for an Argon record written by a Rust service — the gate is consulted based on the STORED record\'s algorithm). With a Redis client available (redis_service, or RedisStorage as the storage backend) the cap is enforced across all PHP-FPM workers via tokenized leases; otherwise it is best-effort per process (see README for the multi-worker caveat).')
                    ->defaultValue(2)
                    ->min(0)
                ->end()
                ->integerNode('argon2_max_waiters')
                    ->info('Bounded waiters guard of the Redis-backed Argon2id admission semaphore (default 64): when the concurrency cap is saturated, contenders are counted in a {..}:sem:waiters counter with the lease lifetime\'s TTL; once the waiter count EXCEEDS argon2_max_waiters, acquire() returns null IMMEDIATELY (CapacityExceeded — surfaced as the captcha violation/429) instead of queueing behind the saturated gate. A waiter is removed when a lease is granted or the acquire returns null (best-effort, same Lua). Hard bound against unbounded waiter accumulation during Argon2id saturation storms.')
                    ->defaultValue(64)
                    ->min(1)
                ->end()
                ->scalarNode('public_base_url')
                    ->info("The deployment's public origin (e.g. https://captcha.example.com), taken from server config and never from the Host header. When set, the challenge endpoint's same-origin check compares the request Origin against this canonical origin instead of the request's own scheme and host. A forged Host header can therefore never make a cross-origin request look same-origin, and the expected origin stays stable behind load balancers. When null (default), the same-origin check derives the expected origin from the request itself; this is allowed in test/dev only. In production with same-origin enforcement (the default) or Siteverify active, the value is required: the extension fails at container compile time otherwise.")
                    ->defaultNull()
                ->end()
                ->integerNode('argon2_max_per_tenant')
                    ->info('PER-SCOPE budget of the Redis-backed Argon2id admission semaphore (default 8): each scope string gets its OWN lease set ({kiwicaptcha:argon2:leases:<ns>}:<scope>, checked IN ADDITION to the global argon2_max_concurrent_verifications cap), so one busy scope can never starve the other scopes\' Argon capacity while the global cap stays the deployment-wide invariant. The waiters guard stays global. Fairness knob for multi-tenant deployments (a tenant/endpoint mapped to a scope gets a guaranteed share of the memory-hard budget).')
                    ->defaultValue(8)
                    ->min(1)
                ->end()
                ->arrayNode('resource_capacity')
                    ->info('Deployment-wide issuance capacity (the shared Redis counter denominator of the resource-pressure provider\'s issuanceCapacity headroom). Separate from the per-process emergency cap (risk.hard_limits.process_per_second), which only bounds the in-process ProcessEmergencyCap admission layer.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('issuance_per_second')
                            ->info('Deployment-wide issuance capacity (shared Redis counter denominator). Default 500, aligned with the hard limiter rate_limit_global (500 per rate_limit_window_secs 60): the default deployment is constrained by that hard limiter, not by this capacity, so the two defaults make the same scale claim. The headroom formula max(0, cap - rate) * 1000 / cap denies only when the measured per-second issuance approaches this value. Operators scaling beyond the hard limiter must raise BOTH this denominator and rate_limit_global together — the global limiter stores one exact-timestamp member per admitted request, so its Redis cardinality is bounded by the cap itself, never by the window. Separate from the per-process emergency cap (hard_limits.process_per_second).')
                            ->defaultValue(500)
                            ->min(1)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('risk')
                    ->info('Adaptive risk engine (kiwicaptcha/kiwicaptcha-risk-php, risk-v1 protocol): a privacy-first, self-hosted scoring layer that adapts challenge difficulty — or denies issuance — per source before a challenge is even minted. Stores only keyed ephemeral pseudonyms (no raw IPs, no stable identifiers); the optional continuity cookie is a first-party, HttpOnly, random 16-byte nonce (never an IP-derived identifier) that links requests from the same browser for the "session" signal. The canonical risk-v1 Lua state script ships INSIDE the package (resources/risk-v1.lua). OFF by default: enabling it requires a Predis\\Client (risk.redis_service, or the bundle redis_service / RedisStorage client when it is a Predis\\Client) — the extension fails fast with a LogicException otherwise.')
                    ->canBeEnabled()
                    ->children()
                        ->scalarNode('redis_service')
                            ->info('Optional service id of a Predis\\Client used for the risk state store (the canonical risk-v1 EVALSHA Lua script). When null, the extension reuses the bundle Redis client resolved from redis_service / RedisStorage when it is a Predis\\Client; otherwise risk.enabled fails at compile time with a LogicException.')
                            ->defaultNull()
                        ->end()
                        ->scalarNode('namespace')
                            ->info('Per-deployment discriminator for the risk Redis keys (hash tag {kiwi:<namespace>}). Defaults to kernel.project_dir; sanitized to [A-Za-z0-9_.-]. Two deployments sharing one Redis instance must use different namespaces so their risk state does not compete.')
                            ->defaultValue('%kernel.project_dir%')
                        ->end()
                        ->scalarNode('master_secret')
                            ->info('HKDF master key for the risk identity keys (source/subnet/session/principal). MUST be a high-entropy secret (%env(KIWI_RISK_SECRET)% recommended). When null, the bundle derives the keys from the captcha secret_key (documented fallback). Configure a dedicated, stable master secret: the derived identities anchor the adaptive risk memory, and a routine signing-key rotation must not silently reset that memory. A fresh master derives fresh pseudonyms, so every source/subnet/session counter restarts at zero and a previously-flagged source loses its memory. A compromise of one secret never leaks the other. An emergency root compromise may intentionally rotate everything; a routine rotation should leave the risk identities untouched.')
                            ->defaultNull()
                        ->end()
                        ->integerNode('source_epoch_secs')
                            ->info('Epoch length in seconds for the SOURCE pseudonym (default 900). The source identity rotates every epoch, so old snapshots cannot correlate one source across time periods.')
                            ->defaultValue(900)
                            ->min(60)
                        ->end()
                        ->integerNode('subnet_epoch_secs')
                            ->info('Epoch length in seconds for the SUBNET pseudonym (default 900).')
                            ->defaultValue(900)
                            ->min(60)
                        ->end()
                        ->integerNode('subnet_ipv4_prefix')
                            ->info('IPv4 subnet mask bits for the network cohort identity (default 24).')
                            ->defaultValue(24)
                            ->min(0)
                            ->max(32)
                        ->end()
                        ->integerNode('subnet_ipv6_prefix')
                            ->info('IPv6 subnet mask bits for the network cohort identity (default 56).')
                            ->defaultValue(56)
                            ->min(0)
                            ->max(128)
                        ->end()
                        ->integerNode('state_ttl_secs')
                            ->info('TTL of the live risk counters (source/subnet/session/global) in seconds (default 1800).')
                            ->defaultValue(1800)
                            ->min(60)
                        ->end()
                        ->integerNode('principal_ttl_secs')
                            ->info('TTL of the principal counter in seconds (default 86400). The bundle never records a principal itself — when a PrincipalResolverInterface service is wired, the RESOLVED principal of the current request flows through pre-issue, post-solve and every feedback signal (HMAC-pseudonymized before storage); apps that want principal reputation but feed no principal feedback keep the counter dormant under this TTL.')
                            ->defaultValue(86400)
                            ->min(60)
                        ->end()
                        ->integerNode('dedupe_ttl_secs')
                            ->info('Event-dedupe window in seconds (default 60): an identical event_id is applied at most once, so retries of the same request never double-count.')
                            ->defaultValue(60)
                            ->min(1)
                        ->end()
                        ->integerNode('hysteresis_ms')
                            ->info('Global pressure level hysteresis window in ms (default 60000): the global level only leaves a band after this quiet window, so level flaps do not oscillate issuance policy.')
                            ->defaultValue(60000)
                            ->min(1000)
                        ->end()
                        ->arrayNode('saturations')
                            ->info('Raw counter saturations (fixed-point 1000 = one unit) for the state script; higher saturation = slower reaction to the signal.')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->integerNode('src_fast')->defaultValue(8000)->min(1)->end()
                                ->integerNode('src_slow')->defaultValue(100000)->min(1)->end()
                                ->integerNode('issue')->defaultValue(6000)->min(1)->end()
                                ->integerNode('bad')->defaultValue(4000)->min(1)->end()
                                ->integerNode('mal')->defaultValue(3000)->min(1)->end()
                                ->integerNode('rep')->defaultValue(2000)->min(1)->end()
                                ->integerNode('action')->defaultValue(6000)->min(1)->end()
                                ->integerNode('switch')->defaultValue(10000)->min(1)->end()
                                ->integerNode('global')->defaultValue(70000)->min(1)->end()
                                ->integerNode('trust')->defaultValue(10000)->min(1)->end()
                            ->end()
                        ->end()
                        ->arrayNode('weights')
                            ->info('13 fixed-point weight fields (0..1000) of the risk-v1 scorer. Defaults are the contract defaults (identical to fixtures.json).')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->integerNode('source_fast')->defaultValue(RiskWeights::DEFAULT_SOURCE_FAST)->min(0)->max(1000)->end()
                                ->integerNode('source_slow')->defaultValue(RiskWeights::DEFAULT_SOURCE_SLOW)->min(0)->max(1000)->end()
                                ->integerNode('subnet_fast')->defaultValue(RiskWeights::DEFAULT_SUBNET_FAST)->min(0)->max(1000)->end()
                                ->integerNode('issue_debt')->defaultValue(RiskWeights::DEFAULT_ISSUE_DEBT)->min(0)->max(1000)->end()
                                ->integerNode('bad_proof')->defaultValue(RiskWeights::DEFAULT_BAD_PROOF)->min(0)->max(1000)->end()
                                ->integerNode('malformed')->defaultValue(RiskWeights::DEFAULT_MALFORMED)->min(0)->max(1000)->end()
                                ->integerNode('replay')->defaultValue(RiskWeights::DEFAULT_REPLAY)->min(0)->max(1000)->end()
                                ->integerNode('action_failure')->defaultValue(RiskWeights::DEFAULT_ACTION_FAILURE)->min(0)->max(1000)->end()
                                ->integerNode('scope_switch')->defaultValue(RiskWeights::DEFAULT_SCOPE_SWITCH)->min(0)->max(1000)->end()
                                ->integerNode('global_pressure')->defaultValue(RiskWeights::DEFAULT_GLOBAL_PRESSURE)->min(0)->max(1000)->end()
                                ->integerNode('network_risk')->defaultValue(RiskWeights::DEFAULT_NETWORK_RISK)->min(0)->max(1000)->end()
                                ->integerNode('trust_credit')->defaultValue(RiskWeights::DEFAULT_TRUST_CREDIT)->min(0)->max(1000)->end()
                                ->integerNode('principal_credit')->defaultValue(RiskWeights::DEFAULT_PRINCIPAL_CREDIT)->min(0)->max(1000)->end()
                            ->end()
                        ->end()
                        ->arrayNode('v2')
                            ->info('RISK-V2 ADDITIVE EVIDENCE WEIGHTS: the three fixed-point weight fields (0..1000) of the risk-v2 additive factors (honeypot/decoy evidence, session client-context consistency, trusted-edge TLS consistency), wired into the RiskGateway. The defaults ARE the contract defaults (identical to the risk-v2 package).')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->integerNode('honeypot_weight')->defaultValue(RiskV2Weights::DEFAULT_HONEYPOT)->min(0)->max(1000)->end()
                                ->integerNode('session_consistency_weight')->defaultValue(RiskV2Weights::DEFAULT_SESSION_INCONSISTENCY)->min(0)->max(1000)->end()
                                ->integerNode('tls_weight')->defaultValue(RiskV2Weights::DEFAULT_TLS)->min(0)->max(1000)->end()
                            ->end()
                        ->end()
                        ->integerNode('policy_version')
                            ->info("SECURITY-POLICY EPOCH stamped (signed) into every issued challenge record and enforced at verification: bumping it (origin/action-policy changes, emergency revocation, compromised tenant) immediately invalidates ALL outstanding challenges — the verifier rejects any record whose policy_version differs from the configured value with WrongPolicyVersion. Cosmetic configuration changes must NOT bump it. The risk-v1 policy CONTRACT version is internal to the risk package (RiskPolicy::CONTRACT_VERSION) and independent of this knob.")
                            ->defaultValue(1)
                            ->min(1)
                        ->end()
                        ->arrayNode('global_floors')
                            ->info('Minimum action per global pressure level 1..4 (default: 1=>sha16, 2=>sha18, 3=>sha20, 4=>sha20). The deployment-wide state script raises/lowers the level; the floor guarantees the aggregate posture tightens before per-source signals do. Index 0 is always Allow in the policy handed to the engine, and when global_pressure.enabled is false every floor is Allow (the global controller is off).')
                            ->useAttributeAsKey('level')
                            ->prototype('enum')
                                ->values(self::RISK_ACTIONS)
                            ->end()
                            ->defaultValue([
                                1 => RiskAction::Sha16->value,
                                2 => RiskAction::Sha18->value,
                                3 => RiskAction::Sha20->value,
                                4 => RiskAction::Sha20->value,
                            ])
                        ->end()
                        ->arrayNode('scopes')
                            ->info('Per-scope policy. The KEY is the application scope string (the one passed to the challenge endpoint / form "scope" option); "id" is the int scope identifier stored in Redis state — it MUST stay stable once deployed (defaults to crc32 of the scope name), two scopes must never share an id. Scopes NOT listed here are handled by the unknown_scope node (baseline = the adaptive engine declines to evaluate and the controller issues the default profile; reject = the controller returns the risk-denied 429 without issuing; minimum = synthetic policy base_risk 100 / minimum sha20 / degraded sha20).')
                            ->useAttributeAsKey('name')
                            ->arrayPrototype()
                                ->children()
                                    ->integerNode('id')
                                        ->info('Explicit int scope id (stable across deploys). Defaults to crc32(scope name) & 0x7fffffff.')
                                        ->defaultNull()
                                        ->min(1)
                                    ->end()
                                    ->integerNode('base_risk')
                                        ->info('Score floor for this scope before any signal is added (0..1000).')
                                        ->defaultValue(100)
                                        ->min(0)
                                        ->max(1000)
                                    ->end()
                                    ->enumNode('minimum')
                                        ->info('Hard minimum action: issuance can never be WEAKER than this regardless of signals (floor, not a target).')
                                        ->values(self::RISK_ACTIONS)
                                        ->defaultValue('allow')
                                    ->end()
                                    ->enumNode('degraded')
                                        ->info('Action used when the risk state backend is unavailable (circuit-breaker open / store failure). Availability-first by default: challenges are still issued with the bundle\'s own configured difficulty.')
                                        ->values(self::RISK_ACTIONS)
                                        ->defaultValue('allow')
                                    ->end()
                                    ->booleanNode('post_solve_check')
                                        ->info('When true, a VALID solve triggers a fresh POST-SOLVE assessment (SolveSuccess) with the same context; a Deny there fails the validation with the "kiwi.post_solve_rejected" error and a StepUp fails it with "kiwi.post_solve_step_up_required" (the application routes the user to MFA/passkey/email confirmation). The gateway does NOT confirm its own post-solve decision — ConfirmedLegitimate / ConfirmedAbuse are application-only signals that require a decision id.')
                                        ->defaultValue(false)
                                    ->end()
                                ->end()
                            ->end()
                            ->defaultValue([
                                'contact' => ['id' => null, 'base_risk' => 60, 'minimum' => 'sha16', 'degraded' => 'sha18', 'post_solve_check' => false],
                                'signup' => ['id' => null, 'base_risk' => 100, 'minimum' => 'sha16', 'degraded' => 'sha20', 'post_solve_check' => true],
                                'login' => ['id' => null, 'base_risk' => 120, 'minimum' => 'sha18', 'degraded' => 'sha20', 'post_solve_check' => true],
                                'password_reset' => ['id' => null, 'base_risk' => 180, 'minimum' => 'sha18', 'degraded' => 'sha20', 'post_solve_check' => true],
                                'admin_login' => ['id' => null, 'base_risk' => 300, 'minimum' => 'sha20', 'degraded' => 'deny', 'post_solve_check' => true],
                                'financial_action' => ['id' => null, 'base_risk' => 400, 'minimum' => 'sha20', 'degraded' => 'deny', 'post_solve_check' => true],
                            ])
                        ->end()
                        ->arrayNode('unknown_scope')
                            ->info('Behavior for scopes that are not configured. minimum (default): unknown scopes are assessed under a synthetic policy (base_risk 100, minimum Sha20, degraded Sha20, ladder defaults) — a typo\'d scope string stays fail-safe (never silently weak) without taking the site down. reject: TRUE rejection — the controller returns the risk-denied response (HTTP 429 RISK_DENIED) without issuing any challenge. baseline: the adaptive engine declines to evaluate and the controller issues the default profile (baseline Kiwi verification still applies).')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->enumNode('mode')->values(['reject', 'baseline', 'minimum'])->defaultValue('minimum')->end()
                            ->end()
                        ->end()
                        ->arrayNode('global_pressure')
                            ->info('Global attack-pressure controller (levels 0-4 with hysteresis).')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')->defaultTrue()->end()
                                ->integerNode('hysteresis_secs')->defaultValue(30)->min(1)->max(300)->end()
                            ->end()
                        ->end()
                        ->arrayNode('argon_capacity')
                            ->info('Never self-DoS: when Argon capacity is saturated, high-risk sources are degraded to SHA-20 instead of more Argon work.')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')->defaultTrue()->end()
                            ->end()
                        ->end()
                        ->integerNode('argon_verification_memory_kib')
                            ->info('The FIXED memory envelope for ALL adaptive Argon challenges : the server-side verification cost of an Argon challenge is bounded by this SINGLE value regardless of the risk decision. Risk escalates the TARGET DIFFICULTY (the expected nonce search space via risk.argon_escalation_target_bits), never the memory — the adaptive engine must never increase the SERVER verification cost as its difficulty mechanism.')
                            ->defaultValue(16384)
                            ->min(1024)
                            ->max(65536)
                        ->end()
                        ->arrayNode('argon_escalation_target_bits')
                            ->info('Target-difficulty escalation ladder of the three adaptive Argon actions: EXACTLY 3 entries — Argon16, Argon32, Argon64 — strictly increasing within 1..Config::MAX_ARGON2_TARGET_BITS (default [1, 4, 8]). The Argon2id memory stays at risk.argon_verification_memory_kib for every action (t=3, p=1); only the expected nonce search space escalates, so the server verification cost ceiling is risk-independent. A ladder violating 1 <= rung1 < rung2 < rung3 <= Config::MAX_ARGON2_TARGET_BITS is refused at configuration time (the rungs must be strictly increasing and bounded by the core\'s Argon2id widget ceiling).')
                            ->integerPrototype()->min(1)->max(Config::MAX_ARGON2_TARGET_BITS)->end()
                            ->defaultValue([1, 4, 8])
                            ->validate()
                                ->ifTrue(static fn (array $v): bool => \count($v) !== 3
                                    || $v[0] >= $v[1]
                                    || $v[1] >= $v[2])
                                ->thenInvalid('must be EXACTLY 3 entries satisfying 1 <= rung1 < rung2 < rung3 <= '.Config::MAX_ARGON2_TARGET_BITS.' — the Argon16/32/64 target-bits ladder, bounded by Config::MAX_ARGON2_TARGET_BITS (the core\'s Argon2id widget ceiling)')
                            ->end()
                        ->end()
                        ->integerNode('security_epoch_cache_secs')
                            ->info('Cache TTL of the SecurityEpochMonitor\'s central security-policy read : the monitor reads `{kiwi:<ns>}:security-policy` hash\'s `min_policy_epoch` at most once per window, keeps a MONOTONIC in-process max (a regressed central value is ignored) and serves the last-observed epoch when Redis is unavailable. The bounded revocation latency of a policy bump is one cache window.')
                            ->defaultValue(1)
                            ->min(1)
                            ->max(30)
                        ->end()
                        ->integerNode('security_epoch_max_stale_secs')
                            ->info('MAX-STALE FAIL-CLOSED window of the SecurityEpochMonitor : after the last SUCCESSFUL central policy read, once now > last_success + max_stale the monitor reports stale — the cached epoch may be outdated (an emergency revocation could have landed while the node could not read). While stale, the validator fails verification closed (temporary_unavailable — the token is not burned, the server refuses to trust its own cache) and the challenge controller refuses issuance with 503 SERVICE_UNAVAILABLE. Within the window the cached max keeps serving (bounded outage tolerance). The availability trade-off is deliberate: a node that cannot confirm the central policy for max_stale seconds stops issuing and stops verifying, rather than serving potentially-revoked challenges forever.')
                            ->defaultValue(60)
                            ->min(10)
                        ->end()
                        ->scalarNode('result_receipt_signing_key')
                            ->info('OPTIONAL base64 32-byte Ed25519 seed : when configured, the validator signs every valid verification result into an asymmetric receipt ({jti, tenant, action, request_binding, issued_at, expires_at, issuer} — the full replay-critical set) with sodium_crypto_sign_detached, exposed via KiwiCaptchaValidator::verifiedReceiptPayload() / ::verifiedReceiptSignature(). The result verification itself stays CENTRAL-ONLY (the HMAC secret never leaves the server); this key only enables EXPORTED result receipts that third parties verify with the PUBLIC key derived from this seed (never the private key). Signature verification alone is NOT sufficient for single-use actions: the integrator must atomically record the jti (INSERT IF NOT EXISTS / SET NX) and treat a pre-existing jti as a replay (verify_and_consume — README).')
                            ->defaultNull()
                        ->end()
                        ->integerNode('max_challenges_per_scope_per_minute')
                            ->info('PER-SCOPE issuance cap : when > 0, a Redis fixed-window counter (INCR + EXPIRE 60 in one atomic Lua script) bounds how many challenges a scope may issue per minute — a public site key + claimed origin can no longer create unlimited billed verification work per scope. The quota keys on the SERVER-OWNED scope identity: the configured risk.scopes.<name>.id (stable u32), or the shared synthetic unknown-scope id — the raw scope string is NEVER a Redis key component , and the quota namespace is bounded by the server-owned set when risk.allowed_scopes is configured. The cap is only enforceable with a Redis client (fail-fast at compile time otherwise); each scope gets its own independent window.')
                            ->defaultValue(0)
                            ->min(0)
                        ->end()
                        ->arrayNode('allowed_scopes')
                            ->info('SERVER-OWNED SCOPE ALLOWLIST: the list of application scope strings the challenge endpoint may issue for. Empty (default) = any syntactically valid scope is accepted (backward compatible). When NON-EMPTY, a scope outside the list is refused with 422 SCOPE_NOT_ALLOWED BEFORE the risk assessment and the quota checks — the per-scope issuance cap then operates over the server-owned namespace (bounded cardinality), which is the only configuration in which that cap is an independent security bound. Unknown scopes listed here but absent from the risk.scopes map are still assessed under the unknown_scope policy (minimum by default); adding the scope to risk.scopes gives it its own stable canonical id.')
                            ->scalarPrototype()
                                ->validate()
                                    ->ifTrue(static fn (string $v): bool => preg_match('/^[A-Za-z0-9._:-]{1,128}$/D', $v) !== 1)
                                    ->thenInvalid('Allowed scope names must match [A-Za-z0-9._:-]{1,128}.')
                                ->end()
                            ->end()
                            ->defaultValue([])
                        ->end()
                        ->arrayNode('sitekey_allowlist')
                            ->info('MIGRATION SITEKEY ALIAS MAP: public sitekey -> scope. A public sitekey is optional legacy metadata, never a secret. When the challenge request scope equals a configured sitekey, it is resolved to the mapped scope — the SERVER-OWNED mapping is authoritative, so an attacker-supplied sitekey can never reduce a route minimum security policy (unknown sitekeys stay scope names subject to allowed_scopes and the risk assessment). Typical: { "6Lc_abc123": "login" }.')
                            ->useAttributeAsKey('sitekey')
                            ->scalarPrototype()
                                ->validate()
                                    ->ifTrue(static fn (string $v): bool => preg_match('/^[A-Za-z0-9._:-]{1,128}$/D', $v) !== 1)
                                    ->thenInvalid('Mapped scope names must match [A-Za-z0-9._:-]{1,128}.')
                                ->end()
                            ->end()
                            ->defaultValue([])
                        ->end()
                        ->arrayNode('sitekeys')
                            ->info('SERVER-OWNED v3-style sitekey policy — public sitekey -> {default_scope, actions: {action: scope}, ttl_secs}. The BROWSER sends sitekey + action in the challenge request; the server resolves (sitekey, action) -> security scope, so a client can never invent protected scope names. An unknown action under a configured sitekey is REJECTED (never silently mapped). Sitekeys without a config entry resolve through sitekey_allowlist / the plain scope. The per-sitekey "binding" option is not offered: the core binds issuance by the GLOBAL binding_mode only, so a per-sitekey "required"/"none" claim could not be enforced (a misleading security promise); the global server-owned mode is the only binding control.')
                            ->useAttributeAsKey('sitekey')
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('default_scope')
                                        ->defaultValue('login')
                                        ->validate()
                                            ->ifTrue(static fn (string $v): bool => preg_match('/^[A-Za-z0-9._:-]{1,128}$/D', $v) !== 1)
                                            ->thenInvalid('default_scope must match [A-Za-z0-9._:-]{1,128}.')
                                        ->end()
                                    ->end()
                                    ->arrayNode('actions')
                                        ->useAttributeAsKey('action')
                                        ->scalarPrototype()
                                            ->validate()
                                                ->ifTrue(static fn (string $v): bool => preg_match('/^[A-Za-z0-9._:-]{1,128}$/D', $v) !== 1)
                                                ->thenInvalid('action scope must match [A-Za-z0-9._:-]{1,128}.')
                                            ->end()
                                        ->end()
                                        ->defaultValue([])
                                    ->end()
                                    ->integerNode('ttl_secs')
                                        ->info('Optional per-sitekey challenge lifetime in seconds, overriding the global challenge_ttl_secs — use 300 for close Turnstile token-lifetime parity. Bounded 1..Config::MAX_TTL_SECS (300).')
                                        ->defaultNull()
                                        ->min(1)
                                        ->max(Config::MAX_TTL_SECS)
                                    ->end()
                                ->end()
                            ->end()
                            ->defaultValue([])
                        ->end()
                        ->arrayNode('chaining')
                            ->info('SELECTIVE CHAINED CHALLENGES: an initial inexpensive proof, followed by a risk reassessment at form-submission time. Only a post-solve action STRICTLY STRONGER than what the client actually solved opens a chain — the reassessment\'s action must be a stronger PoW action (e.g. an Argon action) that the solved challenge does not already satisfy under the configured ladders. StepUp is TERMINAL application-level step-up (it NEVER becomes a chained PoW — the application answers with its own step-up flow, e.g. MFA), Deny rejects the submission, and only a strictly-stronger non-StepUp/Deny post-solve action issues a signed one-shot CHAIN TICKET gating a second (stronger) challenge issuance. The chain is a SERVER-SIDE TRANSACTION OBLIGATION: the chain + its obligation mapping (keyed on the bounded pseudonymous obligation id of the (policy-epoch, scope, AUTHORITATIVE request-binding) triple) are created atomically, so a client cannot restart the transaction at stage 1 by discarding the ticket — a later challenge request for the same transaction AUTO-RESUMES the open chain. The chain completes only when the stage-2 challenge VERIFIES (issued -> verified, the TERMINAL state that clears the obligation); a ticket-bearing request is NEVER downgraded to an unchained issuance.')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->info('Enable selective chaining. When true, a valid verification whose post-solve reassessment demands a stronger stage returns the kiwi.chain_required violation carrying the signed chain ticket (violation parameter {{ chain_ticket }}); the application re-renders the widget with data-kiwi-chain-ticket=<ticket> and the next challenge request presents it for a one-shot stage-2 issuance. Requires risk.enabled AND a non-null risk.request_binding_authority (the chain is anchored on the AUTHORITATIVE transaction binding — never on an unexamined client string); the extension refuses the combination at compile time.')
                                    ->defaultFalse()
                                ->end()
                                ->integerNode('ttl_secs')
                                    ->info('Lifetime of a chain (state + ticket) in seconds (default 300, bounded 30..3600). The ticket expires server-side at issuedAt + ttl_secs; the chain state TTL matches.')
                                    ->defaultValue(300)
                                    ->min(30)
                                    ->max(3600)
                                ->end()
                                ->integerNode('reservation_lease_secs')
                                    ->info('The SHORT owner-scoped reservation lease of a stage-2 chain in seconds (default 15, bounded 5..60 AND strictly smaller than chaining.ttl_secs). A crashed issuance owner blocks retries for SECONDS, not minutes; the lease is further bounded by the chain record\'s OWN remaining TTL (the signed ticket expiry is the true bound).')
                                    ->defaultValue(15)
                                    ->min(5)
                                    ->max(60)
                                ->end()
                                ->scalarNode('hmac_secret')
                                    ->info('HMAC secret signing the chain tickets. MUST be a high-entropy secret of at least 16 bytes (%env(KIWI_RISK_SECRET)% recommended); a shorter configured secret is refused at compile time. When null, the bundle derives it from the risk master_secret (which itself defaults to the captcha secret_key) — a dedicated chain secret is strongly recommended so a compromise of one never leaks the other.')
                                    ->defaultNull()
                                    ->validate()
                                        ->ifTrue(static fn ($v): bool => \is_string($v) && \strlen($v) < 16)
                                        ->thenInvalid('risk.chaining.hmac_secret must be a string of at least 16 bytes when configured')
                                    ->end()
                                ->end()
                            ->end()
                            ->validate()
                                ->ifTrue(static fn (array $v): bool => $v['reservation_lease_secs'] >= $v['ttl_secs'])
                                ->thenInvalid('risk.chaining.reservation_lease_secs must be strictly smaller than risk.chaining.ttl_secs — the reservation lease is a SHORT claim, never the chain lifetime')
                            ->end()
                        ->end()
                        ->scalarNode('request_binding_authority')
                            ->info('OPTIONAL service id of a RequestBindingAuthorityInterface implementation — the AUTHORITATIVE transaction-binding resolver. When configured, the challenge controller resolves the transaction binding ONLY through the authority (resolve($request, $scope, $presented)): the client-presented request_binding field is a HINT, never a value the server signs unexamined, and a binding the authority cannot confirm for the transaction is refused (422 INVALID_REQUEST_BINDING). The authority resolution must be STABLE across one transaction (stage-1 issuance and stage-2 resumption) because the chain obligation is keyed on the authoritative binding. REQUIRED (non-null) when risk.chaining.enabled — a chain without an authoritative binding anchor cannot be a server-side transaction obligation; the extension refuses the combination at compile time.')
                            ->defaultNull()
                            ->cannotBeEmpty()
                        ->end()
                        ->arrayNode('siteverify_secrets')
                            ->info('PROVIDER-COMPATIBLE SITEVERIFY SECRETS: map of server-to-server secret -> EXPECTED SCOPE for the {prefix}/siteverify endpoint. Empty (default) DISABLES the endpoint. Each secret authenticates an application backend (never browsers — a browser must not see it) AND resolves the scope the verifier requires: a login page backend presents its own secret and a financial-action backend presents its secret, so the token scope is enforced server-side (the verifier rejects a weaker login token for the financial secret — no expectedScope=null for multi-scope deployments). `remoteip` is only honored after a valid secret.')
                            ->useAttributeAsKey('secret')
                            ->validate()
                                ->ifTrue(static fn (array $v): bool => \array_filter(\array_keys($v), static fn (string $k): bool => \strlen($k) < 16) !== [])
                                ->thenInvalid('Siteverify secrets are the entire server-to-server authentication boundary — each key must be at least 16 bytes (32 random bytes recommended).')
                            ->end()
                            ->scalarPrototype()
                                ->validate()
                                    ->ifTrue(static fn (string $v): bool => preg_match('/^[A-Za-z0-9._:-]{1,128}$/D', $v) !== 1)
                                    ->thenInvalid('Siteverify expected scopes must match [A-Za-z0-9._:-]{1,128}.')
                                ->end()
                            ->end()
                            ->defaultValue([])
                        ->end()
                        ->arrayNode('hard_limits')
                            ->info('Cheap admission layer BEFORE the risk engine (long-lived-runtime-only, per process): in persistent workers the window is a real per-process emergency shield that gives floods an immediate 429 without touching Redis; under conventional PHP-FPM it is rebuilt per request, so it provides no temporal pre-Redis cap across requests.')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->integerNode('process_per_second')
                                    ->info('Per-PROCESS emergency cap protecting the process from overwhelming work when Redis/state controls fail (default 10000). The window lives in object memory: it is temporal only in a long-lived runtime (RoadRunner/Swoole/amphp or a single CLI process); under conventional PHP-FPM each request rebuilds the cap, so it provides no temporal pre-Redis cap across requests. Per-source throttling belongs to the distributed keyed layer — the risk-v1 source velocity signals plus the caller\'s own keyed rate limiter (fed back as SourceRateLimitHit). The process-local check runs BEFORE any Redis issuance limiter : a saturated window refuses with the 429 risk-denied response without a single Redis round trip.')
                                    ->defaultValue(10000)
                                    ->min(1)
                                ->end()
                            ->end()
                        ->end()
                        ->enumNode('client_ip_mode')
                            ->values(['direct', 'symfony_trusted_proxies', 'symfony_global'])
                            ->info('Trusted client-IP policy: "symfony_trusted_proxies" (default) trusts EXACTLY the risk.trusted_proxies list (an EMPTY list trusts nobody — Symfony global trusted-proxy state is never inherited implicitly); "direct" always uses the socket peer regardless of any application proxy configuration; "symfony_global" is the explicit opt-in that inherits Symfony\'s process-global trusted-proxy state. The controller, the validator and every risk signal derive the client IP through this policy, so the challenge binding tag, the rate-limit identity and the risk source pseudonym all see the same canonical IP.')
                            ->defaultValue('symfony_trusted_proxies')
                        ->end()
                        ->arrayNode('trusted_proxies')
                            ->info('CIDRs (or exact IPs) of the trusted reverse proxies . Only peers in this list may influence the canonical client IP via X-Forwarded-For / Forwarded (mode symfony_trusted_proxies); every other peer is the socket itself. When the list is empty, no peer is trusted — forwarding headers are ignored everywhere. In mode "direct" this list is unused.')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->booleanNode('reject_ambiguous_forwarding')
                            ->info('When a TRUSTED peer sends BOTH X-Forwarded-For AND Forwarded: true (the production default) rejects the request with HTTP 400 AMBIGUOUS_FORWARDING — a proxy sending both is misconfigured, the two headers can disagree, and the canonical IP becomes ambiguous (collapsing many users onto one proxy identity would otherwise weaken per-source rate limits and risk attribution). false logs the anomaly and proceeds with the socket peer. From an UNTRUSTED peer both headers are ignored entirely (never ambiguous, never an anomaly).')
                            ->defaultValue(true)
                        ->end()
                        ->scalarNode('trusted_tls_header')
                            ->info('OPTIONAL name of a TLS-classification header set by TRUSTED reverse-proxy/CDN infrastructure (e.g. "X-Tls-Class" carrying a coarse value like "tls13|http2"). When configured, the challenge controller reads ONLY this header, validates the value against the bounded pattern /^[a-z0-9_+:|:-]{1,64}$/i (a malformed value is ignored) — the 64-character bound and charset match the cross-language risk-v2 contract — and passes it to the risk-v2 client-context as a COARSE, server-attested TLS classification tag — never a raw fingerprint. This input is trusted ONLY from an explicitly trusted reverse proxy/CDN that STRIPS client-supplied values — never enable it without that, or a client can forge the classification. Only the coarse classification is stored (as the session first-seen record); no raw fingerprints are ever stored. Null (default) = the feature is off.')
                            ->defaultNull()
                        ->end()
                        ->arrayNode('trusted_tls_proxies')
                            ->info('CIDRs (or exact IPs) of the trusted edge proxies whose TLS-classification header (risk.trusted_tls_header) is honored. The header is read ONLY when the DIRECT peer of the request (REMOTE_ADDR — the immediate connection, checked with Symfony\'s IpUtils::checkIp) is inside this list; from every other peer the header is ignored (the request is assessed without a TLS tag). The direct peer must be the trusted proxy itself — the proxy must terminate the client connection and strip client-supplied header values. Empty (default) = the header is never read.')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->booleanNode('client_context')
                            ->info('OPT-IN coarse client-context collection: when true, the rendered widget container carries data-kiwi-risk-context="coarse" and the widget sends a deliberately coarse capability tag (viewport class, pointer class, language family, timezone class — no canvas/audio/font/GPU signals, no stable identifiers) with every challenge request. Default false: the widget collects no device-capability or screen-size signal in any mode. Refused under privacy_mode "strict" — enabling it requires the operator to deliberately enable coarse client context (privacy_mode "standard" plus this explicit opt-in).')
                            ->defaultFalse()
                        ->end()
                        ->integerNode('container_memory_mib')
                            ->info('Memory budget of the process container in MiB . When configured, /health/ready requires argon2_max_concurrent_verifications * max-adaptive-profile-memory (64 MiB — the risk profiles\' argon64 m_kib 65536 KiB) + 256 MiB headroom <= container_memory_mib; a violated invariant refuses startup (503 memory_budget_invariant). null (or a concurrency cap of 0 = unlimited) keeps the check skipped/documented — the invariant is only meaningful with a finite concurrency cap.')
                            ->defaultNull()
                            ->min(1)
                        ->end()
                        ->arrayNode('calibration')
                            ->info('Privacy-preserving aggregate calibration: score-bucket statistics (no identity, no IP, no pseudonym) with a bounded scope-bias adjustment. min_samples / max_adjustment / max_change_per_minute are passed to the Redis-backed AggregateCalibrator to bound the automatic adjustment; outcome_receipt_ttl_secs is the lifetime of the outcome/calibration receipts AND of the outcome ledger (the once-only confirmation/correction gate — long enough for fraud review / moderation / chargeback labels; it carries only score/scope/action/sample metadata, no identity); the short-lived nonce->decision handles use risk.nonce_to_decision_ttl_secs instead; retention_secs is accepted for backward compatibility with the former in-memory calibrator and is informational (the Redis-backed store uses the risk-v1 contract\'s fixed 24 h window).')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')->defaultFalse()->end()
                                ->integerNode('retention_secs')->defaultValue(86400)->min(3600)->end()
                                ->integerNode('min_samples')->defaultValue(1000)->min(10)->end()
                                ->integerNode('max_adjustment')->defaultValue(150)->min(0)->max(1000)->end()
                                ->integerNode('max_change_per_minute')->defaultValue(10)->min(1)->max(60)->end()
                                ->integerNode('outcome_receipt_ttl_secs')
                                    ->info('Lifetime of the outcome/calibration receipts AND of the outcome ledger ({kiwi:<ns>}:outcome:<decision_id> — the once-only confirmation/correction gate) in seconds. Long enough for fraud review / moderation / chargeback labels (default 86400 = 24 h); the payload contains only score/scope/action/sample metadata, never identity. The short-lived nonce->decision handles use risk.nonce_to_decision_ttl_secs instead.')
                                    ->defaultValue(86400)
                                    ->min(3600)
                                    ->max(604800)
                                ->end()
                                ->enumNode('mode')
                                    ->info('Label-selection contract: "complete" = every eligible outcome is labeled and fed to the calibrator; "random_sample" = Kiwi samples at assessment time (the receipt carries a "sampled" flag) and unsampled confirmations are consumed but NOT recorded (status 2 — the label can never select itself into the calibration population; the caller may still apply first-party reputation exactly once); "weighted" = the application supplies the inverse sampling probability per confirmation (RiskGateway::confirmDecisionOutcome($ppm) converts it to weight = 1_000_000/ppm) so labels with known selection bias are re-weighted into the population.')
                                    ->values(['complete', 'random_sample', 'weighted'])
                                    ->defaultValue('random_sample')
                                ->end()
                                ->integerNode('sampling_probability_ppm')
                                    ->info('Kiwi-side label inclusion probability in parts per million (default 100000 = 10%) for "random_sample" mode: each decision is sampled at assessment time and its receipt is marked; only sampled decisions can later be confirmed into the calibration aggregates. In "weighted" mode the application supplies the inverse probability per confirmation instead.')
                                    ->defaultValue(100000)
                                    ->min(1)
                                    ->max(1000000)
                                ->end()
                                ->floatNode('minimum_resolution_ratio')
                                    ->info('In random_sample mode, bias adjustment is suspended while total sampled decisions >= min_samples but resolved/total < this ratio — the label-reporting process must resolve a minimum fraction of the server-selected sample before the model may move (default 0.80; 0 disables the gate).')
                                    ->defaultValue(0.80)
                                    ->min(0.0)
                                    ->max(1.0)
                                ->end()
                                ->floatNode('false_positive_cost')
                                    ->info('Class-normalized calibration prices false positives vs false negatives: false_positive_cost is the per-unit cost of legitimate traffic scored as abusive (default 1.0).')
                                    ->defaultValue(1.0)
                                    ->min(0.1)
                                    ->max(10.0)
                                ->end()
                                ->floatNode('false_negative_cost')
                                    ->info('Class-normalized calibration prices false negatives vs false positives: false_negative_cost is the per-unit cost of abusive traffic scored as legitimate (default 2.0 — abuse that slips through costs twice as much as a false rejection).')
                                    ->defaultValue(2.0)
                                    ->min(0.1)
                                    ->max(10.0)
                                ->end()
                            ->end()
                        ->end()
                        ->integerNode('nonce_to_decision_ttl_secs')
                            ->info('TTL of the short-lived server-side mapping pairing a challenge nonce to its risk decision id ({kiwi:<ns>}:decision:<nonce>, JSON {"decision_id": ...}; NO IP, NO identity). Consumed once with GETDEL after a valid solve. Independent of the outcome lifetime: the handle only bridges the challenge solve window (default 300).')
                            ->defaultValue(300)
                            ->min(60)
                            ->max(3600)
                        ->end()
                        ->arrayNode('continuity_cookie')
                            ->info('First-party session continuity cookie: a random 16-byte nonce (hex, HttpOnly, SameSite=Strict) that links requests from the same browser into the risk engine\'s "session" signal. It carries NO identity — it is a fresh random value, and the engine only ever stores its keyed pseudonym.')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('name')
                                    ->defaultValue('__Host-kiwi-session')
                                    ->cannotBeEmpty()
                                ->end()
                                ->integerNode('ttl_secs')
                                    ->info("Cookie lifetime (default 30 minutes; the spec 15-30 minute window; 0 = session cookie).")
                                    ->defaultValue(1800)
                                    ->min(0)
                                ->end()
                                ->scalarNode('path')
                                    ->defaultValue('/')
                                ->end()
                                ->enumNode('samesite')
                                    ->values(['lax', 'strict', 'none'])
                                    ->defaultValue('strict')
                                ->end()
                                ->booleanNode('http_only')
                                    ->defaultValue(true)
                                ->end()
                                ->booleanNode('secure')
                                    ->info('Secure flag; null (default) = follow the request scheme (set when the request is HTTPS).')
                                    ->defaultNull()
                                ->end()
                            ->end()
                        ->end()
                        ->scalarNode('region')
                            ->info('Optional deployment region (e.g. "eu-central-1") baked into every issued challenge record and enforced by the verifier: a result token issued in one region is never redeemable elsewhere (Option A of the failover-replay mitigation — the FailoverReplay audit). When null, no region is recorded and verification never applies a region check.')
                            ->defaultNull()
                        ->end()
                        ->arrayNode('redis')
                            ->info('Redis hardening for the CHALLENGE storage (KiwiCaptcha\\Storage\\RedisStorage) — the failover-replay/replay-safety knobs. wait_replicas/wait_timeout_ms issue a verified WAIT after every durability-critical challenge-storage write — issuance, the pending-to-consumed transition, the deterministic-result commit, and the terminal delete-if-pending deletion — so each write has reached N replicas before the caller proceeds (async-replication failover can otherwise lose the write or resurrect a consumed/burned record from a stale replica). Supported for STANDALONE Redis connections only: a Predis Sentinel/replication aggregate and a Predis cluster aggregate are both refused by the storage constructor with wait_replicas > 0 (WAIT is connection-relative: a replication aggregate\'s failure retry executes the WAIT on a replacement connection whose write offset is empty, and a cluster aggregate cannot route a keyless WAIT). ttl_margin_secs extends the retention of challenge/replay-security state beyond the token validity window (must exceed max clock skew + failover margin — pair with a noeviction policy on the security Redis, see README).')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->integerNode('wait_replicas')
                                    ->info('WAIT numreplicas for every durability-critical challenge-storage write (default 0 = disabled): issuance, the pending-to-consumed transition, the deterministic-result commit, and the terminal delete-if-pending deletion each block until at least this many replicas acknowledged the write. Strengthens replay safety across async replication failover — a write acknowledged by the primary alone can be lost on failover, letting a consumed or burned challenge be replayed against a stale replica after promotion. Supported for STANDALONE Redis connections only: with a Predis Sentinel/replication aggregate or a Predis cluster aggregate the value must stay 0 (the storage constructor refuses both with wait_replicas > 0 — WAIT is connection-relative: a replication aggregate\'s failure retry executes the WAIT on a replacement connection whose write offset is empty, and a cluster aggregate cannot route a keyless WAIT by slot).\n\nHA REPLAY-SAFETY DEPLOYMENT PROFILE: WAIT is acknowledgement hardening, not consensus — it strengthens the durability contract but does NOT by itself guarantee single-use survives every failover. With wait_replicas = 0 (the default), a challenge consumed on the primary can still be replayed after a failover promotes a replica that never received the consume: atomic replay safety holds per Redis authority, but NOT across authority changes. A hardened deployment must choose one of: (A) no automatic promotion for the security Redis (fail closed during failure); (B) wait_replicas > 0 AND a promotion policy that only elects a replica acknowledged by the wait (a sufficiently caught-up replica); or (C) a security-state backend whose acknowledged-write contract itself gives the required durability/consensus property. Do not claim strict replay safety across arbitrary asynchronous failover with wait_replicas = 0.')
                                    ->defaultValue(0)
                                    ->min(0)
                                ->end()
                                ->integerNode('wait_timeout_ms')
                                    ->info('WAIT timeout in ms for the replicas acknowledged (default 100). Only meaningful when wait_replicas > 0.')
                                    ->defaultValue(100)
                                    ->min(1)
                                ->end()
                                ->integerNode('ttl_margin_secs')
                                    ->info('Extra retention on challenge/replay-security state beyond token validity, in seconds (default 0). The challenge record and every consumed-state guard must outlive token validity + max clock skew + failover margin, so a replayed/expired token can never land on a state that already expired and re-accepted it. Pair with a noeviction policy on the security Redis (see README).')
                                    ->defaultValue(0)
                                    ->min(0)
                                ->end()
                            ->end()
                        ->end()
                        ->integerNode('max_outstanding_challenges')
                            ->info('Anti-stockpiling bound: maximum UNSOLVED challenges a single source may hold at once (default 20, min 1). The outstanding accounting is an expiry-aware MEMBERSHIP, not a counter: every issuance atomically prunes expired members, ZADDs the nonce to the source membership ZSET ({kiwi:<ns>}:outstanding:<HMAC(canonical ip)>, member = nonce, score = the Redis-clock deadline) and the live membership ({kiwi:<ns>}:outstanding:global:live), and refuses when the LIVE count reaches the cap. A successful verification, cancellation or proven-not-handed-off issuance removes the nonce from both memberships (one-shot, nonce-authoritative). The memberships expire by their deadlines, and both keys carry a key-level EXPIREAT (latest member deadline + ttl margin) so an abandoned source key cannot accumulate. The challenge endpoint returns the 429 risk-denied response on exhaustion. Bounded memory: an attacker can never stockpile an unbounded number of live challenges for a single source or deployment.')
                            ->defaultValue(20)
                            ->min(1)
                        ->end()
                        ->integerNode('max_outstanding_challenges_global')
                            ->info('Deployment-wide anti-stockpiling cap on outstanding unsolved challenges (default 100000, min 1) — the {kiwi:<ns>}:outstanding:global:live membership ZSET holds every live challenge nonce scored at its Redis-clock deadline; expired members are pruned on every issuance and the cap counts the LIVE members. A source-level solve removes the nonce from the membership like any other release (global pressure is deployment-wide and identity-neutral). The key carries a key-level EXPIREAT (latest member deadline + ttl margin). Exhaustion returns the 429 risk-denied response.')
                            ->defaultValue(100000)
                            ->min(1)
                        ->end()
                        ->arrayNode('challenge_origin_allowlist')
                            ->info('Origin laundering defense: when NON-EMPTY, the challenge POST must carry an Origin header (or Referer-origin fallback) whose scheme+host+port exactly matches one allowlisted origin — otherwise the request is rejected with HTTP 403 origin_rejected BEFORE any CAPTCHA is issued (never a rate-limit hit, no state written). Requests with neither header cannot be matched and are rejected. Comparison is STRUCTURED NORMALIZATION : scheme/host/effective-port, host lowercased, default ports normalized (https 443 / http 80), trailing dots stripped, IDN hosts converted to punycode when ext-intl is available, IPv6 literals kept bracketed — so "https://example.com" matches "https://example.com:443", "https://EXAMPLE.COM." and "https://bücher.example" (as "xn--bcher-kva.example"), but never "https://example.com:444", "http://example.com" or "https://evil-example.com". Server-to-server integrations that cannot send an Origin keep enforce_origin=false (the Referer fallback or a bypassed check is the documented trusted mode). When non-empty, the challenge endpoint also emits `Content-Security-Policy: frame-ancestors <allowlisted origins, space-separated>` .')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->booleanNode('enforce_origin')
                            ->info('When true, challenge requests WITHOUT an Origin header — or carrying the literal "null" Origin (opaque/sandboxed origins) — are rejected with HTTP 403 origin_rejected, even when the allowlist is empty. When the allowlist is NON-EMPTY the (required) Origin must additionally be allowlisted (structured normalization). Browser-laundering defense: a framed/cross-site request either lacks a usable Origin or carries one that cannot match. Server-to-server integrations (no Origin header) MUST keep this false — the explicitly trusted mode.')
                            ->defaultValue(false)
                        ->end()
                        ->booleanNode('enforce_fetch_metadata')
                            ->info('When true, challenge requests whose Sec-Fetch-Site header is PRESENT and equals "cross-site" are rejected with HTTP 403 CROSS_SITE_REJECTED — a browser-laundering signal. Raw HTTP bots lack the header and are unaffected, so this is defense-in-depth only (never the security boundary).')
                            ->defaultValue(false)
                        ->end()
                        ->scalarNode('network_classifier_file')
                            ->info('Optional path to a CIDR classifier file ("cidr,flag1,flag2" per line; flags: reserved, hosting, proxy, tor, blocked). Sources in flagged blocks raise the network_risk signal: 600 for hosting, 650 for Tor exits, 750 for known proxies, 950 for reserved and 1000 for blocked. Default null = no network flags.')
                            ->defaultNull()
                        ->end()
                        ->scalarNode('request_binding')
                            ->info('OPTIONAL STATIC transaction binding : a fixed string (1..128 chars, no "|") baked (signed) into every issued challenge when the challenge request carries no request_binding field of its own. For DYNAMIC per-transaction bindings (recommended: a random nonce per page load) the application supplies the binding per request — the widget reads data-kiwi-request-binding, sends it with the challenge POST, carries it in the hidden kiwi_request_binding form field, and the controller/validator enforce it (a challenge bound to one transaction is never redeemable for another). Static binding is the fallback for server-side integrations that never send the field.')
                            ->defaultNull()
                        ->end()
                        ->arrayNode('health')
                            ->info('Rollback-resistant readiness : /health/live is always 200 while the process runs; /health/ready returns 200 only when the signing keys are configured, the security Redis answers a PING (probe cached ~1 s; transient probe timeouts are absorbed by the cache — a single blip never flips a healthy deployment, Argon queue fullness is NEVER consulted), and the CENTRAL security-policy state ({kiwi:<ns>}:security-policy hash: min_protocol_version, min_policy_epoch) is compatible — when the key is present, ready requires min_protocol_version <= 2 (this binary\'s max protocol) AND min_policy_epoch <= risk.policy_version; when absent, the binary\'s own configuration is authoritative. Operators set the hash to protect mixed-version rolling deployments and rollbacks (see README).')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')->defaultTrue()->end()
                            ->end()
                        ->end()
                    ->end()
                    ->validate()
                        ->ifTrue(static fn (array $v): bool => ($v['chaining']['enabled'] ?? false)
                            && (!($v['enabled'] ?? false) || ($v['request_binding_authority'] ?? null) === null))
                        ->thenInvalid('risk.chaining.enabled requires risk.enabled=true AND a non-null risk.request_binding_authority — the chain is a server-side transaction obligation anchored on the AUTHORITATIVE binding, never on an unexamined client string')
                    ->end()
                ->end()
            ->end()
            // Cross-field rotation invariants over the signing key
            // identity (kid, secret_key, secrets_by_kid, revoked_kids),
            // validated here on the root node where all four are in
            // scope. Each combination below is a guaranteed-outage or
            // silently-weakened-security configuration, refused at
            // compile time instead of failing on the first challenge.
            // Each validate() call appends one rule (a single ExprBuilder
            // keeps only its last ifTrue/thenInvalid pair). The
            // secrets_by_kid keys are canonicalized to ints by the map
            // node's own rules first; the cross-field comparisons still
            // run through self::canonicalKid() so a textual alias can
            // never bypass them.
            ->validate()
                ->ifTrue(static fn (array $v): bool => \in_array($v['kid'], $v['revoked_kids'], true))
                ->thenInvalid('kiwi_captcha.kid must not appear in kiwi_captcha.revoked_kids: issuing under a revoked kid is a guaranteed outage, since every freshly issued challenge would fail verification with UnknownKid. Remove the kid from revoked_kids (revocation applies to superseded keys only) or bump kid to a new signing key id')
            ->end()
            ->validate()
                ->ifTrue(static function (array $v): bool {
                    foreach (\array_keys($v['secrets_by_kid']) as $historicalKid) {
                        if (self::canonicalKid($historicalKid) === (int) $v['kid']) {
                            return true;
                        }
                    }

                    return false;
                })
                ->thenInvalid('kiwi_captcha.secrets_by_kid must not contain the current kiwi_captcha.kid: a historical entry for the current signing key would make the verifier select the wrong secret. The current secret belongs in kiwi_captcha.secret_key, not in the historical map')
            ->end()
            ->validate()
                ->ifTrue(static function (array $v): bool {
                    foreach (\array_keys($v['secrets_by_kid']) as $historicalKid) {
                        $canonical = self::canonicalKid($historicalKid);
                        if ($canonical === null || $canonical > (int) $v['kid']) {
                            return true;
                        }
                    }

                    return false;
                })
                ->thenInvalid('every kiwi_captcha.secrets_by_kid key must be strictly below kiwi_captcha.kid: the map holds historical signing keys only, and a future key would silently extend the verifier rollback/forward guard (a record kid above the newest ring key) so no deployment should accept it. Bump kid above the newest historical key when rotating')
            ->end();

        return $treeBuilder;
    }

    /**
     * Canonical kid of a secrets_by_kid map key: a strictly-positive
     * canonical decimal integer within the signing kid range, or null for
     * anything else (text, leading zeros, out of range). The cross-field
     * rotation rules compare these canonical ints so a textual alias like
     * '02' can never bypass or collide with a numeric kid.
     */
    private static function canonicalKid(int|string $raw): ?int
    {
        if (\is_int($raw)) {
            $canonical = $raw;
        } elseif (preg_match('/^[1-9][0-9]*$/D', $raw) === 1) {
            $canonical = (int) $raw;
        } else {
            return null;
        }
        if ($canonical < 1 || $canonical > 4294967295) {
            return null;
        }

        return $canonical;
    }
}
