-- Proposed migration (NOT WIRED — coordinate with the migrations owner).
--
-- Problem (audit item I.5): APPEND/COPY dedup drops mail.
--
-- Today `idx_mail_messages_dedup` enforces uniqueness on
-- (account_id, mailbox_id, message_id), and `store_message` silently
-- returns the EXISTING row's (id, uid) when a duplicate Message-ID is
-- inserted into the same mailbox. Consequences:
--
--   1. COPY of a message into a mailbox that already has that Message-ID
--      returns a COPYUID mapping to the EXISTING uid — no new row is
--      created, so the "copy" is an alias, not a copy.
--   2. When the aliased original is expunged, the copy "vanishes": the
--      client was told the copy exists (COPYUID), but the backing row is
--      gone. That is silent data loss from the user's point of view.
--   3. APPEND of a duplicate returns the APPENDUID of the existing message
--      with no indication it was a dedup hit.
--
-- Dedup is the right behavior for DELIVERY (SMTP redelivery of the same
-- message must not duplicate it), but wrong for user-initiated
-- COPY/APPEND, where the user explicitly asked for a second instance.
--
-- Recommended schema change: keep delivery dedup, but allow explicit
-- copies. Add a boolean column marking rows created by the dedup-exempt
-- path and drop it from the unique index:
--
--     ALTER TABLE mail_messages
--         ADD COLUMN dedup_exempt BOOLEAN NOT NULL DEFAULT FALSE;
--
--     DROP INDEX IF EXISTS idx_mail_messages_dedup;
--
--     CREATE UNIQUE INDEX idx_mail_messages_dedup
--     ON mail_messages(account_id, mailbox_id, message_id)
--     WHERE message_id IS NOT NULL AND message_id != ''
--       AND dedup_exempt = FALSE;
--
--     -- Optional: advisory marker for APPEND dedup hits.
--     -- (Untagged `* OK [DUP]`-style notes are NOT standard IMAP; a
--     -- server-side log + response-code-free NO is the RFC-safe route.)
--
-- Application changes required alongside (mailstore-core):
--   * `store_message` gains a `dedup_exempt: bool` parameter (or the
--     gRPC StoreMessageRequest/CopyMessageRequest carry it); SMTP delivery
--     keeps FALSE, IMAP COPY/APPEND passes TRUE so a real row is created.
--   * With this migration absent, current behavior is preserved: COPY
--     reports the existing uid (documented in regression tests) and APPEND
--     returns the existing uid. The vanishing-copy hazard remains until
--     this migration lands.
