apiVersion: v1
kind: ServiceAccount
metadata:
  name: enterprise
  namespace: apexmail
  labels:
    app.kubernetes.io/name: enterprise
    app.kubernetes.io/component: enterprise
automountServiceAccountToken: false