apiVersion: v1
kind: Service
metadata:
  name: enterprise
  namespace: apexmail
  labels:
    app.kubernetes.io/name: enterprise
    app.kubernetes.io/component: enterprise
spec:
  selector:
    app.kubernetes.io/name: enterprise
  ports:
    - name: http
      port: 3002
      targetPort: http
      protocol: TCP
  type: ClusterIP