{{- if .Values.worker.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apexmail.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apexmail.labels" . | nindent 4 }}
    {{- include "apexmail.selectorLabels" (dict "name" "worker" "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "apexmail.selectorLabels" (dict "name" "worker" "context" .) | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.worker.healthPort }}
      targetPort: health
      protocol: TCP
{{- end }}